README.md
geopandas/plotting.py

add the ability to pass ``edgecolor`` to ``plot_dataframe``, ``plot_series``

Plot edge options

---

examples/null_geom.geojson
geopandas/base.py
geopandas/geodataframe.py
tests/test_geodataframe.py
tests/test_geom_methods.py

This copy includes commits in stale P.R. #156.  I'm re-posting under my account to be able to iterate and get it merged, toward issue #139.
I'm not 100% acquainted with all these commits quite yet, but I am willing to figure it out, discuss the design, and iterate as necessary.

Handle missing geoms

---

.travis.yml
geopandas/tools/geocoding.py
requirements.test.txt
tests/test_geocode.py

Use most recent geopy release and fix API accordingly.
Closes #200

Update geopy version

---

README.md
geopandas/base.py
geopandas/sindex.py
geopandas/tools/sjoin.py
setup.py
tests/test_sjoin.py

Closes #217
Most things were already inplace to have this optional, and I think with this it should be ok.

Make rtree an optional dependency

---

tests/test_plotting.py

Fix tests after #228
(see also comments here: https://github.com/geopandas/geopandas/pull/186#discussion_r43541233)

Fix test after colormap->cmap change

---

geopandas/plotting.py

Deprecation warning for axes and colormap

---

doc/source/install.rst

An small update to the install section (correct the the requirements), remove the hard coded version number, added conda with mention of ioos channel, ..)

DOC: update install instructions

---

geopandas/io/file.py

improve read_file docstring

---

geopandas/geoseries.py
tests/test_geoseries.py

Fix GeoSeries.to_json

---

README.md
examples/nyc_boros.py
tests/test_geodataframe.py
tests/test_io.py
tests/test_overlay.py
tests/test_sindex.py
tests/test_sjoin.py
tests/util.py

Change download_nybb() to return shapefile name and path within the zip file.   Fix for issue #295   A few changes to make the code a little more maintainable.

Update nybb url.

---

doc/source/contributing.rst
doc/source/data_structures.rst
doc/source/index.rst
doc/source/install.rst
doc/source/io.rst

Addresses my remaining comments in PR #283 of @nickeubank

DOC: some clean-up after #283

---

geopandas/__init__.py
geopandas/tests/test_overlay.py
geopandas/tools/tests/test_sjoin.py

move sjoin to top-level namespace

---

geopandas/geodataframe.py
tests/test_dissolve.py

Sketch of implementation for  #310. 
(Open issues: clean up; catch errors; handle string aggfuncs)

Add dissolve method to GeoDataFrame

---

doc/source/data_structures.rst
doc/source/mapping.rst
doc/source/mergingdata.rst
doc/source/projections.rst
doc/source/set_operations.rst
geopandas/__init__.py

ref #281, docs examples were broken since #312, so fixing references to example data

DOC: loading example datasets with new method

---

geopandas/geodataframe.py
geopandas/tests/test_dissolve.py

Continuation (and resolution?) of #311

Dissolve tweaks

---

CHANGELOG

Started with a small overview of changes for 0.2

Add changelog for v0.2.0

---

geopandas/plotting.py

Fixes 356: let PySAL own logic for k

---

geopandas/plotting.py
geopandas/tests/test_plotting.py

Fixes 359: raise ValueError on unsupported scheme

---

.travis.yml
requirements.test.txt

TST: switch to codecov for coverage testing

---

geopandas/tools/tests/test_sjoin.py

Closes #423
From the notebook http://nbviewer.jupyter.org/gist/jorisvandenbossche/751809b631f30579b9859e6bf75d2657

TST: add more robust tests for sjoin (GH423)

---

.travis.yml

Update newest tested matplotlib to version 1.5.3

TST:Add Pandas version 0.20.2 to Travis testing

---

geopandas/base.py
geopandas/geodataframe.py
geopandas/tests/test_geom_methods.py

Wraps `total_bounds` as a numpy array. I don't *think* this should change any of the tests etc...let's see :-)
Closes #458

total_bounds is an array

---

geopandas/tests/test_geoseries.py
geopandas/tests/test_pandas_methods.py

For refactoring the internals, to have some more tests with pandas interaction (how pandas methods currently behave)

TST: add more extensive tests of pandas functionality

---

CHANGELOG.md
geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py

Closes https://github.com/geopandas/geopandas/issues/225
See [jupyter notebook with usage examples](https://gist.github.com/emiliom/bde588461f816a0f0b5e4ae47ffbcc20)

ENH: GeoDataFrame.from_features to accept FeatureCollection as well

---

geopandas/_geos.pxi
geopandas/base.py
geopandas/tests/test_geom_methods.py
geopandas/tests/test_vectorized.py
geopandas/vectorized.pyx

This isn't optimally fast, but might be faster than current methods of densification
cc @jorisvandenbossche 
This currently depends on #500 
```python
In [1]: from shapely.geometry import Polygon
In [2]: coords = [((0, 0), (1, 1), (1, 0), (0, 0)),
...:           ((0, 0), (0, 10), (10, 10), (10, 0), (0, 0))]
...: polys = [Polygon(c) for c in coords] + [None]
...:           
In [3]: import geopandas as gpd
In [4]: s = gpd.GeoSeries(polys)
In [5]: s.exterior.coords()
Out[5]: 
[((0.0, 0.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0)),
((0.0, 0.0), (0.0, 10.0), (10.0, 10.0), (10.0, 0.0), (0.0, 0.0)),
()]
```

Cythonize get coordinates

---

geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py

We unpack the geometry and normal pandas data and then repack in setstate

Fix GeoDataFrame pickling

---

.travis.yml
geopandas/geoseries.py
geopandas/tests/test_geoseries.py
requirements.txt

This should for now close #509 (although I am not really satisfied with the fix -> still relies on the fact that the array interface for Polygon won't change).

BUG/COMPAT: fix fillna by filling with Polygon instead of Point

---

geopandas/base.py
geopandas/tests/test_geom_methods.py

Pass through kwargs for GeoSeries.buffer

---

geopandas/tests/test_pandas_methods.py
geopandas/vectorized.pyx

- fix tests for changed order of columns (geometry column is now last column)
- add tolist to GeometryArray (for iteration in pandas)

Fix failing tests

---

geopandas/geoseries.py
geopandas/tests/test_geoseries.py
geopandas/tests/test_pandas_methods.py

@mrocklin I would like an eye on this to see if this is what you had in mind (I am not too familiar with `__new__`, and it also feels a bit messy with the need to define a dummy `__init__`)

GeoSeries to return Series when non-geometry data are passed

---

geopandas/tools/sjoin.py

We switch the sides of the join and use the complementary predicate.
This seems to be significantly faster in the common case.
Fixes https://github.com/geopandas/geopandas/issues/563
@andreas-h if you have a chance to try your code on this branch I would be very grateful.
@brendancol may also have run into this

Implement sjoin within with contains

---

geopandas/tools/sjoin.py
geopandas/tools/tests/test_sjoin.py

Analog of #577 for cython branch.

TST: Add CRS mismatch warning to cython branch

---

CHANGELOG.md
README.md
benchmarks/transform.py
geopandas/base.py
geopandas/plotting.py
geopandas/tests/test_geodataframe.py
geopandas/tests/test_geom_methods.py
geopandas/tests/test_overlay.py
geopandas/tests/test_plotting.py
geopandas/tests/test_sindex.py
geopandas/tools/overlay.py
geopandas/tools/tests/test_sjoin_old.py

New round of cherry-picks of commits to master since last round.

Update geopandas-cython branch with changes in master

---

geopandas/_block.py
geopandas/tests/test_pandas_methods.py
geopandas/tests/util.py

BUG: correct filling logic for GeoSeries.reindex

---

geopandas/_block.py
geopandas/geoseries.py
geopandas/io/file.py
geopandas/tests/test_geocode.py
geopandas/tests/test_geodataframe.py
geopandas/tests/test_geoseries.py
geopandas/tests/test_pandas_methods.py
geopandas/tests/test_vectorized.py
geopandas/tools/tests/test_sjoin.py
geopandas/vectorized.pyx

This fixes a few of the xfailing tests.  Going through this commit-by-commit probably makes sense.

Fix missing data handling

---

geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py

Closes https://github.com/geopandas/geopandas/issues/528

Do not densify geometries in __setitem__

---

geopandas/geodataframe.py
geopandas/geoseries.py
geopandas/tests/test_geodataframe.py

Real PITA .. (but this occurred in the concat with axis=1 PR)

BUG: fix cornercase in __setitem__ when column already exist but is non-geometry

---

geopandas/tests/test_geodataframe.py

Simple test effectively replicating the test on a not-inplace transform.

TST: Test inplace transform on geodataframe

---

geopandas/io/file.py

PERF: writing mutliple records at once to increase speed in GeoPackage

---

appveyor.yml

CI: build env in one go

---

geopandas/tools/tests/test_sjoin.py

Looking to test out issue raised in #637.

TST: Add test of naturalearth spatial join

---

appveyor.yml
appveyor/stdbool.h
geopandas/algos.c

BLD: enable to build for Python 2.7 on Windows (vc9)

---

geopandas/tests/test_datasets.py

Parametrized test for test_dataset.py
Related to: #644

TST: parametrized test_datasets.py tests

---

geopandas/tests/test_dissolve.py

Removed testing class in `test_dissolve.py`, using fixtures instead.

TST: Fixtures and test clean up for test_dissolve.py

---

geopandas/_geos.pxi
geopandas/tests/test_vectorized.py
geopandas/vectorized.pyx

Vectorized function to create GeometryArray from array of WKB bytes objects. Can add a `from_wkt` as well (and maybe also the `to_` versions).

Add vectorized from_wkb / from_wkt functions

---

geopandas/geodataframe.py
geopandas/io/file.py
geopandas/io/tests/test_io.py

Closes https://github.com/geopandas/geopandas/issues/649

BUG: read empty files correctly

---

geopandas/tests/test_geocode.py

@jorisvandenbossche started work on test_geocode.py, just wondering how you think the best way to deal with the  ForwardMock and ReverseMock classes is with regards to pytest?

TST: test_geocode.py pytest conversion

---

geopandas/io/file.py
geopandas/tests/test_geodataframe.py

[WIP] Error message for writing empty dataframe to file

---

geopandas/geoseries.py

Should fix the failing tests on pandas master (xref https://github.com/pandas-dev/pandas/issues/20391)

BUG: fix GeoSeries construction from scalar on pandas master

---

examples/create_geopandas_from_pandas.py

First attempt to address #689 
Closes #689

Building a GeoDataFrame from DataFrame

---

geopandas/plotting.py
geopandas/tests/test_plotting.py

Resolves #664.
I think this looks right, mostly just re-used the methods & tests for plotting MultiPolygons.

ENH: add support for plotting MultiPoints

---

geopandas/base.py

It was not clear what the integer in the multi-index represented

DOC: clarify MultiIndex of explode() return value

---

geopandas/base.py
geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py
geopandas/tests/test_geom_methods.py

Related to #667 .
@jorisvandenbossche not sure what the desired behaviour for the resulting GeoDataFrame index is? Left it as suggested in the example, could also be fully reset?

ENH: explode() method for geodataframe

---

geopandas/plotting.py
geopandas/tests/test_plotting.py

Closes https://github.com/geopandas/geopandas/issues/768
1) Check if color and column are defined. Original assumption was
that both are strings. This is no longer the case, now we check if
they are not None (if they exist).
2) The docstring was updated to state that now column accepts np.array or
pd.Series
3) Added conditional statement to check if:
a) The passed column is a pd.Series or a np.array
b) The passed column has the same number of elements as df has rows
4) Added instruction to assign the column to variable values:
if it is an array (pd.Series or np.array)
or if it is a column in the df

ENH: pass array/series of values to column argument in plot

---

CHANGELOG.md

@jdmcbr I also had some updates, merged it with your update

DOC: Update changelog

---

CHANGELOG.md

Correcting the changelog date for Release 0.4.0 from 2017 to 2018

Correcting the changelog date for Release 0.4.0 from 2017 to 2018

---

geopandas/plotting.py

Resolves #698.
Added check in `_flatten_multi_geoms` to see if there are multi-geometries and whether the flattening is needed.

PERF: added check for multi-geometries

---

MANIFEST.in

@jorisvandenbossche this will ensure that the license is packaged with the source.

package license file

---

doc/source/aggregation_with_dissolve.rst
doc/source/mergingdata.rst

This is a followup PR to 
https://github.com/geopandas/geopandas/issues/732
I am updating the documentation for gpd.sjoin() to be a bit more explicit. 
Please bare with me as this is my first actual contribution to an OS repo (i've submitted issues but never contributed content). I've directly edited the `.rst` files and welcome comments wherever you'd like changes. 
Once i understand how to best suggest changes I will update other parts of the docs as i create lessons for my python class! :)

DOC updating spatial merge docs with argument details

---

geopandas/base.py
geopandas/geoseries.py

Part of https://github.com/geopandas/geopandas/pull/835 that is unrelated to ExtensionArrays, so split off.
Harmonized the helper functions for binary/unary spatial ops + some PEP8 clean-up.

CLN: clean-up base.py

---

geopandas/io/file.py
geopandas/io/tests/test_io.py

Use fiona.Env() for new versions to avoid warning

---

geopandas/geodataframe.py

Rename keys to col in docstring to correspond with method signature

DOC: fix param name for GeoDataFrame.set_geometry

---

geopandas/tests/test_plotting.py

Change of the dataset (#808) was merged without updating `test_legend` and `test_classification_kwds`. I have changed expected values to match new data. This is also causing other failure of checks other recent PRs.

Tests updated to match new sample dataset

---

doc/source/conf.py
geopandas/geodataframe.py

Docs were failing because expected failure was unexpectedly not failing.
:)
Also minor changes to postgis doc in order to quiet warning.

DOC: Add geoplot example back to doc

---

doc/source/io.rst

I have added just a couple of examples of reading / writing files to docs as it was a bit empty. I made examples of keywords usage for driver as well as layer (GeoPackage).

Added couple of read / write examples to docs

---

.travis.yml

Hopefully fixes https://github.com/conda-forge/fiona-feedstock/issues/121

use strict channel

---

geopandas/base.py
geopandas/tests/test_geom_methods.py

Closes https://github.com/geopandas/geopandas/issues/912
cc @martinfleis

BUG: unary/binary geo ops with all-empty result raise error

---

README.md
doc/source/index.rst

Better list different communication channels (eg the fact that we have a mailing list .. :))
(inspired by the xarray readme https://github.com/pydata/xarray/)

DOC: add different communication channels to README/docs

---

.travis.yml
ci/travis/35-minimal.yaml

Try to fix the failing CI (not sure what update to Anaconda changed this)

CI: too old fiona installed on py3.5-minimal build

---

doc/source/conf.py

Just a tiny update to include 2019 in copyright.
I am going to merge, as there is basically nothing to review.

DOC: updated year in copyright

---

geopandas/tests/test_types.py

This should make CI green again.

TST: remove select test (removed in pandas 0.25.0)

---

geopandas/tests/test_geodataframe.py
geopandas/tests/test_geoseries.py

Some tests I wrote in the process of the refactor (https://github.com/geopandas/geopandas/pull/835) that were already passing on master.

TST: additional constructor and getitem tests

---

geopandas/geoseries.py
geopandas/tests/test_geoseries.py
geopandas/tests/test_pandas_methods.py

Retake of earlier PR https://github.com/geopandas/geopandas/pull/572 (from the cython branch) but for the master branch now.

GeoSeries to return Series when non-geometry data are passed (#572)

---

.travis.yml
appveyor.yml
geopandas/tests/test_pandas_methods.py

See https://github.com/pandas-dev/pandas/issues/27035

TST: no strict xfail on flaky drop_duplicates test

---

geopandas/tests/test_geodataframe.py
geopandas/tests/test_merge.py
geopandas/tests/test_pandas_methods.py

Some additional tests from PRs that were merged in the cython branch, for which the fix is no longer relevant for master (eg because it already works, or the fix was specific to the custom block), but we still can add the tests to master (#583, #591, #596, https://github.com/geopandas/geopandas/pull/515)

TST: additional tests

---

geopandas/tests/test_geodataframe.py
geopandas/tests/test_geoseries.py

Some additional tests from https://github.com/geopandas/geopandas/pull/835

TST: additional asserts in constructor tests

---

examples/plotting_with_geoplot.py

See https://github.com/geopandas/geopandas/pull/1044

DOC: fix dataset usage from geoplot

---

geopandas/array.py
geopandas/geoseries.py
geopandas/tests/test_geoseries.py

Closes https://github.com/geopandas/geopandas/issues/1047

TST: test GeoSeries constructor fallback in case of list-like scalars

---

geopandas/_compat.py
geopandas/tests/test_api.py
geopandas/tests/test_extension_array.py

Closes https://github.com/geopandas/geopandas/issues/1045

Avoid importing pytest in main geopandas import

---

.travis.yml
CHANGELOG.md
appveyor.yml
doc/source/conf.py
geopandas/plotting.py
geopandas/tests/test_plotting.py
geopandas/tests/test_types.py

Starting a branch to cherry-pick commits for the bug fix release

Backports for the 0.5.1 bugfix release

---

README.md
doc/source/geometric_manipulations.rst
geopandas/base.py
geopandas/geoseries.py

Some of the examples do not work with modern tools, and some of the outputs have changed.
These are now revised and refreshed.

DOC: refresh with Python 3 syntax, and modern outputs

---

doc/source/reference.rst
geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py

ENH: add rename_geometry() method 

---

geopandas/tests/test_array.py

Moving a bunch of additional array tests from the geopandas-cython branch to master, now we have the GeometryArray (ExtensionArray) in master as well.

TST: add additional GeometryArray tests

---

geopandas/base.py
geopandas/geodataframe.py
geopandas/geoseries.py

Closes https://github.com/geopandas/geopandas/issues/1042

CLN: implement CoordinateIndexer .cx without using pandas internals

---

ci/travis/37-dev.yaml
ci/travis/37-latest-defaults.yaml

Try to fix Travis CI, xref https://github.com/scipy/scipy/issues/10637

CI: pin python to 3.7.3 (pip install issues with 3.7.4)

---

examples/create_geopandas_from_pandas.py

Fixes #1060 , added another plot to confirm visually.

fixed WKT order in `create_geopandas_from_pandas` example

---

geopandas/_version.py

correcting minor typo in _versions.py

---

geopandas/array.py
geopandas/tests/test_extension_array.py
geopandas/tests/test_pandas_methods.py

Addresses https://github.com/geopandas/geopandas/issues/1100
@martinfleis this at least adds it back with the exact same behaviour as before. 
I am not fully sure what to do further (leave it as is, deprecate it).

Re-enable GeoSeries.any/all

---

geopandas/array.py
geopandas/tests/test_array.py

Closes https://github.com/geopandas/geopandas/issues/1130
We already had this fix in a few places, but not yet consistently in all places.

BUG: fix geometry methods to handle single MultiGeoms output

---

doc/source/install.rst

update installation information about pyproj

---

doc/source/index.rst
doc/source/missing_empty.rst

Closes https://github.com/geopandas/geopandas/issues/1098

DOC: add docs on missing and empty geometries

---

geopandas/array.py

xref https://github.com/pandas-dev/pandas/pull/28389

REF: implement size for 2D compat

---

CHANGELOG.md

Preparing for actual 0.6.0 release (will keep this open until we actually do the release).

RLS/DOC: update changelog for final 0.6.0 release

---

geopandas/tests/test_config.py

I actually wrote tests in https://github.com/geopandas/geopandas/pull/1057 for the new options code, but apparently I forgot to "git add" it ;)

TST: add tests for new options

---

geopandas/geodataframe.py
geopandas/tests/test_pandas_methods.py

Closes https://github.com/geopandas/geopandas/issues/1144

BUG: allow astype to work on invalid GeoDataFame + fix astype(object)

---

geopandas/array.py
geopandas/tests/test_pandas_methods.py

Closes https://github.com/geopandas/geopandas/issues/1149

BUG: allow specifying np.nan in fillna

---

geopandas/geodataframe.py

DOC: add docstring for geodataframe.py merge function

---

geopandas/_compat.py
geopandas/array.py
geopandas/tests/test_array.py
geopandas/tests/test_geom_methods.py
geopandas/tests/test_pandas_methods.py

Closes https://github.com/geopandas/geopandas/issues/1195, closes https://github.com/geopandas/geopandas/issues/1184

BUG: fix bounds/total_bounds for empty GeometryArray/GeoSeries

---

geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py
geopandas/tests/test_pandas_methods.py

Closes https://github.com/geopandas/geopandas/issues/1190

BUG: fix index type in filtering/take or creation of empty GeoDataFrame

---

geopandas/io/tests/test_file.py

Closes #1199.
Also added gpkg to the drivers to test reading/writing.

TST: Add tests of pathlib.Path for file i/o

---

doc/source/io.rst

DOC: Add docs for using read_file on a ZIP file

---

doc/source/mapping.rst

DOC: Add example docs for plotting transparent polygons

---

geopandas/tests/test_sindex.py

See https://github.com/geopandas/geopandas/issues/1221, this should at least make CI green again.

TST: fix tests to work with rtree 0.9

---

.travis.yml

It would be good to also test with the development version of Shapely, so adding that here.

CI: test with shapely master

---

geopandas/array.py

Closes https://github.com/geopandas/geopandas/issues/1257, xref https://github.com/pandas-dev/pandas/pull/30308
cc @martinfleis

Fix GeometryArray indexing with pandas boolean array (pandas 1.0 compat)

---

.travis.yml
appveyor.yml
ci/travis/37-latest-conda-forge.yaml
ci/travis/38-latest-conda-forge.yaml

I have added conda-forge environment with python 3.8 to both appveyor and travis to have it covered. I was not able to make it work with conda defaults yet.

CI: test python 3.8

---

geopandas/array.py

I improved the utility function to check the indexer in pandas a bit (https://github.com/pandas-dev/pandas/pull/31150), which should make it simpler to use here

Update GeometryArray.__getitem__ for pandas 1.0 changes

---

geopandas/array.py

CI is failing with pandas master due to a changed error message in the extension array tests

TST: Update ExtensionDtype error message to follow pandas master

---

geopandas/array.py

COMPAT: update GeometryArray setitem to handle pandas1.0 nullable keys

---

geopandas/array.py
geopandas/tests/test_pandas_methods.py

Fixes #1149, which was already closed but IMO could stand to be re-opened :)
cc @martinfleis

API: Only raise TypeError for non-geometry in fillna if there are missing values

---

CHANGELOG.md

Companion with https://github.com/geopandas/geopandas/pull/1282

DOC: add changelog for 0.6.3

---

CHANGELOG.md
geopandas/_compat.py
geopandas/array.py
geopandas/tests/test_api.py
geopandas/tests/test_pandas_methods.py

Going to do a quick bug fix release with those two fixes

RLS 0.6.3 backports 

---

geopandas/array.py

This should fix the failing tests on pandas-master (pandas added some new tests related to setitem with slicing, that were failing in geopandas)

BUG: fix setitem with slices

---

doc/source/io.rst
geopandas/io/file.py
geopandas/io/tests/test_file.py

Closes #1157 
Opening PR so you can see the code and recommend changes. If you like the implementation, I can add some tests.

ENH: add support for filtered loading with open_file using mask and rows

---

doc/source/projections.rst

Still WIP, need to further fill in further sections. And are there other potential useful sections?
cc @martinfleis @snowman2

DOC: add upgrade guide for GeoPandas 0.7 / pyproj 2 / PROJ 6

---

geopandas/__init__.py
geopandas/array.py
geopandas/tests/test_array.py

Same points_from_xy at toplevel as in array

---

geopandas/tools/clip.py
geopandas/tools/tests/test_clip.py

Bugfix and tests for https://github.com/geopandas/geopandas/issues/1363
Please review and comment if possible; I'm new to this

BUG: return empty gdf for empty result of clip

---

.travis.yml
geopandas/tests/test_crs.py

Closes https://github.com/geopandas/geopandas/issues/1360

TST: turn off network usage in test_transform for PROJ>=7

---

doc/source/mergingdata.rst

DOC: fix typo in spatial join

---

doc/source/mergingdata.rst

Hi all,
Have amended the documentation slightly to try to fix issue [1186](https://github.com/geopandas/geopandas/issues/1186). If this is overkill as compared to the rest of the documentation, please let me know, as it might go into a bit too much detail compared to the rest.
Looking forward to your feedback,
Regards,
Tim.
Closes #1186

DOC: add example of appending GeoSeries

---

CONTRIBUTING.md
environment.yml
requirements-dev.txt
requirements.test.txt
requirements.txt

Also added notes on which packages are needed for which parts of
geopandas functionality outside of the core requirements.

Add pre-commit and black to dev requirements

---

doc/source/reference.rst

Small follow-up on https://github.com/geopandas/geopandas/pull/1248

DOC: add read_postgis/to_postgis to reference docs

---

geopandas/io/tests/test_sql.py
geopandas/tools/overlay.py
geopandas/tools/sjoin.py

Fix newly captured flake8 issues causing master to fail. https://travis-ci.org/github/geopandas/geopandas/jobs/686107588

STYLE: fix flake8 issues

---

benchmarks/clip.py
geopandas/tools/clip.py

Quick PR to implement the new spatial index capabilities in clip.

ENH: Implement sindex query in clip

---

.travis.yml
geopandas/base.py
geopandas/sindex.py
geopandas/tests/test_sindex.py
geopandas/tools/sjoin.py
geopandas/tools/tests/test_sjoin.py

MAINT: Unify spatial index error and empty handling

---

geopandas/array.py
geopandas/tests/test_array.py
geopandas/tests/test_overlay.py
geopandas/tools/clip.py
geopandas/tools/overlay.py
geopandas/tools/sjoin.py
geopandas/tools/tests/test_clip.py
geopandas/tools/tests/test_sjoin.py

Closes #1354 
Implements the same check and message we have in `array`.

ENH: consistent CRS mismatch check

---

geopandas/geodataframe.py

Example inspired by the pandas DataFrame docstring

DOC: Add example in GeoDataFrame docstring

---

geopandas/base.py
geopandas/tests/test_pandas_methods.py

BUG: override the .equals() method from pandas to correct isinstance

---

geopandas/_vectorized.py
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

ENH: add covered_by() method for GeoSeries

---

geopandas/array.py

xref https://github.com/geopandas/geopandas/issues/1432/#issuecomment-643599958

BUG: fix astype('string')

---

geopandas/base.py
geopandas/geodataframe.py

Let me know if the example isn't clear enough.

DOC: add example for is_empty

---

geopandas/array.py

See https://github.com/geopandas/geopandas/pull/1469

BUG: astype('string')

---

CONTRIBUTING.md
doc/source/contributing.rst

DOC: Travis doc link fix

---

doc/source/mergingdata.rst
geopandas/tools/sjoin.py

This applies the structure discussed in #1463. This should make it easier to further develop `sjoin` in the future. Please feel free to suggest other names, docstrings or arrangements, mine are somewhat arbitrary.

REF: refactor sjoin as per #1463

---

geopandas/plotting.py
geopandas/tests/test_plotting.py

Closes #1486 
I've also added test which loops through all available classifiers except `UserDefined` and checks if everything passes.

REGR: *Sampled plotting scheme fails

---

geopandas/geodataframe.py
geopandas/tests/test_crs.py

BUG: ensure CRS object also for empty GeoDataFrame

---

doc/environment.yml

Fix `environment.yml` to make RTD build again.

DOC: fix rtd

---

.pre-commit-config.yaml
geopandas/_vectorized.py
geopandas/array.py
geopandas/io/sql.py
geopandas/io/tests/test_file.py
geopandas/sindex.py
geopandas/testing.py
geopandas/tests/test_array.py
geopandas/tests/test_plotting.py
geopandas/tests/test_sindex.py

CI/LINT: update and pin black version

---

geopandas/tools/clip.py

Fixes #1570 
I'm a beginner and I've chosen this simple fix to start contributing. I'd be happy to receive any feedback about the pull request I've just submitted !

BUG: TypeError exception message in clip

---

geopandas/plotting.py

Fixes #1565
As for the other pull request, any feedback is welcome since I'm a beginner.

BUG: Warning when missing_kwds provided but no areas missing data

---

geopandas/_vectorized.py
geopandas/tests/test_crs.py

BUG: Handle missing geometry with to_crs and shapely

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/installation_issue.md
.github/ISSUE_TEMPLATE/submit_question.md

As a followup to #899, it would be nice to highlight this function, as
well as other useful information, when users are creating new bug
reports or requests for new features. These are copied and very lightly
edited from the templates used by pandas.

Create issue bug report and enhancement templates

---

doc/environment.yml

I forgot to add it after #1617.

DOC: add sphinx-toggleprompt to red environment

---

geopandas/_compat.py
geopandas/geodataframe.py
geopandas/tests/test_pandas_methods.py

closes #1654
Can use some additional tests (eg to also test flags), but putting it out here to check if this is working.

ENH: support pandas' new .attrs functionality

---

geopandas/sindex.py
geopandas/tests/test_sindex.py

ENH/MAINT: Let wrappers handle valid predicates

---

geopandas/geodataframe.py

REF: Add geometry and crs to GDF.__init__ signature

---

geopandas/plotting.py
geopandas/tests/test_plotting.py

Fixes #1657.
Should the edits of this pull request be accepted, they would need to be merged with the ones in #1694. 
What's the procedure in cases like that ? Should I submit a single pull request that closes the two issues ?
Also, should a test about plotting empty geometries be added ?

REG: Do not attempt to plot empty geometries

---

doc/source/getting_started/install.rst

DOC: Update rtree wheel information in installation instructions

---

geopandas/tests/test_plotting.py

Fixes #1717
I've fixed the tests where there were different lengths of actual and expected colors for the `_check_colors` function (sometimes a length was zero which means there was nothing actually being checked).
In order to avoid this situation I've also added a simple `assert` in `_check_colors`.
Please let me know if there is something that doesn't make sense even though the tests "are working".

TST: Fix plotting tests

---

.github/workflows/release_to_pypi.yml

GHA: ensure to upload sdist to GitHub release

---

.github/workflows/tests.yaml
ci/envs/37-dev.yaml
ci/envs/38-dev.yaml
geopandas/array.py
geopandas/io/tests/test_file.py
geopandas/tests/test_array.py
geopandas/tests/test_extension_array.py

See https://github.com/geopandas/geopandas/issues/1728
First commit to add CI (and to see failures), will further add commits with some fixes.

Fix compatilibilty with numpy 1.20.0

---

ci/envs/36-minimal.yaml

Test for https://github.com/geopandas/geopandas/pull/1811#issuecomment-770837759

CI: force fiona version to 1.8.13 for minimal build

---

geopandas/plotting.py
geopandas/tests/test_plotting.py

Fixes #1572
Part of the original issue was fixed in #1677, the rest is here.

REGR: ignore empty geometries in plot

---

geopandas/io/tests/test_file.py

TST: fix path to remote gejson

---

doc/environment.yml

xref #1835 
This is how the environment resolves on my ubuntu 18.04.

DOC: pin RTD environment

---

geopandas/tools/_show_versions.py

That's an optional dependency that is missing

Add pygeos to geopandas.show_versions()

---

geopandas/_compat.py
geopandas/array.py
geopandas/geoseries.py
geopandas/tests/test_array.py
geopandas/tests/test_crs.py
geopandas/tests/test_geoseries.py

REF: Implement to_crs and estimate_utm_crs in GeometryArray

---

geopandas/io/sql.py
geopandas/io/tests/test_sql.py

BUG: Add quotes to tablename in COPY

---

geopandas/geodataframe.py
geopandas/tests/test_crs.py

xref https://github.com/geopandas/geopandas/issues/902
Adding the same logic we added for GeoSeries (https://github.com/geopandas/geopandas/pull/1478) to GeoDataFrame as well

ENH: try to preserve CRS in GeoDataFrame.apply

---

geopandas/geodataframe.py
geopandas/tests/test_dissolve.py

See description in #1844.
Closes #1844

ENH: Add groupby kwargs to dissolve

---

doc/source/about.md

Temporarily hide docs from menus until there's some contents in it.

DOC: hide roadmap from docs

---

doc/source/community/contributing.rst

These are just some minor changes, but happy to revise the docs in more detail on a regular basis. 
Also happy to help out with new documentation content.
Please let me know if there is anything that is prioritized.

DOC: fix typos in contributing guide

---

doc/source/community/ecosystem.md

hvPlot supports GeoPandas data objects natively, extending them with interactive plotting functionality, and so should be listed in the ecosystem section. Also fixed various typos and grammar issues in that file.

DOC: Add hvPlot to ecosystem

---

geopandas/sindex.py

Compat with changes in https://github.com/pygeos/pygeos/pull/263#
ccing @brendan-ward

MAINT: use BinaryPredicate Enum for PyGEOS predicates

---

doc/source/docs/reference/geodataframe.rst
doc/source/docs/reference/geoseries.rst

DOC: Add from_wkt, from_wkb, to_wkt, to_wkb to API reference (#1889)

---

geopandas/array.py
geopandas/tests/test_pandas_methods.py

ENH: use crs.is_projected and heuristic as fallback (#1713)

---

geopandas/tests/test_extension_array.py

Skipping a new test from pandas master to make CI green again.

TST: skip pandas master fillna test

---

doc/source/getting_started/introduction.ipynb

Includes minor changes on the sentence level, punctuation, and a few typos.
I haven't seen a style guide for the Geopandas documentation, but I would recommend adapting the highlights from [Google's developer documentation style guide](https://developers.google.com/style/highlights).

DOC: revise intro to geopandas notebook

---

geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py

BUG: fix to_json/to_file when DataFrame duplicate columns (#1894)

---

ci/envs/37-latest-defaults.yaml

CI: fix arrow CI using defaults

---

doc/source/docs/user_guide/mapping.rst

Added a small section in User Guide - Mapping and plotting tools called Other map customization. This section covers the set_axis_off method. #524

DOC: set_axis_off method in User Guide

---

geopandas/array.py

Closes #1930 
This will require https://github.com/pandas-dev/pandas/pull/41312 to be merged first

BUG/TST: support parametrized string dtype

---

doc/environment.yml

This updates the doc environment to use the latest version PyGEOS (0.10).

Increment PyGEOS version for doc environment

---

geopandas/geodataframe.py
geopandas/tests/test_pandas_methods.py

BUG: preserve attrs in Dataframe.explode (#1875)

---

doc/source/gallery/plotting_with_folium.ipynb

Revision includes:
- Sentence level changes
- Typos
- Removal of redundant info
ref #1896

DOC: revise plotting with folium example

---

doc/source/gallery/polygon_plotting_with_folium.ipynb

DOC: revise plotting polygons with folium gallery example

---

geopandas/geoseries.py
geopandas/tests/test_geoseries.py

TST: fix proj4strings test for PROJ 8.0.1

---

geopandas/geodataframe.py
geopandas/tests/test_crs.py

This fixes #1372, and by association fixes #1960

BUG: GeoDataFrame CRS loss during __setitem__ 

---

.github/workflows/tests.yaml

(no idea if this will actually fix it, but just to start testing things)

CI: fix activation of the conda environments + switch to conda-incubator/setup-miniconda

---

geopandas/tests/test_crs.py

fix https://github.com/geopandas/geopandas/runs/2985725996?check_suite_focus=true#step:5:2713

TST: don't use to_crs on GeometryArray without crs

---

doc/environment.yml
doc/source/gallery/matplotlib_scalebar.ipynb

Adding a new example to the gallery which describes the usage of matplotlib-scalebar library. Resolves #1597

DOC: Example of matplotlib-scalebar library usage

---

CHANGELOG.md
doc/source/community/contributing.rst
doc/source/docs/user_guide/missing_empty.rst
doc/source/gallery/choropleths.ipynb
doc/source/gallery/geopandas_rasterio_sample.ipynb
doc/source/gallery/polygon_plotting_with_folium.ipynb
doc/source/getting_started.md
doc/source/getting_started/introduction.ipynb
geopandas/geodataframe.py
geopandas/io/tests/test_file.py
geopandas/sindex.py
geopandas/tests/test_extension_array.py
geopandas/tests/test_geodataframe.py
geopandas/tests/test_geom_methods.py
geopandas/tests/test_plotting.py
geopandas/tools/overlay.py
geopandas/tools/tests/test_clip.py
geopandas/tools/util.py

Fixed several typos using [codespell](https://github.com/codespell-project/codespell).

Fixed typos

---

doc/source/conf.py

pyepsg this package comes up twice in `intersphinx_mapping`.
See below.

DOC: Remove duplicated `intersphinx_mapping` key

---

geopandas/base.py

Clarifying the meaning of spatial predicates. xref #1574

DOC: Editing the documentation of predicates

---

geopandas/_config.py

REF: remove forgotten python 2 compat code

---

geopandas/array.py
geopandas/tests/test_extension_array.py
geopandas/tests/test_pandas_methods.py

ENH: support Series.value_counts for geometry dtype (add value_counts to GeometryArray)

---

geopandas/_compat.py
geopandas/array.py
geopandas/tests/test_geoseries.py

COMPAT: suppress numpy1.21 deprecation warnings for Shapely < 1.8

---

geopandas/tests/test_plotting.py

TST: speedup hexbin plot with bigger gridsize

---

doc/source/docs/advanced_guide.rst
doc/source/docs/user_guide/reproject_fiona.rst

DOC: Add example using Fiona to re-project

---

geopandas/_vectorized.py
geopandas/tests/test_array.py

ENH: Automatically handle hex with shapely in from_wkb

---

geopandas/io/arrow.py
geopandas/io/tests/test_arrow.py

cfr https://github.com/geopandas/dask-geopandas/pull/103#issuecomment-917465318

BUG: fix reading Parquet file without metadata (proper error message)

---

doc/source/community/contributing.rst

DOC: Add doc style guide

---

doc/environment.yml

Let's start debugging #2124 . The error comes from `nbsphinx` and happened after changes to `scheme`. Commenting out all choropleth plots within Jupyter notebooks.
Closes #2124

DOC: fix RTD builds

---

geopandas/plotting.py
geopandas/tests/test_plotting.py

BUG: path_effects incorrectly treated in plot

---

doc/source/docs/user_guide/mergingdata.rst
geopandas/tools/sjoin.py
geopandas/tools/tests/test_sjoin.py

ENH: support how="inner" in sjoin_nearest

---

geopandas/geodataframe.py
geopandas/tests/test_crs.py
geopandas/tests/test_geodataframe.py

Closes #2129 (unless there is actually an api discussion and this is somehow a feature and not a bug).

BUG: GeoDataFrame(gdf) constructor: preserve geometry column name

---

doc/source/docs/reference/geodataframe.rst
doc/source/docs/reference/geoseries.rst
doc/source/docs/user_guide/mergingdata.rst
doc/source/docs/user_guide/set_operations.rst
doc/source/gallery/overlays.ipynb
doc/source/gallery/plot_clip.ipynb
doc/source/gallery/spatial_joins.ipynb
geopandas/geodataframe.py
geopandas/geoseries.py
geopandas/tests/test_geodataframe.py
geopandas/tests/test_geoseries.py
geopandas/tools/clip.py
geopandas/tools/overlay.py
geopandas/tools/sjoin.py

Together with #1984 closes #2141 .

API: expose sjoin_nearest, clip and overlay as methods

---

CHANGELOG.md

In preparation of https://github.com/geopandas/geopandas/issues/2076

DOC/RLS: add changelog for 0.10 release

---

doc/source/docs/user_guide/geometric_manipulations.rst
geopandas/array.py
geopandas/base.py
geopandas/explore.py
geopandas/geodataframe.py
geopandas/io/tests/test_sql.py
geopandas/sindex.py
geopandas/tests/test_explore.py
geopandas/tests/test_extension_array.py
geopandas/tests/test_geoseries.py
geopandas/tests/test_pandas_methods.py
geopandas/tools/sjoin.py
geopandas/tools/tests/test_sjoin.py
versioneer.py

Hi,
This PR fixes minor typos found in docstrings.

Fix minor typos in docstrings

---

geopandas/tools/sjoin.py

Is this definition correct?
I asked something similar with movingpandas recently and wanted to check that is also true here (https://github.com/anitagraser/movingpandas/commit/38e27c3a6331ff08d75b310e8fb702e3b4af5182)

DOC: distance units in sjoin_nearest

---

benchmarks/sjoin.py
doc/source/gallery/spatial_joins.ipynb

DOC: Replaced instances of deprecated op with predicate

---

.github/workflows/tests.yaml
ci/envs/310-latest-conda-forge.yaml

Also adds a conda environment yaml file for Python 3.10

CI: Add Python 3.10 to job matrix

---

doc/source/conf.py

This updates the copyright year to read "2013-2022" in conf.py.

DOC: Update copyright year to 2022

---

.github/workflows/tests.yaml
ci/envs/310-dev.yaml
ci/envs/39-rc.yaml

And I also changed the dev environment from Python 3.8 -> 3.10

CI: test against pandas 1.4 release candidate

---

doc/source/docs/user_guide/aggregation_with_dissolve.rst
geopandas/geodataframe.py

DOC: Document full capabilities of aggfunc argument

---

geopandas/_compat.py
geopandas/tests/test_pandas_methods.py

Closes #2294
https://github.com/geopandas/geopandas/issues/2294 needs to be fixed on the pandas side (https://github.com/pandas-dev/pandas/pull/45363), but adding a test here as well in GeoPandas with the original reproducer (in pandas it's only a test with a dummy subclass)

TST: test groupby apply with function that requires GeoDataFrame attributes

---

ci/envs/310-dev.yaml

CI: ensure numpy nightly is installed in dev build

---

geopandas/array.py
geopandas/tests/test_array.py

BUG: allow single-column GeoDataFrame in GeometryArray __setitem__

---

geopandas/io/sql.py
geopandas/tools/overlay.py

Discovered two instances that could use augmented assignment to append values.

REF: use augmented assignments where feasible

---

geopandas/tests/test_op_output_types.py

Follow-up on https://github.com/geopandas/geopandas/pull/2329, updating the test (comments) to reflect the decision we made in https://github.com/geopandas/geopandas/issues/2133

TST: update comments in tests after #2329

---

geopandas/explore.py
geopandas/tests/test_explore.py

ENH: explore() flexible style function (#2350)

---

geopandas/io/sql.py
geopandas/io/tests/test_sql.py

RP to add in changes proposed in #2414 ,

BUG: support ESRI CRS in to_postgis #2414

---

geopandas/_compat.py
geopandas/tests/test_array.py

Closes https://github.com/geopandas/geopandas/issues/2435

TST: update is_closed test for shapely 1.8.2

---

geopandas/geodataframe.py
geopandas/tests/test_pandas_methods.py

picked up by codecov warning in #2280

CLN: remove pandas <1.0 check

---

geopandas/geodataframe.py
geopandas/geoseries.py
geopandas/io/file.py
geopandas/io/sql.py
geopandas/io/tests/test_file.py
geopandas/io/tests/test_sql.py
geopandas/plotting.py
geopandas/tests/test_geom_methods.py
geopandas/tests/test_plotting.py

Left this a little too late I suspect (was on my list a while ago but slipped off), but thought I'd put up anyway since getting this into a release will speed up when the final deprecations can actually happen.
xref #2263

MAINT: switch old deprecationwarnings to futurewarnings

---

ci/envs/310-dev.yaml

xref https://github.com/dask/dask/issues/9152#issuecomment-1148553047

CI: ensure we use the latest pandas dev version in the dev build

---

doc/source/docs/user_guide/io.rst

Related to:
- #2458
- https://github.com/Toblerity/Fiona/pull/889
- #1383

DOC: Add include_fields example

---

geopandas/tools/_show_versions.py

Also sorts groups of deps alphabetically to make it easier to maintain and review output in submitted bug reports.
(only substantive change is adding `pyogrio`).
Even though Fiona isn't yet truly optional, I included it in the optional deps since it is heading that way.

ENH: add pyogrio to show_versions

---

CHANGELOG.md
geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py
geopandas/tests/test_op_output_types.py
geopandas/tests/test_pandas_methods.py

Closes https://github.com/geopandas/geopandas/issues/2486

REGR: fix recursion error in GeoDataFrame constructor with MultiIndex

---

CHANGELOG.md
geopandas/io/file.py
geopandas/io/tests/test_file.py

BUG: fix mixed datetime regression

---

ci/envs/310-dev.yaml

https://github.com/Toblerity/Fiona/issues/1053
I am checking to see if the CRS changes break anything.

CI: add fiona latest to test runs

---

doc/source/conf.py
geopandas/io/file.py

This adds links to the fiona documentation with intersphinx.

DOC: Add direct references to fiona docs in read_file

---

ci/envs/310-dev.yaml
geopandas/io/file.py

Related to #2458
Cherry-picked in #2456 to be sure it works as expected. Can remove later.

BUG: Handle Fiona 1.9 CRS deprecation

---

ci/envs/38-latest-defaults.yaml

CI: pin to older numpy for compat with older shapely in defaults channel

---

geopandas/explore.py
geopandas/plotting.py
geopandas/tests/test_explore.py
geopandas/tests/test_plotting.py

Addresses the issue of #2416  
This is my first contributing oss activity.  
So if you find something wrong, please point it out.
The main changes are as follows
- Using pandas API instead of numpy API
- Adding conditions in plotting as well as explore  
The reason for the above changes is that using pandas.api.types can be better way to catch more conditions, as stated in #2416.

ENH: better detection of categorical columns in plot and explore

---

doc/environment.yml

Closes #2561
Removing the pin as the issue has been fixed.

DOC: remove pydata-sphinx-theme pin

---

CHANGELOG.md
geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py

BUG: Fix inconsistency with "geometry" in frame but not active geometry column

---

ci/envs/310-latest-conda-forge.yaml
ci/envs/38-latest-conda-forge.yaml
ci/envs/39-latest-conda-forge.yaml
ci/envs/39-no-optional-deps.yaml
ci/envs/39-pd12-conda-forge.yaml

xref https://github.com/conda-forge/tiledb-feedstock/issues/170, https://github.com/conda-forge/gdal-feedstock/issues/654

CI: temporary fix for GDAL/tiledb conda-forge issues

---

CHANGELOG.md
geopandas/tools/clip.py
geopandas/tools/tests/test_clip.py

BUG: Fix handling of empty shapely geometries in clip()

---

doc/source/community/contributing.rst

See https://github.com/geopandas/geopandas/issues/2615#issuecomment-1292408029
Agreed to update the way to create a develop environment using `pip install -e .`

DOC: add pip install -e . to contributing.rst

---

setup.py

See https://github.com/geopandas/geopandas/issues/2603#issuecomment-1295080298

Remove shapely <2 pin in install requirements

---

.pre-commit-config.yaml
geopandas/base.py

In my env pre-commit started hanging.  Have not found further references other than this:
https://www.reddit.com/r/Python/comments/yvfww8/flake8_took_down_the_gitlab_repository_in_favor/

CI: flake8 moved to github

---

CHANGELOG.md
geopandas/io/arrow.py
geopandas/io/tests/test_arrow.py

BUG: avoid invalid bbox for empty GeoDataFrame in to_parquet

---

ci/envs/310-dev.yaml
ci/envs/310-latest-conda-forge.yaml
ci/envs/311-latest-conda-forge.yaml
ci/envs/39-latest-conda-forge.yaml
ci/envs/39-pd13-conda-forge.yaml

Probably also need to pin deps until pandas is compatible?

CI: pin sqlalchemy <2 for now

---

CHANGELOG.md
geopandas/array.py
geopandas/base.py
geopandas/tests/test_extension_array.py
geopandas/tests/test_pandas_methods.py
geopandas/tools/hilbert_curve.py
geopandas/tools/tests/test_hilbert_curve.py

Follow-up on https://github.com/geopandas/geopandas/pull/2297 to make use of the Hilbert distance when sorting GeoSeries/GeoDataFrame.
Closes #2070

ENH: support sorting geometry columns based on Hilbert distance

---

doc/source/docs/reference/geoseries.rst

DOC: Add GeoSeries.make_valid to API doc

---

doc/source/gallery/cartopy_convert.ipynb
doc/source/gallery/create_geopandas_from_pandas.ipynb
doc/source/gallery/matplotlib_scalebar.ipynb
doc/source/gallery/overlays.ipynb
doc/source/gallery/plot_clip.ipynb
doc/source/gallery/plotting_basemap_background.ipynb
doc/source/gallery/plotting_with_folium.ipynb
doc/source/gallery/plotting_with_geoplot.ipynb
doc/source/gallery/polygon_plotting_with_folium.ipynb
doc/source/gallery/spatial_joins.ipynb

DOC: remove usage of datasets from examples

---

geopandas/base.py
geopandas/geodataframe.py
geopandas/plotting.py
geopandas/tools/hilbert_curve.py
geopandas/tools/overlay.py
geopandas/tools/sjoin.py

Sphinx warns about this nowadays.

DOC: fix some sphinx warnings (underlines)

---

geopandas/_compat.py

Trying to make it a bit more explicit about when and what will change.
xref https://github.com/geopandas/geopandas/issues/2691

Update warning on import when both Shapely 2 and PyGEOS are installed

---

CHANGELOG.md
benchmarks/sindex.py
doc/source/docs/reference/sindex.rst
geopandas/base.py
geopandas/sindex.py
geopandas/tests/test_sindex.py
geopandas/tools/overlay.py
geopandas/tools/sjoin.py

Closes https://github.com/geopandas/geopandas/issues/2823

API: deprecate sindex.query_bulk and move functionality to sindex.query (matching shapely)

---

doc/source/gallery/create_geopandas_from_pandas.ipynb

Fixes #2838 
This adds an explicit CRS value to an example data frame to make it explicit what format the data is in and make the code more compatible with other libraries, eg. contextily.

DOC: Update to example gallery

---

geopandas/io/file.py

Super small fix of error message of `_to_file` method.

CLN: Fix ValueError message in _to_file

---

CHANGELOG.md

I merged #2886 without a changelog note, so adding it here.

DOC: add missing changelog for #2886

---

ci/envs/311-latest-conda-forge.yaml
geopandas/_compat.py
geopandas/io/tests/test_sql.py

See https://github.com/geopandas/geopandas/pull/2849#issuecomment-1537099850

TST: skip postgis duplicate column test for pandas 2.0.x

---

CHANGELOG.md

xref https://github.com/geopandas/geopandas/issues/2692

RLS/DOC: update to changelog for 0.13

---

CHANGELOG.md
geopandas/io/file.py
geopandas/io/tests/test_file.py

REGR: fix read_file with file:// URIs

---

geopandas/tests/test_geodataframe.py

TST: Fixed conditions on test_sjoin in test_geodataframe, so that test is not unnecessarily skipped

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
doc/source/docs/user_guide/geometric_manipulations.rst
geopandas/_vectorized.py
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

Implements the shapely offset_curve method as part of #2010

ENH: add offset_curve as GeoSeries method

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
geopandas/_vectorized.py
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

implements hausdorff distance, from #2010

ENH: add hausdorff distance method

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
doc/source/docs/user_guide/geometric_manipulations.rst
geopandas/_vectorized.py
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

Implements the shapely segmentize method as part of https://github.com/geopandas/geopandas/issues/2010

ENH: add segmentize as a GeoSeries method

---

geopandas/geoseries.py

We didn't merge main in before merging #2027 which made ruff unhappy on main.

MAINT: fix linting issue caused by a merge of #2027

---

CHANGELOG.md
geopandas/geodataframe.py
geopandas/tests/test_pandas_methods.py

BUG: fix apply axis=1 edge case for nested data

---

geopandas/geodataframe.py

Description: This pull request updates the docstring for the dissolve function in the geopandas package to accurately document the options for the by parameter.
Changes Made: Modified the docstring to indicate that the by parameter can accept either a string or a list-like object.
Please review and merge this pull request. Thank you for your attention to this matter.

DOC: Update dissolve docstring to document options for the "by" parameter

---

geopandas/io/tests/test_file.py

TST: compat with tzdata (2023c-8)

---

CHANGELOG.md
doc/source/docs/reference/sindex.rst
doc/source/docs/user_guide/pygeos_to_shapely.rst
doc/source/getting_started/install.rst
geopandas/_compat.py

Switch the default geometry engine to Shapely

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
geopandas/_vectorized.py
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

ENH: expose reverse

---

doc/source/docs/user_guide/io.rst
doc/source/getting_started/install.rst
geopandas/_config.py
geopandas/io/file.py
geopandas/io/tests/test_file.py
geopandas/tests/test_config.py

Closes https://github.com/geopandas/geopandas/issues/2995

DOC: update io user guide to mention pyogrio

---

geopandas/array.py
geopandas/explore.py
geopandas/geoseries.py
geopandas/plotting.py
geopandas/tests/test_pandas_methods.py

Few commits broken off from https://github.com/geopandas/geopandas/pull/2966 that have the actual code changes that are important to have in the release

COMPAT: fix warnings for latest pandas

---

doc/source/docs/user_guide/interactive_mapping.ipynb

I didn't realise this is not explore code that would pull data from xyzservices...

DOC: use included tilelayer in explore guide

---

doc/source/docs/user_guide/data_structures.rst

xref https://github.com/geopandas/geopandas/discussions/3021

DOC: minor grammar fix

---

doc/source/gallery/plotting_basemap_background.ipynb

Addressing https://github.com/geopandas/geopandas/issues/3065

Remove Stamen references from  plotting_basemap_background.ipynb

---

doc/source/docs/user_guide/io.rst

DOC: add note for to_file method when saving multiple GeoSeries

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

ENH: add force_2d and force_3d

---

geopandas/geodataframe.py
geopandas/io/sql.py
geopandas/plotting.py

Removing some dead code paths which are no longer executed / required. This started looking at the indirect coverage changes from #3001, but I also had a quick scan at coverage a bit more widely to pick up a few places with redundant lines.

MAINT: Coverage related cleanups

---

geopandas/io/tests/test_file.py
geopandas/io/tests/test_file_geom_types_drivers.py
geopandas/tests/test_array.py
geopandas/tests/test_crs.py
geopandas/tests/test_geom_methods.py
geopandas/tests/test_plotting.py

Follow up on https://github.com/geopandas/geopandas/pull/2966

MAINT: reduce warnings in the tests

---

geopandas/io/tests/test_file.py

TST: Add test on reading None values

---

geopandas/tests/test_geom_methods.py
geopandas/tests/test_pandas_methods.py
geopandas/tools/tests/test_sjoin.py

Closes https://github.com/geopandas/geopandas/issues/3143

TST/CI: skip some tests for older GEOS

---

geopandas/io/file.py

Closes #3147
I want to point out that this is not a bug on our side but knowing Esri, this is the easiest way how to fix the issue geopandas users face when working within ArcPro environment. There's probably no way to test this though.
@remi-braun can you test this?

COMPAT: fix compatibility with Esri-shipped GDAL

---

doc/source/index.rst

I just made some small cosmetic additions to the landing page. 
1. remove the secondary sidebar as there are no real sections here, simply titles
2. remove the indices that are generated by sphinx-quickstart and are no longer supported by modern sphinx-build.

DOC: improve landing page

---

readthedocs.yml

For some reasons, RTD does not pick tags and uses 0+untagged. An attempt to fix that though it is unclear to me why it happens.

RTD: update readthedocs setup

---

CHANGELOG.md
geopandas/array.py
geopandas/geodataframe.py
geopandas/geoseries.py
geopandas/io/file.py
geopandas/io/sql.py
geopandas/io/tests/test_file.py
geopandas/io/tests/test_sql.py
geopandas/sindex.py
geopandas/tests/test_array.py
geopandas/tests/test_geom_methods.py
geopandas/tests/test_sindex.py
geopandas/tools/sjoin.py
geopandas/tools/tests/test_sjoin.py

xref #2263. This definitely needs a changelog, haven't done that yet.

MAINT: Expire deprecations

---

.github/workflows/tests.yaml

Closes https://github.com/geopandas/geopandas/issues/3169

TST/CI: decrease verbosity for xfails in pytest 8+ output

---

doc/source/conf.py

Updates the copyright year in `conf.py` to "2013-2024".

DOC: remove copyright year

---

ci/envs/310-pd20-conda-forge.yaml
ci/envs/311-dev.yaml

See https://github.com/geopandas/geopandas/issues/3207

TEMP pin fiona to 1.9 in dev build

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

ENH: `set_precision` and `get_precision` methods

---

geopandas/array.py

This should fix the one failing test for `astype` in the dev build

COMPAT: adjust for new `copy`  behaviour of numpy.array / __array__

---

pyproject.toml

Closes https://github.com/geopandas/geopandas/issues/3258

BLD/RLS: add numpy explicitly as install dependency

---

CHANGELOG.md
geopandas/base.py
geopandas/tests/test_geom_methods.py

API: raise when using unaligned Series as a method argument

---

CHANGELOG.md
ci/envs/311-dev.yaml
geopandas/_compat.py
geopandas/array.py
geopandas/base.py
geopandas/geodataframe.py
geopandas/geoseries.py
geopandas/io/file.py
geopandas/io/tests/test_file.py
geopandas/io/tests/test_file_geom_types_drivers.py
geopandas/io/util.py
geopandas/tests/test_array.py
geopandas/tests/test_crs.py
geopandas/tests/test_dissolve.py
geopandas/tests/test_extension_array.py
geopandas/tests/test_geodataframe.py
geopandas/tests/test_geom_methods.py
geopandas/tests/test_geoseries.py
geopandas/tests/test_overlay.py
geopandas/tests/test_pandas_methods.py
geopandas/tests/test_plotting.py
geopandas/tools/overlay.py
geopandas/tools/tests/test_random.py
geopandas/tools/tests/test_sjoin.py
pyproject.toml
readthedocs.yml

Initial set of backports for 0.14.4
- https://github.com/geopandas/geopandas/pull/3183
- https://github.com/geopandas/geopandas/pull/3184
- https://github.com/geopandas/geopandas/pull/3191
- https://github.com/geopandas/geopandas/pull/3180
- https://github.com/geopandas/geopandas/pull/3222
- https://github.com/geopandas/geopandas/pull/3209
- https://github.com/geopandas/geopandas/pull/3232
- https://github.com/geopandas/geopandas/pull/3042
- https://github.com/geopandas/geopandas/pull/3235
- https://github.com/geopandas/geopandas/pull/3234
- https://github.com/geopandas/geopandas/pull/2966
- https://github.com/geopandas/geopandas/pull/3126
- https://github.com/geopandas/geopandas/pull/3264
- https://github.com/geopandas/geopandas/pull/3254

0.14.4 backports

---

CHANGELOG.md
geopandas/_config.py

Related to #3037, but doesn't close it (will be closed when this is removed completely)

DEPR: deprecation warning for use_pygeos

---

geopandas/io/tests/test_file.py

Follow-up on https://github.com/geopandas/geopandas/pull/3286, this now also shows up with fiona

TST: GDAL 3.9 compat for boolean array in shp for fiona

---

geopandas/geodataframe.py
geopandas/geoseries.py

Follow-up on https://github.com/geopandas/geopandas/pull/3088#discussion_r1622365523

Fix deprecation message in setting crs directly

---

geopandas/io/file.py
geopandas/io/tests/test_file.py

TST: Add test covering passing geojson string to read file

---

CHANGELOG.md
geopandas/base.py
geopandas/tests/test_geom_methods.py

REGR: fix regression preventing a Series as an arg for geo methods

---

geopandas/base.py

Fixes failures seen in https://github.com/geopandas/geopandas/actions/runs/9848957022/job/27201199481.

DOC: update docstrings to match GEOS 3.12.2

---

CHANGELOG.md
geopandas/geodataframe.py
geopandas/tests/test_pandas_methods.py

BUG: support named aggregations over a geometry column in `GroupBy.agg`

---

doc/source/conf.py

Adapt our conf.py ahead of https://about.readthedocs.com/blog/2024/07/addons-by-default/. Got an email notification from RTD about this.

DOC: update config for RTD upcoming changes

---

CHANGELOG.md
geopandas/geoseries.py
geopandas/tests/test_geoseries.py

BUG: Fix constructing geoseries from geometrydtype pd.Series

---

geopandas/explore.py

Closes #2187 
Added a check for folium version, raise an error if it's less than 0.12.0. Tested locally with different folium versions - it works as expected.

ENH: check for minimum version of folium

---

geopandas/geodataframe.py

There was a note that this was only pandas <1.4 compat, testing if that's still true

CLN: Remove astype overload

---

geopandas/tools/clip.py

Closes #3461
Changes include:
1. adding a docstring to the _mask_is_list_like_rectangle function
2. ensuring consistent variable naming across _clip_gdf_with_mask and clip functions by renaming the "mask_is_list_like" variable to "clipping_by_rectangle"
I created issue GH3461 to explain the benefits of these changes in more detail. While this file is already in really good shape, I believe these changes will bring it to PEP 8 standards and make it slightly more readable.

CLN: GH3461 Implements minor readability changes to clip.py.

---

geopandas/tests/test_explore.py

Update to changes in folium. There should be not change of behaviour.

TST: test compatibility with latest folium

---

geopandas/base.py

DOC: add clarification to concave_hull behaviour

---

CHANGELOG.md
geopandas/geodataframe.py
geopandas/tests/test_overlay.py
geopandas/tools/overlay.py

Remark:
- The speedup has as side-effect that e.g. int64 columns with NAN values in some situations will retain the original int64 dtype instead of switching to float64
Solves #3295

ENH: improve performance of overlay/identity

---

geopandas/base.py

Sync improvement of documentation in shapely: https://github.com/shapely/shapely/pull/2256/files

DOC: improve documentation of snap

---

CHANGELOG.md
geopandas/_compat.py
geopandas/array.py
geopandas/base.py
geopandas/geodataframe.py
geopandas/tests/test_array.py
geopandas/tests/test_dissolve.py
geopandas/tests/test_geom_methods.py

Mimics the way we exposed `coverage_union`.

ENH: expose disjoint_subset union in union_all and dissolve

---

geopandas/base.py

Updating expected WKT caused by change of GEOS version. The result has been verified to be correct.

DOC: update expected offset curve

---

geopandas/array.py
geopandas/geoseries.py

Add on_invalid="fix" option to the documentation of `from_wkb` and `from_wkt`.
reference https://github.com/shapely/shapely/pull/2094
reference https://github.com/geopandas/pyogrio/pull/532

DOC: doc from_wkb and from_wkt with on_invalid=fix

---

doc/source/docs/user_guide/pygeos_to_shapely.rst

Get the correct relative path to Installation Instructions.

DOC: Get the correct relative path to Installation Instructions

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

ENH: add minimum_clearance_line

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

ENH: add GeoSeries.simplify_coverage for topological simplification

---

doc/source/gallery/choropleths.ipynb

Update the links in the Choropleth Classification example.
The correct PySAL link is: https://pysal.org/
And the Columbus dataset link is:
https://github.com/pysal/pysal_examples/tree/master/pysal_examples/columbus

DOC: Update the links in the Choropleth Classification example

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geom_methods.py

ENH: add orient_polygons

---

geopandas/io/arrow.py
geopandas/io/tests/test_arrow.py

BUG: fix error message reading invalid geoparquet

---

CHANGELOG.md
doc/source/docs/reference/geoseries.rst
geopandas/array.py
geopandas/base.py
geopandas/tests/test_geoseries.py

ENH: add geom_equals_identical

---

doc/source/gallery/plot_clip.ipynb

DOC: Correct a typo: chicago -> Chicago

DOC: Correct a typo: chicago -> Chicago

---

doc/source/gallery/plotting_basemap_background.ipynb

Update link to Web Mercator wiki:
https://en.wikipedia.org/wiki/Web_Mercator_projection

DOC Update link to Web Mercator wiki

---

CHANGELOG.md

Just reordering and moving some notes to a correct category.

RSL: prepare changelog for 1.1.0 release

---

CHANGELOG.md
geopandas/geodataframe.py
geopandas/tests/test_geodataframe.py

REGR: fix GeoDataFrame constructor when np.nan given as only geometry

---

geopandas/array.py
geopandas/base.py
geopandas/geodataframe.py

DOC: fix crs docstrings

---

doc/source/getting_started/install.rst

Broken link to folium in getting started page fixed
Fixes #3612

Fixed broken link

---

geopandas/geoseries.py

Noticed it was missing on the website.

DOC: Add example for `to_wkb` docstring

---

doc/source/conf.py
doc/source/gallery/cartopy_convert.ipynb

The Cartopy docs have a new home.

DOC: update Cartopy url

---

CHANGELOG.md
geopandas/io/arrow.py
geopandas/io/tests/test_arrow.py

Fixes https://github.com/geopandas/geopandas/issues/3639

BUG: fix read_parquet to_pandas_kwargs with complex dtypes

---

geopandas/tests/test_extension_array.py

https://github.com/pandas-dev/pandas/pull/62417 breaks our inherited EA tests, pretty straightforward to fix.

TST: more pandas compat test updates
