geopandas/tools/sjoin.py, tests/test_sjoin.py
This PR increases the performance of geopandas' spatial join function (sjoin.py). The work is based largely on @perrygeo's original work, but introduces a number of optimizations that (a) improve the speed of the join, and (b) reduce memory consumption, allowing the function to handle larger datasets.
Performance increases are primarily achieved by vectorizing operations that were previously handled through iteration (e.g. querying the Rtree index, checking binary predicates). Performance increases are also obtained by generating 'prepared geometry' instances using the `shapely.prepared` package.
Sample speed tests are shown below. The original sjoin function is indicated by `tools.sjoin` while the new sjoin function is indicated by `fast_sjoin`. Join speed is increased by about an order …
=> ENH: Optimized spatial join

geopandas/geodataframe.py, geopandas/io/file.py, tests/test_geodataframe.py
Add a schema argument in GeoDataFrame.to_file to pass in to Fiona.
Allows for finer control over how the data gets written.
Refactor to_file into geopandas.io.file.
Addresses #177
=> ENH: Allow schema input in to_file()

.travis.yml
The test versions of pandas used on Travis were out of date. This updates `travis.yml` to use 0.15.2 and 0.16.0, the latest 2 major releases, as well as master.
=> Update pandas versions on Travis CI

geopandas/tools/sjoin.py, tests/test_sjoin.py
Fix for second issue mentioned in #190.
=> Fix bug in sjoin index

geopandas/base.py
Small cleanup to address my [comment](https://github.com/geopandas/geopandas/pull/193#discussion_r29402616) on #193.
=> Always use kwargs when calling _series_unary_op()

geopandas/geodataframe.py, tests/test_geodataframe.py
Fixes #199 to correctly serialize/deserialize `crs` attribute. Not implemented for `GeoSeries` here, only for `GeoDataFrame`. A cleaner fix will be to do this upstream, as submitted in pydata/pandas#10557.
=> Serialize metadata

geopandas/plotting.py
I added this because descartes does not accept polygons with a z coordinate. I could imagine wanting to do something a bit more sophisticated when the z coordinate contains interesting information, but in the meantime, this is nicer behavior than raising an exception.
I would not ordinarily have put the shapely import inside the if statement, but from the descartes import within the function, I guessed there was some desire to limit global imports.
=> Added check for z dimension in plot_polygon; if yes, flatten before plot.

geopandas/plotting.py, tests/test_plotting.py
Based on a SO question, I added the ability to create a legend for choropleth figures based on PySAL schemes (see my answer: http://stackoverflow.com/questions/31755886/choropleth-map-from-geopandas-geodatafame?noredirect=1#comment51555293_31755886 and the notebook: http://nbviewer.ipython.org/gist/jorisvandenbossche/d4e6efedfa1e4e91ab65)
This lets you obtain something like:
=> ENH/VIS: add legend for choropleth plots

.travis.yml
Inspired by the speedups achieved [in rasterio](https://github.com/mapbox/rasterio/pull/474), these changes run the Travis builds on the new container-based infrastructure and build wheels for the dependencies. The wheels are cached so that subsequent builds will be much faster.
With the addition of [libspatialindex-dev]( https://github.com/travis-ci/apt-package-whitelist/issues/1100) to the travis apt package whitelist, all of the system deps are available in the containers.
Pandas master still requires a build but the pandas stable releases use pypi and build cacheable wheels.
After the initial build, I'm seeing travis runs completing 2-4x faster. 
Resolves #125
=> TST: speed up travis builds with containers and wheel caching

tests/test_sindex.py
When Shapely geometries become unhashable, this behavior is no longer
supported.
See #221.
=> Remove test_merge_geo

geopandas/plotting.py, tests/test_plotting.py
This PR let's you specify a colormap for `Point` plots.
Some questions:
- this changes the default colors: now it are the colors from the default matplotlib color cycle. Is this a problem? (I rather think this makes it more consistent with Linestrings/Polygons)
- the docstring of `plot_dataframe` says that the default for `colormap` is 'Set1', but the actual signature uses `None` -> therefore the default matplotlib colormap 'jet' is used
- how should this be tested? Adding an image to compare with? Or I can also just check the actual color on the `ax` object
=> ENH: add plot points with colormap

geopandas/plotting.py, tests/test_plotting.py
Add the ability to specify `color` in `plot()` to plot all points/lines/polygons in a single color.
You can see it at work in this notebook: http://nbviewer.ipython.org/gist/jorisvandenbossche/47e6d587eec39a8357f0#
=> ENH: plot with single colors

geopandas/plotting.py, tests/test_plotting.py
Previously, a value of min=0 was interpreted as False and ignored.
I added a new test case that failed before and passes now.
I also removed some duplicated entries in the docstring.
=> BUG: 0 is a valid value for vmin, vmax

setup.py
Let's get the RTD build working again.
This skips installing requirements when installing on readthedocs. Otherwise it fails on the binary libraries. I did try mocking out the libraries instead of skipping them, as listed [here](http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules), but that didn't work for me (I must be doing something wrong).
Link for the build associated with this branch: http://geopandas.readthedocs.org/en/doc-readthedocs-requirements
=> Revive readthedocs build

geopandas/plotting.py, tests/test_plotting.py
This PR fixes the problem mentioned in Issue #204 where one cannot pass a fixed color to `plot_series` or `plot_dataframe`. Before the PR, the following line:
```python
df.plot(facecolor='white')
```
Returns the error that `facecolor` is referenced twice. This is solved with the patch.
In addition, the patch also allows related problems also mentioned in the issue, where arguments for `plot_linestring` and `plot_point` are not passed properly.
After the patch, all the tests continue passing locally.
=> ENH: Fix facecolor conflict

geopandas/plotting.py, tests/test_plotting.py
By passing through the `color_kwds`, you can eg also adapt the markersize for point plots, or the linestyle for line plots. 
Added a test for those two example cases.
=> Plotting: pass kwargs also for lines and points

.travis.yml
This is not the most beautiful way to change the Travis builds, but it is an attempt at resolving issues raised in PR #243 and Issue #271.  
This results in 11 test and removes the test combinations aspect of the matrix.  Eight (8) tests focused on testing Python 2.7 and 3.5 with many versions of Pandas.
I did not attempt to add multiple versions of matplotlib to the travis tests.  (I've made a similar travis test "suite" for basemap.) I'm not trying to avoid doing that, but I am trying to make sure that this is acceptable before spending too much time on it.
=> Travis: "Matrix" Changes

tests/test_plotting.py
This patch calls setUpClass and tearDownClass once. (setUp and tearDown were called once for each test fixture [3-4 times]).  This is very minor change.
=> unittest: call mkdir & rmtree once for the class

.requirements-2.6.txt, .travis.yml, requirements.txt
matplotlib testing was proposed in PR #243.   Add Pandas 0.18.0 to testing.  Have one requirements.txt file for all versions (remove .requirements-2.6.txt).  Allow MATPLOTLIB=master tests
to fail (which a few of the tests currently fail).
=> Travis:Test different versions of matplotlib

geopandas/geodataframe.py, geopandas/geoseries.py, tests/test_geoseries.py
Right now, the CRS tools won't accept a proj4 string -- it requires they be broken out into a dictionary. But behind the scenes is the pyproj library which can parse proj4 strings. This just adjusts the call to pyproj slightly so `to_crs()` can take proj4 strings in addition to full dictionaries. Dictionaries still work!
=> make crs more flexible

setup.cfg
... has the potential to make geopandas slightly easier to install.  Since geopandas itself it pure python, this should be an extra step during release: `python setup.py sdist bdist_wheel upload`
See: http://pythonwheels.com/
=> Universal Python Wheel

doc/environment.yml, doc/source/data_structures.rst, doc/source/mapping.rst, doc/source/projections.rst, readthedocs.yml, requirements_rtd.txt
Starting with #283 PR from @nickeubank, the docs require a usable installed version of geopandas, because the examples are being built at doc build runtime. Installing these dependencies on read the docs is not done at the moment, and was also somewhat problematic, but they recently added conda support: http://docs.readthedocs.org/en/latest/conda.html
This PR adds therefore a readthedocs.yml config file and a conda environment file for installing all doc dependencies on read the docs using conda. 
This is currently working: http://readthedocs.org/projects/geopandas/builds/3894807/, only the docs are not yet fully correct because the example data used in the docs are not available in the installed version (but will open a separate issue for that): …
=> DOC: add readthedocs yaml config file + use conda for doc deps

geopandas/geodataframe.py, geopandas/geoseries.py
Closes #264
Doc strings for plotting were not accessible to the user. This moves them up to associate them with the appropriate methods.
=> moved docs for plotting to more accessible location

geopandas/tests/test_overlay.py, geopandas/tools/overlay.py
Closes #305 (by adding informative error for when overlay passed a GeoSeries) and #306 (overlay fixed for geometry columns not named geometry).
=> Bug fixes for overlay

doc/source/install.rst
Updated the version to the minimum one we are using in the tests (older version we cannot (and do not want) guarantee I think since we are not testing those).
(also removed a notion of the `--pre` tag, as I don't think development versions are uploaded to PyPI
=> DOC: update minimum pandas version in install docs

geopandas/geodataframe.py, geopandas/tests/test_merge.py
Closes #247 
TODO for this PR:
TODO for later PR:
- I now use the metadata of the left/first object, but in the right/other objects can also be GeoDataFrames/Series, with possibly conflicting metadata
- Eg when concatting with `axis=0`, I think we should check that the metadata are equal and otherwise raise (on different crs or different geometry column) -> https://github.com/geopandas/geopandas/issues/326
=> BUG: preserve metadata on merge/concat (#247, #320)

doc/environment.yml
Needed for new mapping and merging docs (currently the build was failing on readthedocs)
=> DOC: add rtree and pysal to doc requirements

doc/source/aggregation_with_dissolve.rst, doc/source/geometric_manipulations.rst, doc/source/index.rst, doc/source/mergingdata.rst, doc/source/set_operations.rst
Closes  #281?
- Updates tool import paths -- `sjoin` and `overlay` now in root path. 
- Adds dissolve docs
=> final doc updates

geopandas/tests/test_plotting.py
Related to https://github.com/geopandas/geopandas/issues/278. Deliberatly skipping the tests until #278 is resolved has the advantage that if other tests start failing in a PR for pandas/matplotlib master, this gets noticed (because now the tests fail anyway).
=> TST: explicitly skip tests that fail with master version of matplotlib

doc/source/set_operations.rst
I added examples of the different overlay 'how' methods using the same dummy/simple example GeoDataFrame. 
Using a simple example makes it easier to see what the different methods do, I think, and it also helps to reduce the time to build the docs.
Similar output can be seen at http://nbviewer.ipython.org/d993c25e0ea8111778599990fb2da2bd
=> DOC: add overview of overlay methods

readthedocs.yml
This should solve #333 for now. 
I don't think the pdf and epub versions of the documentation are really essential.
=> DOC: disable other formats on readthedocs (for faster build)

geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
This changes the behavior of `set_geometry()` in the case of a geometry column not named `geometry`, but I believe the previous behavior was incorrect. Previously, passing in a column to `set_geometry()` would always create a column called `geometry`, and leave the existing geometry column if it had a different name. This change will honor the geometry column name, and overwrite the existing one (as it already did in the case of a column actually called `geometry`).
Fix #339.
=> Use _geometry_column_name in set_geometry()

.travis.yml
Tests were using 0.18.0, while 0.18.1 is the latest release.
=> TST: test with latest 0.18.x pandas release

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
This is a fix for issue https://github.com/geopandas/geopandas/issues/251 
The problem is an obscure error when performing an sjoin where the result of sjoin has no overlapping geometries. Now instead of an error it returns an empty GeoDataFrame on inner join as well as left_df and right_df when performing respectively left and right joins.
The only pieces of code are the added if, else part with handling of empty results.
=> Fix for issue 251 

setup.cfg, setup.py
xref https://github.com/geopandas/geopandas/issues/361
Seems I forgot the `cmdclass` in setup.py 
Tested it, and now it generates the correct version in the packaged source.
=> Fix usage of versioneer in setup.py

geopandas/tests/util.py
I was able to find what appears to be the updated and only available zip file that is consistent with what the nybb_16a.zip file contained.
Unfortunately, the number of fields in the shapefiles appear to be different, and the hardcoded shapes that are used for verifying geodataframe shapes are no longer valid.
For example, the test below fails because the number of fields in the shapefile differs from the hardcoded reference tuple:
```
FAIL: test_intersection (geopandas.tests.test_overlay.TestDataFrame)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/nickg/geopandas/geopandas/tests/test_overlay.py", line 62, in test_intersection
self.assertEquals(df.shape, (68, 7))
AssertionError: Tuples differ: (67, 7) != (68, 7)
``` …
=> BUG: nybb zip file no longer exists.

geopandas/io/file.py, geopandas/io/tests/test_io.py
Closes #371
This is a quick fix that ensures filtered results from Fiona's `filter` function are used to populate the `GeoDataFrame`. Previously, the entire selection of features were returned whether or not the `bbox` keyword argument was passed in while using `geopandas.read_file`.
=> BUG: fixed fiona filter results where bbox is not None

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
The geometry columns were hardcoded in the sjoin operation, meaning if a user renamed their geometry column, the function would fail. Or worse yet, if a second geometry column were generated with a different name and set as the default geometry column, the sjoin operation would still run on the column named "geometry," unbeknownst to the user.
This PR ensures the actual default geometry column is called during sjoin operations.
=> Changes hard-coded reference to geometry column in sjoin operation

geopandas/io/file.py, geopandas/io/tests/test_io.py
Closes #378 
Use ordered dict from meta["schema"]["properties"] with column order, as suggested by @jorisvandenbossche.
I added a couple of lines to `TestIO.test_read_file` verifying that the column order matches. In doing so, I needed to convert the fiona column names to lower case to match a conversion happening to the geodataframe. I see that `validate_boro_df` has the columns in lower case, presumably motivating that lower case transformation in `test_read_file`, but it wasn't clear to me why it was necessary in `validate_boro_df`.
=> ENH: preserve column order in read_file (#378).

doc/source/contributing.rst, geopandas/tests/test_geocode.py
Alternative for #347 from @perrygeo. 
Since travis is already using pytest, I just removed the remaining usage of nose.
Closes #347
=> TST: switch remaining nose to pytest

appveyor.yml, geopandas/tests/test_sindex.py
=> TST: add appveyor windows testing

appveyor.yml
Our tests are still failing for the newest matplotlib 2.0 due to the style changes, so until that is fixed, pin matplotlib to 1.5 on appveyor.
=> TST: fix matplotlib to 1.5.3 on appveyor

.travis.yml, requirements.txt
Alternative to #406, and also a simplification of the travis.yml file: remove pip wheel commands (for the more recent versions, wheels are already available on PyPI, for the other ones pip nowadays automatically builds wheels the first time and then use pip cache).
=> TST: remove explicit building wheels - wheels are now available on PyPI - use pip cache

.travis.yml, geopandas/tests/test_dissolve.py, geopandas/tests/util.py
Closes https://github.com/geopandas/geopandas/issues/407
Drop support (at least testing) for python 2.6 and 3.3, pandas 0.15 (and added 019.2 in test matrix) and matplotlib < 1.4
Also changed the main test matrix to use python 3.6 instead of 3.5
=> Drop python 2.6/3.3, pandas 0.15, matplotlib 1.2/1.3

geopandas/geodataframe.py
#390 asks that exporting an ID when exporting to GeoJSON be made an optional thing, per the specification. However, @sgillies (who is actually on the spec committee) stepped in and pointed out that this was due to a lack of consensus regarding an error correction in the previous spec and that actually having a meaningful ID is part of best practices.
In light of that I'm opposed to making exporting an ID optional, and in favor of making the ID exported meaningful. This PR is a tiny change that does the latter by replacing `str(i)` (the column number) with `str(row.name)` (the column index entry) in the export.
=> ENH: use row.name for id when exporting to GeoJSON

geopandas/base.py
Maybe since `cascaded_union` is deprecated, this does not really
matter, but `gdf.unary_union` works, while `gdf.cascaded_union`
did not, and I thought as long as both are supported they should
behave the same way.
BTW, I'm seeing three test failures on plotting, but they are evidently
unrelated to this pull request. I'm guessing it is due to having
upgraded to matplotlib 2.0.0, but I'll look into it a bit more.
=> Change cascaded_union property behavior

.gitignore
`pytest` creates a `.cache/` file when it runs, so let's add that to the `.gitignore` to avoid having to delete it when we want to commit (`pandas` already has this).
=> Add cache skip

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
Fixes #352.
`rtree` allows fewer things in its index than `pandas` does, causing errors when you use a non-int index and try to do an `sjoin` with it. This PR attempts to fix this issue by stashing the actual index in favor of an `int` index and only reattaching The Real Thing at the end of the operation.
@jorisvandenbossche wanted to get your feedback on this...what do you think of this approach?
=> ENH: Enable non-integer-indexed GeoDataFrame sjoin operations

geopandas/tests/util.py
xref https://github.com/pandas-dev/pandas/pull/10458 and https://github.com/pandas-dev/pandas/pull/15652
=> CLN/TST: remove usage of assert_isinstance from pandas (deprecated/removed)

geopandas/io/file.py, geopandas/io/tests/test_io.py, geopandas/tests/test_geodataframe.py, geopandas/tests/util.py
Per @jorisvandenbossche comments in #440, remove the statements in database testing functions designed to handle pandas version <0.14.
=> CLN: Remove deprecated PANDAS_NEW_SQL_API check

geopandas/geodataframe.py, geopandas/geoseries.py
The series being an array subclass (`OLD_PANDAS` checks) dates from pandas <= 0.12, which we don't support anymore.
Also closes #443 (remove cache_readonly import, was not used)
=> CLN: clean up old compat code

geopandas/geoseries.py, geopandas/tests/test_geoseries.py
With the previous tests of the style `xs.start or xmin`, if `xs.start`
equalled 0, `xmin` was taken, ignoring the user specified slice boundary.
This fixes that issue, and adds miminal testing around slices with
boundaries at 0.
Closes #477
=> BUG: Fix handling of 0 slice in cx method (#477)

doc/source/index.rst, doc/source/indexing.rst, geopandas/base.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tests/test_geodataframe.py
In addition to applying the existing cx slicing functionality for `GeoSeries` to `GeoDataFrame` objects, I added a minimal page to the docs on indexing geodataframes, which includes an example of using the `cx` method.
=> ENH: add cx indexer to GeoDataFrame (#471)

.coveragerc
The inclusion of tests as part of the coverage seems a little distracting to me. Of course, if there's a good reason to keep them, it isn't that big a deal, but the projects with which I'm most familiar all seem to exclude tests.
=> TST: Omit tests from coverage report

Makefile, setup.py
Hopefully this will allow `make inplace` to work for more people and under more circumstances.  This gets the paths with system calls to `geos-config`.  XREF #473
=> Get include and library paths for GEOS from `shapely._buildcfg.get_os_config`

geopandas/tests/test_plotting.py
Instead of specifying the name of the default color table, verify that default geopandas plots have color schemes that match the mpl defaults, which as far as I can tell, still captures the spirit of the original tests. This addresses a couple of the testing failures introduced with matplotlib 2.0, and is a first step towards #278.
=> TST: Fix tests of color in matplotlib 2.0

.travis.yml, geopandas/tests/test_plotting.py
I reversed the way the test was applied for simpler handling between matplotlib versions, but I think the basic logic is the same.
Closes #278
=> TST: Fix test of LineString style in mpl>=2.0

geopandas/tests/test_pandas_methods.py
This adds tests of desired behavior of drop_duplicates as applied to
geoseries and geodataframes, with currently failing tests for both.
=> TST: Add (failing) tests of drop_duplicates

CHANGELOG.md
I followed the example in `rasterio` (whose change logs I like) and labeled the changes with "next", to be updated to `0.3.0` once we merge everything we want to include and release. I also changed the extension since it is written with markdown already, and improves the readability when browsing on github, but happy to change back if there is some reason I'm not seeing for it not having an extension.
=> RLS: add pre-0.3.0 changelog

.gitignore, geopandas/algos.c, geopandas/algos.h, geopandas/geodataframe.py, geopandas/kvec.h, geopandas/tests/test_geodataframe.py, geopandas/tests/test_vectorized.py, geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py, geopandas/tools/tests/test_sjoin_old.py, geopandas/vectorized.pyx
This uses GEOS's STRTree to implement a spatial join.
=> Add spatial-join algorithm

.travis.yml, appveyor.yml, requirements.txt
Some tests are failing since shapely 1.6 is used on CI (see eg https://travis-ci.org/geopandas/geopandas/jobs/267360623)
(reported to shapely: https://github.com/Toblerity/Shapely/issues/510)
=> TST: temporary pin shapely to < 1.6

geopandas/plotting.py, geopandas/tests/test_plotting.py
I went through the plotting code and did some clean-up (builds further upon the work of @IamJeffG):
- Changed the signature of the `plot_*_collection` functions. They now just have an optional `values=None` argument (instead of `colors_or_values, plot_values` combo where `plot_values` indicated whether `color_or_values` should be interpreted as colors or as values
- This makes the implementation IMO a bit cleaner
- This simplifies the code as I leave all handling of the color kwargs to matplotlib collection constructors (no need to set them manually)
- I removed the legacy handling of `alpha` for plotting polygons:
- Currently polygons were plotted twice to be able to apply alpha to fill color, but not to edge. Removed this hack, which implies of course a behavioural change that the alpha …
=> Clean-up / simplify plotting code

geopandas/io/file.py
This intercepts GDAL error and warnings so that they go to the Python logger instead of directly to stderr, solving confusing error messages like the one reported at https://github.com/Toblerity/Fiona/issues/468.
=> Open output file in a GDAL error-handling context

geopandas/geoseries.py, geopandas/tests/test_pandas_methods.py
Add same alias for notnull -> notna, and add tests of empty geometries
to ensure that the check is working for the case it is supposed to
catch.
Questions: 
- Are the docs sufficient? 
- I don't think what I've added is incompatible with changes in #512, but maybe I've missed something?
- This doesn't cover `isna` or `notna` on `GeoDataFrames`, which is consistent with existing behavior of `isnull`, where the override only occurs for `GeoSeries`. Should that change?
=> COMPAT: Alias isnull -> isna, following pandas

doc/source/io.rst, geopandas/io/file.py, geopandas/io/tests/test_io.py
=> Add basic support for remote resources to `read_file`

doc/source/conf.py, doc/source/mapping.rst, doc/source/reference.rst, geopandas/base.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tests/test_geom_methods.py
Fixes #530 
Uses sphinx autodoc for the reference documentation to pick out the docstrings of the corresponding attributes and methods.
The documentation originally in `reference.rst` has been merged with the docstrings inside the `.py`-files. An attempt has been made to make the documentation more consistent.
=> Improve API reference docs

geopandas/plotting.py, geopandas/tests/test_plotting.py
A few things changed between 2.0.0 and 2.0.1, causing tests to not pass against 2.0.0.
=> Add compatibility with Matplotlib 2.0.0

geopandas/tests/test_geodataframe.py, geopandas/tests/util.py
`validate_boro_df` had been used primarily for testing reads from a postgis database, and so was checking against lower case column names. In the one other place that `validate_boro_df` was used, it was changing column names prior to testing in order to use the existing functionality. I think this is a little more transparent functionality for any future situations in which `validate_boro_df` might be used.
=> TST: Add case sensitivity flag to validate_boro_df

geopandas/tests/test_geocode.py, geopandas/tools/geocoding.py
This uses geopy's `get_geocoder_for_service` to map strings to the proper class
to use, so a geopandas user can use any available geopy Geocoder. This also
provides the option to use a Geocoder instance, rather than the string
mapping, which is potentially more transparent. I'll add a couple inline notes on
potentially questionable changes.
Closes #468 and closes #539.
=> ENH: Expose all geopy services

doc/source/geocoding.rst
I think the documentation here is outdated. As a first-time user of Geopandas, I could only find the geocode function in the tools module. Is this correct?
=> DOC: Update geocoding.rst

geopandas/plotting.py, geopandas/tests/test_plotting.py
closes https://github.com/geopandas/geopandas/issues/377 and https://github.com/geopandas/geopandas/issues/355
I know you guys are considering overhauling the plotting methods (https://github.com/geopandas/geopandas/issues/405), so I won't mind if you'd rather not merge without a clear concept for geopandas' plottin API. 
the ``*_kwarg={}`` strategy is the one we follow in xarray, until now without too much trouble (the drawback is the high number of kwargs of course).
=> Add legend_kwds to plot()

geopandas/tests/test_geom_methods.py
Basic tests of `centroid` and `convex_hull` methods that were not previously covered.
=> TST: Add tests for centroid and convex_hull

geopandas/base.py
`_array_input` was not used anywhere, and has been sitting around unused
for ~4 years, so far as I can tell.
If this has a clear purpose I'm missing, I'm happy to close this. I just noticed it, tried to figure out what it was used for, couldn't discern any function it was currently serving, and making a PR to remove it was as easy as creating an issue to ask about it.
=> CLN: Remove unused internal function

geopandas/tests/test_geom_methods.py
The symmetric difference test compared a frame with a crs to one
without. It didn't seem that this was intentional, so set the second
frame crs to the first so that the tests run without warnings.
Warning below:
```
geopandas/tests/test_geom_methods.py::TestGeomMethods::()::test_symmetric_difference_series
/home/james/python/geopandas/geopandas/base.py:29: UserWarning: GeoSeries crs mismatch: {'init': 'epsg:4326', 'no_defs': True} and None
other.crs))
geopandas/tests/test_geom_methods.py::TestGeomMethods::()::test_symmetric_difference_operator
/home/james/python/geopandas/geopandas/base.py:29: UserWarning: GeoSeries crs mismatch: {'init': 'epsg:4326', 'no_defs': True} and None
other.crs))
```
=> TST: Set test gdf crs to silence crs warning

.travis.yml, geopandas/tests/test_block.py, geopandas/tests/test_geocode.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geom_methods.py, geopandas/tests/test_merge.py, geopandas/tests/test_pandas_methods.py, setup.cfg
Marking the remaining failures as `xfail`, so we can start relying on travis for further developing of the geopandas-cython branch.
I also marked the same tests with a cython mark, so you can do:
```
pytest geopandas -v --runxfail -m cython
```
to run all those tests in no-xfail mode to see the actual remaining failures.
Further trimmed down the travis build matrix (trying 0.19 for now)
=> TST: mark geopandas-cython failures and update travis matrix

README.md
A quick update to note the use of `conda-forge` when installing on OSX/Windows
=> DOC: update installation instructions in README

geopandas/tests/test_overlay.py
All current overlay tests have indices for which `loc`/`iloc` give the same
result. Since `ix` will be deprecated (and #579 would remove use of `ix`), add a test to
distinguish behavior between the two indexers.
=> TST: Add test of overlay with non-integer index

CHANGELOG.md, geopandas/tests/test_geodataframe.py, geopandas/tests/test_sindex.py, geopandas/tools/overlay.py, geopandas/tools/tests/test_sjoin.py
As of 0.20.0, pandas .ix is deprecated (http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated). This switches all such instances
to the label based .loc indexer. (In searching for usage, I also noticed
the CHANGELOG contained an error in describing the introduction of the
.cx indexer.)
=> COMPAT: Remove deprecated usage of ix

benchmarks/transform.py
Inspired by possibility of switch to `fiona` as basis of transform, rather than `pyproj` (#564). I just replicated the NYBB dataset by 10x since ~1 second runtime seemed like a good baseline amount of time for the test.
=> Add asv benchmark for to_crs

geopandas/tools/overlay.py
Handling for a bug discussed in
https://github.com/Toblerity/Shapely/issues/47#issuecomment-18506767
seems no likely necessary, given the issue was fixed 4 years ago.
Of course, not a big deal to leave this in place if there's concern about removal, I've just been looking around the code and seeing some references to fixes required for old versions of libraries geopandas depends upon.
=> CLN: Remove try/except for old GEOS bug

geopandas/plotting.py, geopandas/tests/test_plotting.py
This PR fixes #565 by introducing a check in `plot_dataframe`  to make sure the table is not empty. If `df.shape[0] > 0`, it proceeds; otherwise, it issues a warning and returns the original `ax` (if nothing's passed, the `None` is returned).
=> Fix error on plot empty GeoDataFrame

setup.cfg
Put both under [tools:pytest] section to silence warnings.
=> CLN: Consolidate pytest sections in setup.cfg

geopandas/geoseries.py, geopandas/tests/test_geoseries.py
Related to https://github.com/geopandas/geopandas/pull/587#issuecomment-337393467 (but this only fixes align to preserve the metadata, does not yet add the warning to `binary_geo`)
=> Fix align to preserve metadata

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
a fix and some unit tests for issue #525. Original panda dataframe's index names are no longer changed by sjoin() call.
This pull request follows on from request #538 (I reorganised my github fork and broke things)
My original code didn't work for pandas 0.16.2 and so I've found the following way to make the code work across pandas version 0.16.0 - 0.20.0
left_df = left_df.copy(deep=True)
left_df.index = left_df.index.rename(index_left)
left_df = left_df.reset_index()
I wanted to do copy(deep=False) in order to save a copy but the geopandas code for the copy method is different from the pandas method code and so it didn't work (but works for a pandas dataframe). Is there a reason for that?
pandas code is
data = self._data.copy(deep=deep)
return self._constructor(data).__finalize__(self) …
=> BUG: retain index names of input frames to sjoin

geopandas/_geos.pxi, geopandas/vectorized.pyx
Previously we called a Cython function that obtained the handle at every
function call.  We inherited this behavior from Shapely and they
presumably had some reason to do it.  We are trying this change to avoid
an error around get_geos_context_handle during tests.
=> Obtain GEOS Handle at every function call

geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
Closes https://github.com/geopandas/geopandas/issues/602
Logic: if we specify a `geometry` keyword that is not a string, drop any columns in the passed data that have the same name (the default 'geometry' or the derived geometry name if a Series is passed to `geometry`)
=> BUG: let geometry kwarg override geometry in data in GeoDataFrame constructor

geopandas/base.py, geopandas/geoseries.py, geopandas/tests/test_geoseries.py
Closes https://github.com/geopandas/geopandas/issues/598
As this PR stands, it at least addresses the individual specific issue raised in #598; `geom_equals` already avoids densifying, so just need to override `__eq__` on a `GeoSeries` to use `geom_equals`. That said, it is not clear to me if there was any particular reason why this behavior was not already in place on master. I would have assumed it was, so the fact that it was not makes me wonder if I'm missing something.
If this is the right way to go, I at least need to add `__ne__` as well. I'm not sure if there's anything else of that sort that makes sense to add.
=> Override __eq__ with geom_equals for GeoSeries

doc/source/geocoding.rst
Shows the location of borough centers accessed through Google geocoding
API, along with the boundaries in the shapefile included in geopandas.
=> DOC: Add minimal geocoding example for docs

geopandas/plotting.py, geopandas/tests/test_plotting.py
Can optionally set the size of points in a scatter plot of point
geometries to be specified by the value of a column in the frame. Note
that it does not perform any normalization at present, so very small or
very large values in the column specified lead to less than desirable
results. Also no checks on user, so if a user specifies a column with a
non numeric type, it does throw a slightly less than clear error.
I can see addressing either of those potential shortcomings as useful. Though
unlike the `column`/`colormap` case, there isn't really a natural range by which
`markersize` values should be normalized, and adding options for that seems
too much. 
Closes #624. cc @h4k1m0u
=> ENH: Set point markersize with column values

geopandas/io/file.py, geopandas/tests/test_geodataframe.py
Fiona doesn't support writing to files with boolean type. There was some
discussion of converting to int and writing to file anyway, but at a
minimum seems useful to raise a clearer message about the problem.
Closes #437.
=> Raise ValueError using to_file with bool column

README.md, setup.py
The descartes import in plotting is hidden, so it is not a hard
dependency, and should not be required for installation.
Closes #647.
=> Remove descartes from install requirements

geopandas/base.py, geopandas/io/file.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geom_methods.py
In so doing, add the has_z attribute to series. The check in determining
the geometry type is pretty simplistic. Given how fiona is thinking
about geometry types now (https://github.com/Toblerity/Fiona/issues/465)
I didn't see a clearly better way.
Closes #612.
=> BUG: Save z dimension in file writes

geopandas/tests/util.py
The assert_seq_equal test was not used, and was written in such a
way that it would never fail.
=> BUG/CLN: remove unused and broken test utility

.travis.yml
As of https://github.com/matplotlib/matplotlib/commit/c36902c19622aae8102e12d6ffb4b65f84211465#diff-2eeaed663bd0d25b7e608891384b7298, matplotlib master no longer supports python 2.7. Given the impending deprecation plans for 2.7 across the scientific python stack, it seems reasonable to drop the python2.7 build check for pandas/matplotlib master. Currently, the travis build check is failing everywhere because matplotlib master cannot install with python 2.7.
=> BLD: remove pandas/matplotlib master from 2.7

geopandas/base.py, geopandas/tests/test_geom_methods.py
Not doing so resulted in incorrect dtypes when the
result was empty since numpy could not automatically
determine the dtype. This then had the effect of
indexing dropping columns unexpectedly.
Closes #685
=> Explicitly set the dtype for geometry operations

doc/source/mapping.rst
I noticed some differences between the docs and the source code. By default scheme is ``None`` and ``equal_interval`` mustn't end with an s otherwise an exception is raised. I also changed the link because the current URL resolves to a 404 error.
=> Adjust the scheme option docs to reflect the source code

geopandas/array.py, geopandas/tests/test_vectorized.py, geopandas/vectorized.pyx
Currently the `cast=True` in cython leads to silently wrong data (`points_from_xy` requires float64 data):
```
In [12]: a = geopandas.array.points_from_xy(np.array([0, 1]), np.array([0, 1]))
In [13]: [p.wkt for p in a]
Out[13]: ['POINT (0 0)', 'POINT (4.940656458412465e-324 4.940656458412465e-324)']
In [14]: a = geopandas.array.points_from_xy(np.array([0, 1], dtype='float64'), np.array([0, 1], dtype='float64'))
In [16]: [p.wkt for p in a]
Out[16]: ['POINT (0 0)', 'POINT (1 1)']
```
=> BUG: fix points_from_xy for non-float data

geopandas/tests/test_vectorized.py, geopandas/vectorized.pyx
Mimicked the existing `serialize` function, but writing to an object array instead of a single bytearray.
=> Add vectorized to_wkb function to convert to object arrays of bytes 

.travis.yml
Clean-up of the travis yaml file. 
(could maybe even more aggressively remove more old versions)
=> TST/DEP: remove support for pandas <0.19

geopandas/testing.py, geopandas/tests/test_testing.py, geopandas/tests/util.py
This moves the testing functionality from `geopandas.tests.util` to `geopandas.testing`, as this is generally useful functionality. 
And also adds a `assert_geodataframe_equal` method that uses `assert_geoseries_equal` for the geometry column, to ensure correct comparison of that column.
=>  Add assert_geodataframe_equal function + expose testing functions in geopandas.testing module

geopandas/tests/test_overlay.py, geopandas/tools/overlay.py
Added some more tests for `overlay` comparing to actual output (so using simple example dataframe like in docs, and not only checking shape). 
Wanted to do this before #338 to ensure the perf improvements do not change the output.
=> TST: more thorough testing of overlay

geopandas/plotting.py
This is one way to address #715 
Another way is to push this on users, to suggest that every time a multi-axis figure is built using:
`f,ax = plt.subplots(2,2,figsize=(10,10), subplot_kw=dict(aspect='equal'))`
If it's better to not set `aspect=equal` by default, then maybe just showing the way to set all axes in a subplot to equal aspect in docs would help it be recognized.
=> always set equal aspect on active axis

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
Closes #731
This makes sure that the key dtype in empty spatial joins is `float`, addressing but #731.
=> BUG: fix empty sjoin

doc/source/projections.rst, geopandas/plotting.py
@jorisvandenbossche @slumnitz Does this seem sufficient to resolve #764? It does seem reasonable that a downstream test of geopandas install from the test requirements file, in which descartes is included.
=> Add error message if descartes import missing

geopandas/io/sql.py, geopandas/io/tests/test_io.py
After further investigation, it seems like the current `read_postgis`
command would not support a spatialite database in the wild (as compared
to the one I'd created using ogr2ogr that had made me optimistic that we
had spatialite read capabilities in place). So long as it is not likely
to work for more use cases, let's leave it as `read_postgis`, since that
is all we think it is likely able to do.
=> BUG: Remove read_sql alias

geopandas/plotting.py
A minor refactoring to use generators instead of lists in built-in Python functions. Please feel free to reject this, if it's unnecessary.
=> CLN: Use generators inplace of lists

doc/source/mapping.rst
Corrected mapping scheme options from percentiles to fisher_jenks.
"Options are 'Equal_interval', 'Quantiles', 'Fisher_Jenks'"
See: https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L522
=> DOC: Corrected Mapping Tools scheme options

.travis.yml
All tests are currently failing due to installation problems with conda-forge (see also https://github.com/conda-forge/geopandas-feedstock/pull/43#issuecomment-412686051). 
This PR will not solve this for the conda-forge builds, but does correct the mixing of conda-forge and defaults (I added a channel flag and added the channel if it was specified, but then hard-coded the use of conda-forge for the first install command). 
Now we explicitly run some builds with conda-forge channel added, and the others without conda-forge
=> CI: fix usage of conda-forge in travis.yml

geopandas/base.py, geopandas/tests/test_geom_methods.py
This PR allow to use a `np.ndarray` or a `pd.Series` as `distance` argument for the `buffer` and `interpolate` methods of GeoSeries and should closes #767 if merged.
=> ENH: allow to specify varying distances for buffer and interpolate

doc/source/conf.py, geopandas/geodataframe.py, geopandas/tools/geocoding.py
There are some warnings issued by Sphinx when building the docs.
This PR fixes most of the warnings. There are four outstanding warnings about missing `source/reference/geopandas.<smth>.examples` files. These warnings should probably be fixed by creating examples :blush:
=> DOC: Remove warnings when building docs

geopandas/plotting.py
Working with some rather brightly colored labelled data, I noticed that the legend styling can be very visually discordant for some colormaps. 
This errs in the same direction as the other cartography, using no boundaries on patches by default:
If there's anything else we'd like to see from legend symbology here, I'm very OK with keeping this open and adding that functionality (@lwasser #735), so long as it's agreed. 
For instance, we could align `geom_types` and `categories` and check during the`(value,cat)` loop at line 497 if `cat` is all of one geometry type. If it is, we could set the marker style intelligently based that type (e.g. polygons get `marker='s'`, points get `marker='o'`, and lines get `marker='-'` or something via `markeredgewidth`).
=> VIS: remove marker edge from legend

geopandas/geoseries.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geoseries.py
The crs was not preserved when aligning GeoSeries objects + added some more thorough test for align
=>  BUG/TST: fix align to preserve metadata + more tests 

geopandas/testing.py, geopandas/tests/test_overlay.py, geopandas/tests/test_testing.py
I just tracked down this bug when using geopandas.testing.assert_geodataframe_equal. I kept being confused as to why my test was succeeding when it shouldn't. This appears to be a typo. I didn't see any other mistakes.
This is my first commit to geopandas. Let me know if you need anything else. Thanks for all your hard work!
=> Fix assert_geodataframe_equal to correctly compare left and right

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
Fix for #841. Also added some more information to the warning raised for mismatching CRS.
Seems like my autopep8 format on save also touched a few more lines in the sjoin test.
=> Raise exception from sjoin if inputs are not GeoDataFrames

.travis.yml, ci/travis/27-dev.yaml, ci/travis/27-latest-conda-forge.yaml, ci/travis/27-latest-defaults.yaml, ci/travis/27-pd020.yaml, ci/travis/35-minimal.yaml, ci/travis/36-pd020.yaml, ci/travis/36-pd022.yaml, ci/travis/37-dev.yaml, ci/travis/37-latest-conda-forge.yaml, ci/travis/37-latest-defaults.yaml, geopandas/geodataframe.py, geopandas/io/sql.py, geopandas/io/tests/test_io.py, geopandas/tests/util.py
Though GIS databases allow missing geometry values, `from_postgis` breaks when it encounters them.
These patches fix `from_postgis` and `GeoDataFrame` to allow nulls, and test for the feature with sqlite.
Should [`create_sqlite`][1] get a GIS-oriented rewrite?
Though [`create_sqlite`][1] seemed to have been written for SQLite tests, its original design assumes data isn't stored to perform geospatial analysis within SQLite, which I find questionable.
While comments under [`create_postgis`][2] remind the tester to load a GIS extension in their database, [`create_sqlite`][1] lacks such comments and instead stores geometries as opaque blobs that SQLite's GIS extension, [SpatiaLite][3], wouldn't store.
I would think anyone seriously using GeoPandas and SQLite for GIS analysis would load and …
=> BUG: fix from_postgis to accept nullable geometry

doc/source/conf.py
IPython 7.0 now makes sphinx stop the full doc build if an unexpected warning or error happens in one of the examples. There is an option to restore the old behaviour (to only print the tracebacks), which is IMO more useful (you at least see all errors, and not only the first one).
=> DOC: continue doc build on warnings/errors in examples

ci/travis/27-dev.yaml, ci/travis/27-latest-conda-forge.yaml, ci/travis/27-latest-defaults.yaml, ci/travis/27-pd020.yaml, ci/travis/35-minimal.yaml, ci/travis/36-pd020.yaml, ci/travis/36-pd022.yaml, ci/travis/37-dev.yaml, ci/travis/37-latest-conda-forge.yaml, ci/travis/37-latest-defaults.yaml, geopandas/plotting.py, geopandas/tests/test_plotting.py, requirements.test.txt
Fix to #721 
PySAL, which is being used for classification of choropleth maps is changing its structure (http://pysal.org/about.html). Instead of depending on the full PySAL we can now use package mapclassify directly. Currently used pysal.esda.mapclassify will be soon deprecated. 
During this edit, I have also added option to use Fisher_Jenks_Sampled scheme, which can be useful for large datasets.
=> Use mapclassify instead of PySAL due to change of PySAL structure.

geopandas/io/file.py, geopandas/tests/test_geodataframe.py
Per https://github.com/Toblerity/Fiona/pull/539 this seems like the right way to handle this case.
```
import os
from shapely.geometry import Polygon, MultiPolygon
p = Polygon([(0., 0.), (0., 1.), (1., 1.), (1., 0.), (0., 0.)])
gdf = gpd.GeoDataFrame({'a':[1,2]}, geometry=[p, MultiPolygon([p])])
try:
os.remove('/tmp/test.geojson')
except:
pass
gdf.to_file('/tmp/test.geojson', driver='GeoJSON')
```
The above works on Fiona==1.7.13 but on Fiona==1.8a2 gives
```
GeometryTypeValidationError: Record's geometry type does not match collection schema's geometry type: 'MultiPolygon' != 'Polygon'
```
Setting the schema like in this PR works with both versions:
```
gdf.to_file('/tmp/test.geojson', driver='GeoJSON', schema={**gpd.io.file.infer_schema(gdf), 'geometry': …
```
=> Default to `'Unknown'` geometry schema

geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
Fix for #863 .
I referred to @jorisvandenbossche 's code very much.
I implemented three different na strategies (null, drop, keep).
Under my PC environment, the speed improvement was nearly nine times as follows.
%timeit list(df.iterfeatures())
Before: 3.36 s ± 225 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
After : 375 ms ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
(The same condition as @jorisvandenbossche 's [Notebook](http://nbviewer.jupyter.org/gist/jorisvandenbossche/3bea109e0622fa5e3f90eecdc496c816) )
=> PERF: Improve iterfeatures performance

geopandas/geodataframe.py, geopandas/io/sql.py
It adds the argument `parse_dates`. The default value is None.
I just add the possibility you have pandas `read_sql` function to specify columns for date parsing to geopandas `read_postgis` function.
I didn't add any test because I was not sure if it was required for such a small change. I'm also unsure of how to do it but if you give me hints I will do it.
=> ENH: parse date for read_postgis

geopandas/plotting.py, geopandas/tests/test_plotting.py
Changes in #770 wrong behaviour of `mn = values.min() if vmin is None else vmin` and `mx = values.max() if vmax is None else vmax` which lead to wrong colours during plotting. 
Previous version was passing Series, which ignores NaNs in min() and max(). Now it is passing numpy array which returns NaN for min() and max() (if there are any).
Resolves #877
=> BUG: Ignore NaN in setting mn and mx (#877)

geopandas/tools/__init__.py, geopandas/tools/crs.py, geopandas/tools/tests/test_tools.py
Gets full/explicit CRS from EPSG code provided. This provides useful logic for #245 when used like `gdf.to_crs(crs=explicit_crs_from_epsg(other_gdf.crs))`. Additionally this could provide a 90% solution for not performing `to_crs` unnecessarily by checking `if explicit_crs_from_epsg(gdf.crs) == explicit_crs_from_epsg(other_gdf.crs)` prior to running `to_crs` could then be used as part of a resolving #65.
Note, I didn't know where this should go (in code or in the docs) so I created the file you see, however I leave it at the discretion of the maintainers as to where it best fits and what documentation it needs (and I'm happy to revise once given direction).
=> ENH: get explicit CRS from EPSG code

doc/source/mapping.rst, geopandas/plotting.py, geopandas/tests/test_plotting.py
Following #872 and responding to #235 and #357, I have added access to all mapclassify schemes. It is possible to pass kwargs in classification_kwds dict in the exactly same way as it is for legend_kwds. k can be passed as normal argument (same as now)(will be ignored if scheme does is not k-based) or in classification_kwds. If both will be passed, latter will overwrite former. 
I have also added simple test to check if args were passed. Hope you will find it useful, those issues are quite old, I just felt it could be easily done.
=> Access to all mapclassify schemes including keywords (#235, #357)

doc/source/geocoding.rst
The request to google is frequently (always?) failing in the past few
months, so use geocodefarm instead for the example of how to use
geocoding in geopandas.
=> DOC: Use geocodefarm rather than google for example

doc/source/conf.py
Currently due to an installation problem (https://github.com/conda-forge/geoplot-feedstock/pull/5#issuecomment-450808839), the example is not running. 
But even when the latest geoplot is used, it will fail for some time due to the `__pysal_choro` -> `_mapclassify_choro` rename.
=> DOC: temp allow failure in geoplot example gallary

ci/travis/36-pd020.yaml
Travis CI tests were failing recently for one specific build, see https://github.com/conda-forge/gdal-feedstock/issues/261
Fixed by removing the pin of matplotlib to 1.5.3 (but added `gdal=2.3` to keep at older gdal version). 
Also added `nomkl` to have a built with numpy/openblas from conda-forge (not that it should matter though).
=> CI: fix the conda-forge env with pd 0.20 (remove pin of old matplotlib)

appveyor.yml, geopandas/tests/test_pandas_methods.py, requirements.test.txt
Pandas 0.24 changed default lineterminator
to os.linesep (so OS dependent now).
=> TST: fix to_csv test on Windows

doc/source/mapping.rst, geopandas/plotting.py, geopandas/tests/test_plotting.py
This PR aims at solving issue #702 , and it is directly inspired from reviews done in PR #704 by @jdmcbr .
The point is to improve colormap representation when plotting a GeoDataFrame feature. On master we get oversized colormaps next to main plot:
The `geopandas` new version after PR gives:
Before calling the `gdf.plot(.)` method, we have to write the following lines:
```
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
fig, ax = plt.subplots(1, 1)
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.2) # depends on the user needs
```
Hence goes the GeoDataFrame feature plotting:
```
gdf.plot("feature", ax=ax, cax=cax, legend=True)
```
This new behavior allows to tune the colormap, without including the tuning …
=> Consider a new plotting artist for improving colormap legends

doc/source/geocoding.rst, geopandas/tests/test_geocode.py, geopandas/tools/geocoding.py
I hesitated to do this before for the docs, but it is nice to have the
default provider be one that works without an API key (which is now
required for google). The downside of this is that geocodefarm has only
been an option since May 2018, so if someone tries just running the
examples and doesn't have prior experience, they'll get a crash due
to a missing provider rather than a crash due a missing API key.
=> Set nominatim as default geocoding service

examples/create_geopandas_from_pandas.py, geopandas/__init__.py, geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
Following discussion at #833 this PR is adding `points_from_xy()` function to convert coordinates stored in the separate columns (or other objects) to `shapely.Point` to be used as `geometry`. 
I just wasn't sure where to put the function (and the test) as it is a bit independent function not so much related to GeoDataFrame or GeoSeries. It is in geodataframe.py as it is designed to be used while creating geometry for GeoDataFrame.
**From longitudes and latitudes** example has been updated to use this new function a well.
=> ENH Provide API to convert x, y(, z) coordinates to geometry

geopandas/io/file.py
This is a fix for #881 
It simply wraps the reading code in a `with fiona_env()` block, like in `to_file()`.
=> Read in a fiona.Env() block to make sure GDAL_DATA is set

geopandas/geoseries.py, geopandas/tests/test_pandas_methods.py
A recent change on pandas master (https://github.com/pandas-dev/pandas/pull/25272) made it so that `isna` now preserves the subclass (resulting in a boolean GeoSeries, which caused the current failures on travis for pandas master).
It might still be changed on the pandas side before a release, but ensuring it on the GeoPandas side with this fix (so our builds are green, and also it shouldn't cause any harm even if the pandas behaviour would be changed back).
=> Ensure GeoSeries.isna is always a Series and not GeoSeries

geopandas/io/file.py
This was deprecated in numpy 1.16 and prints a warning on every invocation.
The function was just a thin wrapper around .item() since a long time(Maybe forever, not sure about that), so this should have no impact on people using older versions.
=> COMPAT: use .item() instead of deprecated np.asscalar()

examples/plotting_with_geoplot.py
See https://github.com/ResidentMario/geoplot/issues/69: depending on how the data are subsampled, we stumble into a potential bug in geoplot. So fixing the random state with a working one to prevent this.
=> DOC: fix random state in geoplot voronoi example to prevent random errors

.travis.yml, ci/travis/27-pd023.yaml, ci/travis/37-dev.yaml
- remove py27 dev build (pandas master no longer supports python 2.7) and replace with pandas 0.23 build
- py37 dev build: move installing pandas and matplotlib master to separate steps in travis yml file (otherwise the conda create step takes too long)
- remove conda-forge/label/dev label for fiona (was still installing the rc instead of actual released version)
=> CI: update travis builds

README.md, doc/source/geometric_manipulations.rst, doc/source/io.rst, doc/source/mergingdata.rst, examples/spatial_joins.ipynb, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tools/sjoin.py, setup.py
Update links to point at `shapely.readthedocs.io` and `fiona.readthedocs.io` to avoid the 404 page found on `toblerity.org` in the current documentation.
=> Fix broken links to Shapely and Fiona docs

geopandas/base.py
The buffer resolution has to be an int. Passing a float will result in:
```ArgumentError: argument 4: <class 'TypeError'>: wrong type```
=> DOC: buffer resolution is an int, not a float.

geopandas/tests/test_plotting.py
Since matplotlib is an optional requirement, this allows to also runs the tests with only the base dependencies.
=> TST: skip plotting tests if matplotlib is not installed

geopandas/tests/test_crs.py, geopandas/tests/test_geodataframe.py, geopandas/tools/tests/test_tools.py
Our tests are broken with proj.4 6 / pyproj 2 (see https://github.com/pyproj4/pyproj/issues/269 for context). 
So updating the tests here to just make sure they are correctly working and passing with the latest pyproj (without any change to optimally use the changes in pyproj 2, that's already done in another PR). 
And while at it, I isolated the `to_crs` related tests in a separate file, with the intent to add some more extensive testing of the current functionality.
=> TST/CI: update CRS tests + ensure compatibility with proj.4 6 / pyproj 2

geopandas/geoseries.py, setup.py
Closes https://github.com/geopandas/geopandas/pull/962#issue-267016435
Since version 2.0.0 pyproj have a new way to optimize transformation.
I don't know a lot about geopandas to maybe i did it wrong but the last version of pyproj make the transformation a lot slower (about 100 000 times slower).
see https://pyproj4.github.io/pyproj/html/optimize_transformations.html for more information.
so this PR intend to fix the performance loss
=> PERF: Optimize pyproj >= 2.1 transformations 

ci/travis/27-pd023.yaml, ci/travis/35-minimal.yaml, ci/travis/36-pd022.yaml
Some of the builds on defaults are still using fiona 1.7, but pinning this explicitly in the env files to make sure we keep testing it for now, also if the packages would get updated.
=> TST/CI: pin a few builds to older fiona version

doc/source/conf.py
See eg the result of the spatial join in this example: https://geopandas.readthedocs.io/en/v0.4.0/mergingdata.html#spatial-joins
Due to some changes in the pandas display machinery (default option for the number of columns changed from 20 to "whathever fits on one line"), the output is not always shown. Therefore setting it here manually to the old setting, and also increasing the width a bit.
=> DOC: set pandas display options to ensure non-truncated output

doc/environment.yml
This should fix the version check error we are seeing on readthedocs (can't reproduce it locally, but it is fixed in the latest geoplot anyway, xref https://github.com/ResidentMario/geoplot/issues/72)
=> DOC/BLD: update geoplot version in readthedocs environment

doc/source/geocoding.rst, geopandas/tests/test_geocode.py, geopandas/tools/geocoding.py
I started off this way in #907, then switched to nominatim, but our
current usage appears to be a violation of the nominatim terms of
service. Geocodefarm doesn't seem perfect, but given my reading of their
terms of service, I think using it in our examples in docs is okay.
=> Switch geocoding default to geocodefarm

geopandas/array.py, geopandas/base.py, geopandas/geoseries.py, geopandas/tests/test_geom_methods.py
Another part of https://github.com/geopandas/geopandas/pull/835, in preparation to make GeometryArray an actual ExtensionArray. 
This PR already moves the implementations out of base.py to a GeometryArray class (which for now is just holder of those methods, without other functionality) in array.py.
It might not look like a that useful refactor on its own, but will make the diff for the ExtensionArray PR smaller.
=> REF: move element-wise geo ops to array class

geopandas/__init__.py, geopandas/array.py, geopandas/geodataframe.py, geopandas/tests/test_array.py, geopandas/tests/test_geodataframe.py
Another preparation PR for moving to ExtensionArrays (WKB will be useful for factorizing, WKT for repr), and those methods will also be useful in general.
For now not exposed top-level, only in the `array` module (except for the already existing `points_from_xy` which I moved there).
=> ENH: add constructors / converters for shapely, WKT and WKB

geopandas/geodataframe.py, geopandas/geoseries.py
I started looking at the issue raised in #881, and realized there was a
somewehat extraneous codepath with `fiona.open` in the geoseries
`read_file` method. This gives one fewer place to make
updates to use `fiona.Env()`.
It seems a little more natural to me to use the
`io.file.read_file` method here, but the adjoining two class methods are
importing from geodataframe and using the methods on `GeoDataFrame`
objects, so I followed suit here.
=> CLN: Use read_file from geodataframe in geoseries

benchmarks/geom_methods.py, doc/source/geometric_manipulations.rst, doc/source/reference.rst, geopandas/array.py, geopandas/base.py, geopandas/tests/test_geom_methods.py
=> ENH: Add affine_transform method to GeoSeries

appveyor.yml
Attempt to fix https://github.com/geopandas/geopandas/issues/1022, and something we should do anyway to make the approach similar as on Travis (for now trying to use the same env files as for travis, but could make specific ones for appveyor if needed)
=> CI: use conda environment files for Appveyor builds

examples/plotting_with_geoplot.py
Some minor renovations to the `geoplot` example gallery in the documentation necessitated by the `geoplot@0.3.0` release. Also cleans up some code here or there.
=> Update geoplot docs.

doc/environment.yml
Readthedocs is failing currently due to the update of geoplot example, which was not reflected in the environment file.
It may fail for some time anyway as GDAL on conda-forge is broken at this moment. (https://github.com/conda-forge/gdal-feedstock/issues/303) Travis for this PR will probably fail as well.
=> DOC: update geoplot version for rtd environment

doc/source/contributing.rst
Recent PRs involving update of docs #1058 https://github.com/geopandas/geopandas/issues/1052#issuecomment-511123455 suggest that our contributing guidelines for that part are insufficient. I have expanded it a bit, to make clear that it is not strictly required to run `make html` and that it might be needed to use environment.yml for env creation before doing that.
=> DOC: Expand contributing/documentation

ci/travis/27-latest-conda-forge.yaml, ci/travis/37-latest-conda-forge.yaml
For context, see https://github.com/conda-forge/segregation-feedstock/pull/2#issuecomment-514687151
Example failing build: https://travis-ci.org/geopandas/geopandas/jobs/564925601#L514
=> CI: add zstd as dependency to fix conda-forge problem with latest fiona / gdal

ci/travis/36-pd023.yaml
Test to see if this fixed the travis build, see also https://github.com/conda-forge/fiona-feedstock/issues/135
=> CI: use defaults for py36 build

geopandas/geoseries.py, geopandas/tests/test_pandas_methods.py
Closes https://github.com/geopandas/geopandas/issues/1078
The pandas bug itself is described at https://github.com/pandas-dev/pandas/issues/27785.
=> BUG: workaround in GeoSeries constructor for pandas loc bug

ci/travis/37-latest-conda-forge.yaml, geopandas/plotting.py, geopandas/tests/test_plotting.py
As pointed out in #1081, `pysal` package includes codebase of `mapclassify`. If `pysal` is installed but `mapclassify` not, this PR will use `pysal.viz.mapclassify` to get scheme in plotting.
Not sure how to test it though, maybe having mapclassify in one env and pysal in other?
Closes #1081
=> ENH: allow pysal alongside mapclassify for plotting scheme

examples/plotting_basemap_background.py
Updated contextily example to use `add_basemap` from contextily 1.0. However, I would wait with merging until contextily 1.0.0 is stable as `pip install contextily` now installs 0.99.0 which does not work with this example.
Closes #1077
=> DOC: update contextily example

geopandas/tests/test_show_versions.py, geopandas/tools/_show_versions.py
Closes #899 
Added info on GDAL, GEOS and PROJ to show_versions.
I have to admit that merge of #918 was a bit premature as I decided to extend it shortly after that. Nevermind. show_versions in this PR:
```
SYSTEM INFO
-----------
python     : 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)  [Clang 4.0.1 (tags/RELEASE_401/final)]
executable : /Users/martin/anaconda3/envs/guide/bin/python
machine    : Darwin-18.6.0-x86_64-i386-64bit
GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.7.2
GEOS lib   : /Users/martin/anaconda3/envs/guide/lib/libgeos_c.dylib
GDAL       : 2.4.2
GDAL dir   : /Users/martin/anaconda3/envs/guide/share/gdal
PROJ       : 6.1.0
PROJ dir   : /Users/martin/anaconda3/envs/guide/share/proj
PYTHON DEPENDENCIES
-------------------
geopandas  : …
```
=> ENH: show_versions including GDAL, GEOS, PROJ

geopandas/array.py
Currently, the GeometryArray is not that useful if you have big (Multi)Polygons, because the default implementation does not do any truncation of the WKT strings.
Eg 
```
df = geopandas.read_file(geopandas.datasets.get_path("naturalearth_lowres"))
df.geometry.array
```
gives a huge unusable repr. 
So therefore falling back to the shapely reprs (ala `<shapely.geometry.multipolygon.MultiPolygon object at 0x7f8abec050b8>`), until we have a better solution for truncating the strings, if we want that (the `Series/DataFrame` repr already does this automatically, so this is only for `GeometryArray`, so not super high priority)
=> Use shapely repr instead of WKT in repr of GeometryArray

geopandas/geoseries.py, geopandas/tests/test_geoseries.py
Related to the "strict GeoSeries constructor" bullet point in https://github.com/geopandas/geopandas/issues/1000  and also related to https://github.com/geopandas/geopandas/issues/53
This *seems* to work (I am not 100% sure that pandas does not expect an actual class in `_constructor`, but our tests seem to indicate it works)
=> API: deprecate GeoSeries fallback to return Series for non-geometry data

.travis.yml
Temporarily disabling `27-latest-defaults`. It currently fails, due to the error I was not able to track back (no idea what has changed), but which is out of our hands.
```
from urllib2 import urlopen as _urlopen    
url = ("https://raw.githubusercontent.com/geopandas/geopandas/master/examples/null_geom.geojson")       
_urlopen(url)
```
Fails with
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/martin/anaconda3/envs/test/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/Users/martin/anaconda3/envs/test/lib/python2.7/urllib2.py", line 429, in open
response = self._open(req, data)
File "/Users/martin/anaconda3/envs/test/lib/python2.7/urllib2.py", line 447, in _open
'_open', req)
File …
```
=> CI: disable 27-latest-defaults

doc/source/reference.rst, geopandas/geodataframe.py, geopandas/geoseries.py
I have cleaned code a bit by removing which were necessary for older pandas (<0.17). Everything seems to work without these pieces. I have also implemented `pd.api.types.is_list_like` in `_set_geometry` which I found as a TODO in the code during the cleaning. I can split it into two PRs, but it seems not necessary as all edits are basically keeping up with pandas development.
Closes #1070
=> REF: remove unnecessary fixes for older pandas, use pandas is_list_like

doc/source/mapping.rst, geopandas/plotting.py, geopandas/tests/test_plotting.py
This PR exposes the kwargs of matplotlib.pyplot.colorbar to plot().  The following example demonstrates its use for horizontal colorbars located at the bottom.
```
from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable
import geopandas as gp
import matplotlib.pyplot as plt
df = gp.read_file("g2g14vz.shp")
cmap = "inferno"
fig, (ax1, ax2) = plt.subplots(1, 2)
divider = make_axes_locatable(ax1)
cax1 = divider.append_axes("bottom", size="5%", pad=0)
df.plot(column="AREA_HA", cmap=cmap, ax=ax1, cax=cax1, legend=True, cbar_kwds={"orientation": "horizontal"}, vmin=0, vmax=2000)
divider2 = make_axes_locatable(ax2)
cax2 = divider2.append_axes("bottom", size="5%", pad=0)
df.plot(column="AREA_HA", cmap=cmap, ax=ax2, cax=cax2, legend=True, vmin=0, vmax=2000) …
```
=> ENH: pass legend_kwds to colorbar when relevant

examples/create_geopandas_from_pandas.py
Fixes empty plot object being shown in example page for the documentation, introduced in PR #1105. See: https://geopandas.readthedocs.io/en/latest/gallery/create_geopandas_from_pandas.html#from-wkt-format
=> DOC: fix plotting in 'pandas to geopandas' example

geopandas/plotting.py, geopandas/tests/test_plotting.py
As reported earlier, passing a list-like of colors to gdf.plot() will not match rows if there are multipart geometries. That should be fixed now. 
Fixes #1075, fixes #730
=> BUG: pass list-like colors to Multi- geometry

geopandas/plotting.py, geopandas/tests/test_plotting.py
Fixes #869
`norm` keyword currently doesn't persist for all subplots (see original issue). This behaviour should be fixed now.
Implements solution by @ImportanceOfBeingErnest outlined in the issue.
=> BUG: norm not persisting when using subplots 

geopandas/io/file.py, geopandas/io/tests/test_file.py
Fixes #1118.
I tried to add a better test, but couldn't come up with anything that didn't require cloud storage credentials in the test suite (the `zip` and `tar` VSIs don't support output like this, apparently). So I've settled for testing that the utility works as expected, and verified locally that this allows, e.g., writing GeoJSON to s3.
=> Don't convert to absolute path in to_file to preserve VFS paths

geopandas/array.py, geopandas/tests/test_array.py, geopandas/tests/test_extension_array.py
`geoseries != geoseries` was raising an error on master. 
This should also solve the error on Travis in the DEV (pandas master) build
=> BUG: fix != operation

geopandas/plotting.py, geopandas/tests/test_plotting.py
In current version, if you use normalisation, colorbar does not represent true color scheme as it is always normalized linear between min and max. This PR fixes the behaviour and normalises colorbar using the same scheme, so the results should match. 
It should resolve issue like https://github.com/geopandas/geopandas/issues/697#issuecomment-515499696 . 
```
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
gdf['random'] = np.random.gamma(2, 2, len(gdf)) - 2
vmin, vmax, vcenter = gdf.random.min(), gdf.random.max(), 0
divnorm = colors.DivergingNorm(vmin=vmin, vcenter=vcenter, vmax=vmax)
gdf.plot(column='random', cmap='RdBu', legend=True, norm=divnorm)
```
Before:
After:
Closes #697
=> BUG: colorbar did not match normalised colors

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
Fixes #944
Takes care of intersection with empty geometry. I will add tests for this specific case tomorrow.
=> BUG: fix sjoin with empty geometry

geopandas/array.py, geopandas/tests/test_array.py
xref https://github.com/geopandas/geopandas/issues/1145
It doesn't close that issue, but it does solve the `astype` part that we have control over on the geopandas side.
=> BUG: fix astype(str) for Multi-geometries

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
This is a partial solution toward #846, as described in [this comment](https://github.com/geopandas/geopandas/issues/846#issuecomment-540248972)
This retains the index name of the "primary" data frame in the join.  For left and inner joins, this is the left data frame; for right joins, this is the right data frame.
Includes modifications to test fixtures to make sure that index names are passed consistently into the tests, and includes a specific test to ensure that the expected index name passes through to the result.
NOTE: in the case of right joins, the index name will now be `None` if the original right data frame's index name was `None`, instead of `index_right`.  This may be breaking change for anyone that relied on the name being `index_right` after this operation, especially if …
=> Retain primary index name in sjoin

doc/source/data_structures.rst, doc/source/reference.rst
Also added autodoc for `set_geometry` method as it was missing and needed for data sructure docs.
=> DOC: update data structure docs with links to classes/methods

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
Fixes #1074 
Fixed missing support for MultiIndex in `sjoin`.
~As a bonus, `sjoin` now returns the name of the original index instead of None, so the index is preserved intact. In master we have hard-coded `joined.index.name = None` even though we claim than index of left (or right) df is preserved. So this is a slight change of behaviour, but it seems to be fixing what was initially intended but never implemented.~ merged in #1150
=> BUG: spatial join error for MultiIndex

geopandas/tests/test_api.py
I just randomly came across todo I missed previously. `test_no_additional_imports` now updated for python 3 only.
=> CLN: Update test_no_additional_imports for py3

geopandas/plotting.py, geopandas/tests/test_plotting.py
Fixes #1178 
I have added `is_color_like` check before checking for list-like in `color` argument, so if we pass RGBA tuple it gets assigned directly to all geometries instead of expecting that it is a list.
=> BUG: Passing RGBA tuple to color parameter in .plot() throws error

geopandas/tests/test_api.py, geopandas/tests/test_array.py
Temporary fix for failing tests. conda defaults now comes with GEOS 3.8.0 which apparently no longer raises an error while doing `poly.is_simple` if poly is empty. In the [changelog](https://github.com/libgeos/geos/blob/master/NEWS), I assume the change is in `Improve general predicate, overlay, and buffer performance`. I am not sure how does this affect behaviour of overlay though.
=> TST: fix test_unary_predicates for GEOS 3.8

geopandas/_compat.py, geopandas/tests/test_api.py
While looking at the diff of https://github.com/geopandas/geopandas/pull/1201 (thanks @martinfleis !), I noticed that there was actually a type in the original test which made we were not testing matplotlib correctly.
=> TST: fix api test (no import) for matplotlib

geopandas/plotting.py, geopandas/tests/test_api.py, geopandas/tests/test_plotting.py
Passing array of tuples (aka list of lists), `np.take` in plotting flattens the array causing the error, reported in https://github.com/pysal/splot/issues/83. I thought that it is the same bug as #1178 but this one was slightly different. Both caused by changes in #1119 though. 
It should be fixed now, including tests.
_(there is so many options how to pass colors...)_
=> BUG: Passing array of RGBA tuples to color parameter in .plot() throws error

doc/environment.yml, examples/plotting_with_geoplot.py
The 0.4.0 release of `geoplot` made some breaking API changes. Specifically, the default colormap behavior has changed from categorical to continuous, and the `k` parameter has been replaced with direct use of `mapclassify`, which allows for finer-grained control.
This PR brings the `plotting_with_geoplot.py` example in the `geopandas` documentation inline with the new API signature.
=> Update geoplot documentation

doc/source/mapping.rst, geopandas/plotting.py, geopandas/tests/test_plotting.py
I have added support for missing data to the `plot_dataframe`. It does change the default behaviour because I believe that our current handling of missing data is wrong. 
It mirrors what QGIS does by default. Features with missing values are ignored as we do not know which style they should have. Currently we assign the first colour of cmap, but that is incorrect. You can set the style for missing values in newly introduced `missing_kwds`, including a label for the legend.
Examples of proposed behaviour are here https://gist.github.com/martinfleis/62d48a607d1cf4dc7d67841b3f3e8792.
I have not added tests and docs yet, as I want to make sure that we are okay with this change as it is not fully backward compatible (you get different plot). Unlike on master, mapclassify also ignores missing …
=> ENH: support for missing data plotting

geopandas/plotting.py
Just a tiny change to provide better error messages when optional plotting dependencies are missing. Sometimes people struggle to understand - https://stackoverflow.com/questions/58416539/geopandas-importerror-the-descartes-package-is-required-for-plotting-polygons-i.
=> DOC: informative errors for missing matplotlib and descartes

examples/cartopy_convert.py
I noticed there was something wrong with the last plot on this page: https://geopandas.readthedocs.io/en/latest/gallery/cartopy_convert.html 
I first thought it was not working, but it's actually just that the centroids are "hidden" behind the countries polygons. Which can be fixed with providing a "zorder" (not ideal a user needs to do this though)
=> DOC: specify zorder when combining cartopy and geopandas

geopandas/plotting.py, geopandas/tests/test_plotting.py, geopandas/tests/test_sindex.py
Added support for GeometryCollections and LinearRings in `.plot()` for both GeoSeries and GeoDataFrame. As you can see, it first decomposes GeometryCollections  in `plot_dataframe` and then explodes MultiGeometries in `plot_XX_collection` as it did till now. I was thinking about decomposing everything at once, but since we can get MultiGeometry inside GeometryCollection,  we would have to do the check twice anyway. This way is seems to be more understandable for future maintenance.
As I am using `_flatten_multi_geoms` to decompose both Multi and GeometryCollections now, I have slightly changed it, so we can select what to decompose. And as we already returned multiindex instead of actual values, I have removed color attribute.
LinearRings are easy, they can be plotted exactly the same way …
=> ENH: support GeometryCollection and LinearRing in plotting

geopandas/io/file.py, geopandas/io/tests/test_file.py, geopandas/io/tests/test_file_geom_types_drivers.py, geopandas/io/tests/test_infer_schema.py
Closes #1200 
This adds support of pandas Int64 (nullable integer dtype) to `infer_schema`, allowing GeoDataFrame with Int64 column to be saved to file.
I am closing #1200 which meant to carry the whole schema and reuse it on save, but this proved to be tricky as it is extremely sensitive to any change of gdf.
=> ENH: Support nullable integer data type in to_file

doc/source/mapping.rst
=> DOC: Add zorder example to docs

geopandas/tests/test_sindex.py
Closes #1221
The issue with rtree mentioned in #1221 and patched in #1227 has been fixed in https://github.com/Toblerity/rtree/pull/127. Reverting our tests back as it now fails again. 
@jorisvandenbossche do you want to check for 0.9.0 and 0.9.1 and use the patch for these versions only? I have removed it altogether as rtree now comes as 0.9.2.
=> TST: revert tests for sindex

geopandas/array.py
This should fix the failure on the pandas master build (due to https://github.com/pandas-dev/pandas/pull/30247)
=> TST: make dtype error message compatible with pandas

geopandas/tests/test_dissolve.py, geopandas/tests/test_geocode.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geom_methods.py, geopandas/tests/test_geoseries.py, geopandas/tests/test_pandas_methods.py, geopandas/tools/tests/test_sjoin.py
`pandas.util.testing` is deprecated and do not work anymore. (https://github.com/pandas-dev/pandas/pull/30620)
I have just changed imports to follow new path.
=> TST: pandas.util.testing -> pandas.testing

geopandas/array.py
Shapely have changed the behaviour of boolean representation of empty geometries (https://github.com/Toblerity/Shapely/pull/812) which broke our `_binary_geo`. I have made the condition used there more explicit to avoid the issue.
=> BUG: reflect changes in bool(geom) in shapely 1.7

geopandas/geoseries.py, geopandas/tests/test_geoseries.py
Fixes #1216 
Having GeoSeries with MultiIndex, GeoSeries.reset_index() returned pandas DataFrame not GeoDataFrame as I would expect in such a case.
I have used `GeoSeries._constructor_expanddim` as @jorisvandenbossche mentioned. As a result, `to_frame` also returns GeoDataFrame if called on GeoSeries which makes sense to me (it was a DataFrame).
=> BUG: GeoSeries.reset_index() gives DataFrame not GeoDataFrame

geopandas/geodataframe.py, geopandas/io/file.py
#1231 and #1240 are caused by wrong encoding detection. I have added a note to docs mentioning that it may happen and how to fix it.
Closes #1231
=> DOC: explain encoding in to_file, read_file

doc/source/_static/custom.css
xref https://github.com/geopandas/geopandas/pull/1297#issuecomment-586748219.
There is some discussion in https://github.com/numpy/numpydoc/issues/215 about this. TL;DR: sphinx 2.0 changed the way they format field lists in the Parameters section in the resulting html, which broke how many themes rendered docstrings. 
The numpydoc issues has several cross links from projects dealing with this. Here, I copied the mimimal css from sphinx' basic.css to fix the most pressing display issue (the fact that there is no space between the parameter and its type, see eg https://geopandas.readthedocs.io/en/v0.6.0/reference.html#geopandas.GeoSeries.contains)
The relevant (unsolved) issue on rtd's side: https://github.com/readthedocs/sphinx_rtd_theme/issues/746
=> DOC: fix docstring styling with sphinx > 2

doc/source/io.rst
As discussed in #1286, the fact that GeoDataFrame can contain various objects, while standard GIS formats can't, can be confusing on using `to_file()`. I have added a note to the documentation explaining the issue. 
Closes #1286
=> DOC: Add note on field types to io

doc/source/conf.py, doc/source/projections.rst, geopandas/base.py, geopandas/geodataframe.py, geopandas/geoseries.py
Also, fixed some cases where an extra space between the parameter and the `:` were causing issues in the docs.
Note: I didn't run black on the `conf.py` in the `doc` folder as it would have redone the entire file and cluttered up the commit.
=> DOC: Fix intersphinx mapping with pyproj docs

geopandas/io/file.py, geopandas/io/tests/test_file.py
Closes https://github.com/geopandas/geopandas/issues/1004
A simple test for appending to a Shapefile is included. It shouldn't be necessary to test for non-matching schemas when appending, because [Fiona does that](https://fiona.readthedocs.io/en/latest/manual.html#appending-data-to-existing-files):
> The record you write must match the file’s schema. You’ll get a ValueError if it doesn’t.
It doesn't look like there's a more user-friendly list of which formats support appending than in the code: https://github.com/Toblerity/Fiona/blob/master/fiona/drvsupport.py
=> ENH: Allow appending from to_file

geopandas/tools/clip.py, geopandas/tools/tests/test_clip.py
Closes #1308 
Minor fix for clip to ensure that empty GeoSeries is returned if mask is not overlapping with original GeoSeries. Now it raises error as we expect GeoDataFrame there.
=> BUG: clip GeoSeries by non-overlapping mask raises error

CODE_OF_CONDUCT.md, doc/source/code_of_conduct.rst, doc/source/index.rst
Added Code of Conduct for GeoPandas Project based on [Project Jupyter's version](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md) as agreed in #978. You can see the changes by comparing with the first commit on this branch containing the original text.
We have to do couple of things:
Closes #978
=> Add a Code of Conduct

geopandas/array.py, geopandas/tests/test_array.py
Closes #1310 
`total_bounds` should ignore missing and empty geometries as they do not have any spatial extent and return extent of existing geometries instead of returning array of NaNs. See #1310 for details. As `total_bounds` is a property, there is no way to give a choice to filter out missing geoms, so I'd say the correct way to handle it is ignoring them. Moreover, it was implemented like that in the beginning, than changed during refactoring, I'd say unintentionally as there is no discussion on the topic.
=> BUG: ignore NaNs in total_bounds if there is geometry 

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
Fixes #1307, fixes #1315 .
This allows for sjoin to succeed when one of the joined geodataframes cannot generate a spatial index (either due to an empty GDF, or due to all empty rows).
=> BUG: Fix sjoin on empty column

.travis.yml, geopandas/tests/test_pandas_methods.py
Fixing one of the issues with testing with pandas master after pandas started to raise different error message.
At the same time, I am moving DEV CI environment to allowed failures on Travis, so we don't get red CI for all our PRs due to changes in pandas master which broke unrelated things.
=> CI: allow failures on DEV CI

doc/source/reference.rst
Added missing methods and functions to reference API. This was initially part of #1254, but I am splitting it as this can be merged immediately.  
Closes #1052, closes #805
=> DOC: add missing methods to reference

geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
If geodataframe has no geometry column set, `iterfeatures()` will fail with no indication why that happened. I am just adding a tiny check to raise an informative error if there is no set geometry.
+ one minor type found along the way.
=> ENH: informative error in iterfeatures if no geometry set

geopandas/geodataframe.py, geopandas/testing.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_testing.py
Closes #1192 
When accessing geometry dtype column, geopandas currently returns GeoSeries only for active geometry. This PR checks for GeometryDtype and returns GeoSeries for all columns containing GeometryArray.
```
df = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres')) 
df['centroids'] = df.geometry.centroid   
df.dtypes   
pop_est          int64
continent       object
name            object
iso_a3          object
gdp_md_est     float64
geometry      geometry
centroids     geometry
dtype: object
type(df['geometry']) 
geopandas.geoseries.GeoSeries
type(df['centroids']) 
geopandas.geoseries.GeoSeries
```
=> ENH: return GeoSeries when accessing GeometryDtype columns

geopandas/_compat.py
Quick fix, warnings is not being imported but is used on [line 73/74](https://github.com/geopandas/geopandas/blob/5d1181af6bcca88351d84bb63fc0fbe0e32ce055/geopandas/_compat.py#L73).
=> BUG: Fix warning import

doc/source/install.rst
`six` is no longer a dependency as we do not support python 2 anymore. It is still listed in docs.
=> DOC: remove six as a depenency

doc/source/projections.rst, geopandas/array.py, geopandas/base.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/testing.py, geopandas/tests/test_crs.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_testing.py, geopandas/tools/overlay.py
Closes #1193, closes #1340, closes #1362, closes #1366
This moves CRS attribute from GeoDataFrame and GeoSeries to GemetryArray level. It allows us to have multiple geometry columns with different CRS and also making easy access to CRS for array-level methods like `area` or `distance` to implement those for geographic projections using `pyproj.Geod`.
POC at the moment, but everything seems to be working. Few conditions deserve a bit of simplification, I tried to make it explicit so far to cover all possibilities.
I'll post more information and consequences of this (plus few points for discussion) later, I just want to see CI now. 
~Requires #1336 (code of that is included here to make it work for now).~ (merged)
todo:
=> ENH: move CRS to GeometryArray level

geopandas/geodataframe.py, geopandas/tests/test_crs.py
Closes #1374 
In case of setting geometry column using `None`, we should create either empty GeometryArray as in the following case of GeometryArray of `None` with crs inherited from df.
```py
gdf = gpd.GeoDataFrame()
gdf.crs = 4326
gdf['geometry'] = None
```
On master, `gdf.geometry` returns Series, this PR returns GeoSeries with CRS.
=> BUG: CRS not propagated to GeometryArray based on scalar

geopandas/geodataframe.py, geopandas/tests/test_geom_methods.py
Fixes #81
Set operators currently worked on GeoSeries but not on GeoDataFrame. 
```py
a = GeoSeries(...)
b = GeoDataFrame(...)
a.intersection(b)  # Okay
b.intersection(a)  # Okay
a & b  # Okay
b & a # Error
```
GeoDataFrame now supports operators as well using its geometry column.
=> BUG: Set operators are inconsistently handled

geopandas/tools/tests/test_sjoin.py
Closes #1364 
Fix tests for `sjoin(... how='right', op='within')` using pandas master, which now returns gdf of the same order as the original one. This behaviour is essentially a fix of current incorrect result.
I have changed only tests to sort expected df. As this is a very minor issue which is now fixed by pandas, I don't think we have to make fix on our side to make sure that the behaviour is the same with older pandas.
=> TST: fix sjoin test for pandas master

geopandas/array.py, geopandas/base.py, geopandas/testing.py, geopandas/tests/test_array.py, geopandas/tests/test_crs.py, geopandas/tests/test_testing.py
Closes #1369 
Move check for CRS mismatch for binary methods to GeometryArray level from GeoSeries level as discussed in #1339.
=> ENH: Move CRS mismatch check to GeometryArray level

asv.conf.json
Pygeos is in Conda Forge, so that needs to be added.
I also added running with and without Pygoes, which as of right now is a very useful benchmark.
=> BENCH: Fix asv config for pygeos

geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tests/test_geom_methods.py
Deprecating set operators ('&', '|', '^', and '-'). To be removed in v0.9.
ref #1255
=> DEPR: add DeprecationWarning to set operators ('&', '|', '^', and '-')

benchmarks/sindex.py, geopandas/_compat.py, geopandas/base.py, geopandas/sindex.py, geopandas/tests/test_overlay.py, geopandas/tests/test_sindex.py, geopandas/tools/tests/test_sjoin.py
Followup to #1154
Implements PyGEOS' STRTree with a compatibility wrapper. Also reworks compatibility flags to allow dynamic switching from PyGEOS to rtree.
My proposal would be to have this in for ~1 minor version (or maybe until 1.0) and then drop rtree in favor of PyGEOS . We're still going to need the compatibility layer to convert GeoSeries to arrays and such, but maybe at that point support for tuples of bounds as well as the `intersection` and `contains` methods can be dropped.
Failing overlay tests are due to #1337 / #1338.
Edit: added a hacky fix for `TestPygeosWraper`. Will think of a better way.
=> ENH: add PyGEOS spatial index

doc/source/install.rst, geopandas/tools/sjoin.py
* Binary wheels for shapely have been available since version 1.7.0
* Correction to `sjoin` default for `op`
=> DOC: corrections / updates

geopandas/__init__.py, geopandas/geodataframe.py, geopandas/io/file.py, geopandas/io/sql.py, geopandas/io/tests/test_file.py, geopandas/io/tests/test_sql.py
Making our internal io functions, which are then linked to GeoDataFrame as methods, internal. 
See https://github.com/geopandas/geopandas/pull/1406#issuecomment-623987622
> @jorisvandenbossche Now, you somewhat have the same issue with `read_file`, `read_postgis` etc as well, as we don't want people to use that from `geopandas.io.sql`..., but rather from the top-level. But at least there it is the exact same function.
Since these are the same things, we can keep it as it is now. If we change them, then we can switch to private with deprecation later.
=> API: privacy of geopandas.io

geopandas/tests/test_extension_array.py
Pandas added `test_value_counts_with_normalize` to ExtensionArray tests. Skipping as we do not support value_counts on geometry.
=> TST: skip test_value_counts_with_normalize

geopandas/io/sql.py, geopandas/io/tests/test_sql.py
Closes #1414 
Ensures that writing to PostGIS table works when `if_exists="append"` and table does not exist. 
Changes:
- Conduct the sql-query to retrieve the SRID of a table only if table exists. 
- add test for the above, as well as, testing that appending to table with different CRS throws an error.
=> FIX: Ensure writing to PostGIS table works when "appending" and table does not exist yet

geopandas/array.py
Adapt `from_shapely` to allow single geometry on input. That is what pandas master `TestConstructors.test_series_constructor_scalar_with_index` tries to do and fails.
=> TST: fix test_series_constructor_scalar_with_index

.travis.yml, benchmarks/sindex.py, geopandas/sindex.py, geopandas/tests/test_sindex.py
The next step in integration of `pygeos.strtree`.
A couple of notes:
1. I included sorting for now, but am happy to remove it if it adds too much complexity.
2. I included support for other predicates (and tests, it works) but will be happy to remove it for now if we want to do that separately.
A general comment:
I think it would be cool to have a spatial index abstract base class that lives inside of `sindex.py` that starts to sketch out what API we expect for spatial indexes. Any thoughts on that are welcome.
CCing @jorisvandenbossche  @martinfleis  @brendan-ward
=> ENH: Add query and query_bulk to sindex

doc/source/reference.rst, geopandas/base.py
Fix for https://github.com/geopandas/geopandas/issues/1358
The reference for `.. automethod:: geopandas.GeoSeries.overlaps` was missing on doc/source/reference.rst file.
Also, I've added the Parameters description to the function declaration docstring in geopandas/base.py
=> DOC: Adding geopandas.Series overlaps method in documentation

.travis.yml, ci/travis/38-no-optional-deps.yaml, geopandas/tests/test_overlay.py, geopandas/tests/test_sindex.py, geopandas/tools/tests/test_clip.py
To ensure we don't by accident add a hard requirement (and this way can also test error messages for an optional dependency not being present)
=> CI: add a build without optional dependencies

geopandas/_compat.py, geopandas/tests/test_pandas_methods.py
Pandas has changed behaviour of `groupby` on ExtensionArray, which in our case returns GeoSeries if the function is applied to geometry. From my perspective, this is a bug fix on pandas side.
I just fixed our tests which were failing on this using pandas master.
=> TST: GroupBy change on pandas master

geopandas/sindex.py, geopandas/tests/test_sindex.py
Currently, we are removing empty geometries before creating the tree. This causes the indexing to be off it there is an empty geometry anywhere but the last index (the current tests only check a single empty geometry, i.e. the last index). I fixed this and added a test.
~Where things get a tad more complicated is dealing with empty geometries in calculating the "size" of the spatial index. Empty geometries are not inserted into the tree, but pygeos still counts them towards the size of `pygeos.strtree.STRtree`. I think this behavior makes more sense than passing in an array of size 100 with 1 empty geometry and getting back a spatial index size of 99 (which is what rtree is currently doing). Thus I modified the `size` property in the rtree wrapper to return the size of the geometry array, …
=> BUG: Fix PyGEOSSTRTreeIndex indexing with scattered empty geometries.

geopandas/tests/test_overlay.py, geopandas/tools/overlay.py
PR for query_bulk in overlay, crossfref #1404 
Benchmarks:
| before      | after      | ratio | test                                                   | pygeos installed? |
|-------------|------------|-------|--------------------------------------------------------|-------------------|
| 328±80ms    | 266±30ms   | ~0.81 | overlay.Countries.time_overlay('difference')           | Y                 |
| 327±80ms    | 247±80ms   | ~0.76 | overlay.Countries.time_overlay('difference')           | N                 |
| 724±20ms    | 731±70ms   | 1.01  | overlay.Countries.time_overlay('identity')             | Y                 |
| 805±20ms    | 988±200ms  | ~1.23 | overlay.Countries.time_overlay('identity')             | N                 |
| 181±20ms    | 203±30ms   | ~1.12 | …
=> ENH: Implement sindex.query_bulk in overlay

geopandas/io/tests/test_parquet.py
To test whether this is now solved (cfr https://github.com/conda-forge/pyarrow-feedstock/issues/104)
=> CI: remove skip for Parquet tests on AppVeyor

geopandas/array.py, geopandas/tests/test_array.py
Closes #1335
Added support for `pandas.NA` as a missing value in our `_isna` function.
=> ENH: support pd.NA value as missing value

geopandas/geodataframe.py, geopandas/tests/test_geom_methods.py
Fixes #1393 
If there is a column `'level_1'` present in GeoDataFrame, it will fail with `NotImplementedError`. We are using automatically created `level_1` column within explode, so I am renaming potentially conflicting column to `'__level_1'` and then back.
=> BUG: explode() fails if 'level_1' is in columns

geopandas/base.py, geopandas/io/sql.py, geopandas/tools/_show_versions.py
Numpydoc requires the exact correct name ("Examples"), otherwise it doesn't show up, eg https://geopandas.readthedocs.io/en/latest/reference/geopandas.read_postgis.html
=> DOC: correct Examples rubric titles

examples/plotting_basemap_background.py
Update documentation link to point to `contextily` in the `geopandas` organisation.
=> DOC: Link to the canonical geopandas/contextily repo

geopandas/sindex.py, geopandas/tests/test_sindex.py
As discussed in #1439, I think it would be best to deprecate the `objects` parameter. This makes a warning for using it. Hopefully this will be a good first step in that direction.
=> Warn about deprecation of sindex.intersection objects parameter

benchmarks/sjoin.py, doc/source/mergingdata.rst, geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
This is the next step for #1404.
Benchmarks:
| before <master> | after <sjoin-query-bulk> | ratio | test                     | pygeos installed |
|-----------------|--------------------------|-------|--------------------------|------------------|
| 9.51±0.1s       | 178±1ms                  | ~0.02 | time_sjoin('contains')   | Y                |
| 8.40±0.4s       | 7.25±0.02s               | ~0.86 | time_sjoin('contains')   | N                |
| 9.09±0.06s      | 592±9ms                  | 0.07  | time_sjoin('intersects') | Y                |
| 7.80±0.01s      | 11.0±0.1s                | ~1.41 | time_sjoin('intersects') | N                |
| 1.14±0.02s      | 585±4ms                  | 0.51  | time_sjoin('within')     | Y                |
| 7.94±0.2s       | 11.5±0.06s               | …
=> ENH: use query_bulk in sjoin

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
Small follow-up on https://github.com/geopandas/geopandas/pull/1428 that I noticed when running the tests:
* Don't show our own deprecation warning for empty sindex when from inside sjoin
* Fix some warnings about CRS mismatch coming from the tests
=> CLN: clean-up warning from sjoin and in tests

geopandas/tools/overlay.py
Pass `suffixes` in pandas merge as a tuple.
ref https://github.com/geopandas/geopandas/issues/1432#issuecomment-643599958
=> BUG: fix suffix as a tuple in overlay

geopandas/plotting.py, geopandas/tests/test_plotting.py
Implementation of #1121 and the first utilisation of brand new pyproj.CRS 🎉.
`.plot()` now automatically determines whether GeoSeries (or GeoDataFrame) is in geographic or projected CRS and calculates aspect for geographic using `1/cos(s_y * pi/180)` with s_y the y coordinate of the mean of y-bounds of GeoSeries. This leads to better representation of the actual shapes than current hard-coded 'equal' aspect. It is just a minor visual thing, but note that it changes the default behaviour. Implementation is ported from R package `sf`.
You can control the behaviour using new `set_aspect` (matching matplotlib `ax.set_aspect`) keyword, which can be set to `'auto'` (default new behaviour explained above), 'equal' (current) or float which is then passed to `ax.set_aspect()`. Terminology is the …
=> ENH: scaling y-axis for plots in geographic CRS

geopandas/plotting.py, geopandas/tests/test_plotting.py
xref https://github.com/geopandas/geopandas/pull/1173, closes #1158
* This ensures to respect the actual `categories` if a categorical column is specified for `column` (so both all its values (not only the ones present in the data) and its order)
* At the same times cleans up a bit the current code to determine the categories and the integer `values` using pandas' Categorical
cc @martinfleis
=> ENH: honor categories of categorical column in df.plot()

doc/source/io.rst
We need to expand those docs (certainly the part about databases), but this PR is doing something minimal: add a section about Parquet/Feather, and move the mention of read_postgis/to_postgis into its own section (for the rest are mainly newline changes by wrapping the existing text)
=> DOC: add sections for PostGIS and Parquet/Feather to io.rst docs

geopandas/io/sql.py
Filter warning about geometry column not holding geometries when writing to postgis, as the dtype conversion is intentional.
Fixes #1497
=> Filter warning about geometry column not holding geometries when writing to postgis

geopandas/tests/test_extension_array.py
Some new tests were added in pandas master, and we don't support argmin/argmax methods (we don't support min/max sorting related methods generally).
=> TST: skip argmin/argmax extension array tests

geopandas/io/tests/test_arrow.py
Resolves #1536
This removes the test of reading multiple columns from parquet.  On `pyarrow<=0.17` requesting multiple columns was silently ignored and only unique columns were read.  On `pyarrow>=1.0` it raises a `ValueError`.
In either case, geopandas should propagate the behavior from the associated pyarrow version; there is no need for a test of this behavior here.
=> Remove failing test of duplicate columns on read of parquet

doc/source/contributing.rst
Following on from pull request discussion in #1425
> "... read through pandas contribution guide - should have done before - and found commit message convention that geopandas uses which could copy into geopandas' contribution guide if desired"
I believe (though may be mistaken!) that geopandas follows the pandas commit message conventions so I've just copied across 'em across to the end of the `contributing to geopandas` docs as I was a little lost (for more reasons than this one!) during #1425
=> DOC: Copy pandas commit message conventions

ci/travis/36-pd025.yaml
Closes #1542
Pin mapclassify coming from pip to 2.2.0. Newer requires pandas 1.0.
=> CI: pin mapclassify

geopandas/_compat.py, geopandas/tests/test_pandas_methods.py
Closes #1543 
Closes #1541 
Fixed condition to check for pandas 1.1.0 version and added `ValueError` as an option for `idxmax`.
=> TST: Fix CI for pandas 1.1.0

geopandas/tools/overlay.py
While trying to figure out an issue with an overlay returning surprising results, I realized that the `make_valid` argument in overlay wasn't actually used anywhere. I can imagine some cases where there would be some utility in that, but let's remove it in the meantime. A question though: do we need to provide a deprecation warning first for removing an argument that hasn't actually been doing anything (and a quick search through history makes it unclear whether it has ever done anything, but I'm not sure
about that).
=> CLN: Remove unused make_valid argument

geopandas/tools/clip.py, geopandas/tools/tests/test_clip.py
The geodataframe that resulsts from a clipping operations should
retain the geometry column from the input geodataframe, rather than
using the default geom col name "geometry". Resolves #1563
=> BUG: Set clipped gdf geometry name based on input

benchmarks/sindex.py, geopandas/array.py, geopandas/base.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/sindex.py, geopandas/tests/test_sindex.py, geopandas/tools/sjoin.py
Crossref #1439.
This does the following (roughly steps 1 & 2 in #1439):
1. Drop the `objects` parameter completely.
2. Move the management of the spatial index to `GeometryArray`.
I don't expect this to be merged until after 0.8.0, but I'm submitting for some preliminary feedback.
=> REF: Move sindex to GeometryArray

geopandas/plotting.py, geopandas/tests/test_plotting.py
For issue #1489. Now when `aspect=None`, the aspect won't be changed. Also, before this, `aspect="equal"` actually does nothing, which means it assumes that the original aspect of `ax` is always `equal`. I suppose this is probably mostly right, better to be explicit.
=> ENH: Add `aspect=None` option to plotting, to keep the original aspect.

geopandas/plotting.py
Resolves #1555. In cases where legend_kwds was being passed, we were
updating legend_kwds with the cax/ax passed in on that function call.
Within a loop over multiple axes, this meant placing all colorbars on
the first placed axis. This just creates a copy of legend_kwds, when
placed, so we don't update in place.
=> BUG: Copy legend_kwds so we don't update inplace

doc/source/docs/user_guide/projections.rst
I originally added an function `def is_utm(crs)` in the example as well based on [CRS.utm_zone](https://github.com/pyproj4/pyproj/blob/9389f9db058283679ca9f672f6f8798817ad753a/pyproj/crs/crs.py#L979-L990), but I thought it was pretty complex and probably better to just do this. Thoughts?
=> DOC: Use the CRS.utm_zone property to identify UTM CRS

geopandas/geodataframe.py
Simple fix to correct a little bit of docstring that I saw during usage.
=> Correct set_geometry docstring for ``drop`` default.

ci/travis/36-minimal.yaml, ci/travis/36-pd025.yaml, ci/travis/37-dev.yaml, ci/travis/37-latest-conda-forge.yaml, ci/travis/37-latest-defaults.yaml, ci/travis/38-latest-conda-forge.yaml, doc/source/docs/user_guide/io.rst, geopandas/io/file.py, geopandas/io/tests/test_file.py
Fixes #1531.
This allows for more general file-like objects to be used than just those deriving from `TextIOBase`.
It also attempts to infer if a local file should be treated as a zip file and automatically adds a `zip://` scheme to the path. This is so that there is no longer a difference in how local and remote zipped files are handled.
~~The part of #1531 that it does not cover is the difference between how compound URLs are handled with respect to remote data. GeoPandas currently does not use the vsicurl OGR virtual filesystem, but instead downloads the data and feeds the bytes to fiona. I'm not sure which is better at the moment.~~
~~TODO: write tests~~
=> ENH: Allow for more general file-like objects to be used when opening files.

geopandas/io/tests/test_file.py
Closes #1606
Due to adding `a` to the `GeoJSON` driver, the GeoJSON test was no longer skipped (https://github.com/Toblerity/Fiona/commit/79e1b5a2caf8cdcf525b6ee255215e0ab12dc8fc). It failed because one of the geometries was not exactly the same. This addresses the issue.
=> TST: Use less precise option for testing appending to file

geopandas/sindex.py
Address points 2 & 3 of #1529. Point 1 requires unrelated changes to `Base` to check if it has a geometry column, then if that column has a spatial index generated or not.
=> ENH: speed up emptiness and size checks for rtree

.github/workflows/tests.yaml
On Travis we had a cron schedule to run tests daily, to catch potential issues. Setting the same on GHA.
=> CI: schedule daily tests

geopandas/_vectorized.py, geopandas/tests/test_array.py
Fixes #1615 
Correctly assess `is_ring` based on geometry type. Directly for LineString and LinearRing, as the exterior for Polygon. No other geometry can return True by definition.
=> BUG: is_ring returns False even for all LineStrings and LinearRings

codecov.yml
Adding `codecov.yml` to avoid unintentional failure of the coverage check. There are common cases where codecov reports 100% coverage of the patch, but a decrease of coverage of the project (usually by 0.X%), causing check failure. We now require at least 95% coverage and allow 0.2% drop.
I still don't know why a bot does not comment, but it could be fixable via reconnecting Codecov integration in settings. cc @jorisvandenbossche 
Closes #1628
=> CI: codecov yml

geopandas/geoseries.py, geopandas/tests/test_pandas_methods.py
When I added `GeoSeries.apply` in #1478, I apparently forgot one keyword that the pandas version has
To fix https://github.com/jsignell/dask-geopandas/issues/18,
=> BUG: fix overridden GeoSeries.apply method to accept convert_dtype keyword

geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
Fixes #1593
Return a more meaningful error when an existing column is passed in `rename_geometry` 
added some tests for the same
=> Check for duplicate column name in rename_geometry

ci/travis/36-pd025.yaml, ci/travis/37-latest-defaults.yaml
Keeping pygeos installed from github master only in dev environment. The recent change on pygeos master killed our CI.
=> CI: keep pygeos master in dev environment only

geopandas/_vectorized.py
Fixes #1640
PyGEOS now returns -1 for missing geometry on geom_type check. Adding it to our mapping. Since it is fixing a bunch of failing tests, I guess no new tests are needed.
=> BUG: fix geom types codes for pygeos master

geopandas/_vectorized.py
Continuation of #1641. Pygeos now put `-1` back, just as `MISSING`. This should be backward compatible.
ref https://github.com/pygeos/pygeos/pull/204
=> BUG: fix pygeos geom types mapping

.github/workflows/tests.yaml, ci/travis/38-latest-conda-forge.yaml, geopandas/array.py, geopandas/base.py, geopandas/conftest.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/io/file.py, geopandas/io/sql.py, geopandas/tests/test_api.py, geopandas/tools/clip.py, geopandas/tools/geocoding.py
This PR adds one step to CI, checking docstring examples using `pytest` as suggested in #1617. That involves a bit more changes than I initially expected, notably required import of `pytest` on top of every file with examples to avoid the necessity to do `import geopandas` in every single example.
I have added one step to CI checking only docstrings, using pytest plugin `pytest-doctestplus` which allows checking docstrings only. It is run in a single environment, as those with missing dependencies are failing (naturally).
You don't have to check the actual docstrings as changes included in this PR are minimal to make doctest pass.
=> DOC/CI: enable doctest

geopandas/base.py, geopandas/tests/test_geom_methods.py
`GeoSeries.explode()` does not preserve CRS. Fixed.
To reproduce a bug:
```python
nybb = gpd.read_file(gpd.datasets.get_path('nybb'))
nybb.geometry.explode().crs
```
=> REGR: CRS lost in GeoSeries.explode()

geopandas/_compat.py, geopandas/_vectorized.py, geopandas/array.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/plotting.py, geopandas/tests/test_geodataframe.py
I had hoped this being less involved, but apparently, even with our workaround of 
```
out = np.empty(.., dtype=object)
out[:] = [...]
```
to avoid that numpy expands Multi-part geometries upon array construction, the above snippet *still* triggers the warning about Multi-part geometries no longer being iterable (not really sure why, since numpy doesn't actually iterate through them in that case to create the result, but internally in numpy it still happens). 
So therefore, I added a context manager around all those cases where we create a ndarray in this way, and for shapely 1.8 it supresses this warning, otherwise it is a no-op context manager.
=> Compatibility with Shapely 1.8 deprecation warnings (iteration)

geopandas/_compat.py, geopandas/_vectorized.py, geopandas/plotting.py
Follow-up on https://github.com/geopandas/geopandas/pull/1659
This further fixes warnings about trying to convert a geometry to an array (`np.array(geom)` instead of `np.array(geom.coords)`). This again mostly happens under the hood in numpy, so adding it to the context manager I added in #1659
=> Compatibility with Shapely 1.8 deprecation warnings (array interface, asShape)

geopandas/plotting.py, geopandas/tests/test_plotting.py
This fixes #1634.
If categories are passed as a Series, call `.reindex()` so the index matches the data index when plotting.
=> BUG: categories passed as a series are not properly sorted

.github/ISSUE_TEMPLATE/installation_issue.md
xref https://github.com/geopandas/geopandas/issues/982#issuecomment-720506732
> b/c conda-forge issues on geopandas installation are quite common, maybe we should add the feedstock link and a message on the issue template to guide people there.
=> GH: link geopandas-feedstock for conda-forge issue

.github/workflows/tests.yaml, geopandas/plotting.py, geopandas/tests/test_plotting.py
The dev build was failing related to matplotlib, which started to support array-like argument for the `alpha` style keyword (see https://matplotlib.org/devdocs/users/next_whats_new/alpha_array.html), but which we explicitly tested that it raised an error.
Also enabling the dev github actions build to be visible if there are failures, since we currently don't have any (we can always skip it again if there turn up failures we can't directly fix).
=> TST/ENH: support array-like alpha + fix plotting tests for matplotlib dev version

.github/workflows/tests.yaml
Tests are down due to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This is an attempt to fix that.
=> CI: fix conda setup

geopandas/array.py
Closes #1647 
The lines I've added suppress the warning when calling both `__repr__` and `total_bounds`.
This is not exactly the fix what was asked in the issue, but I have noticed that `total_bounds` could already return silently nans before this edit.
Maybe a warning message about returning nans can be printed for both cases ?
=> Suppress warning when calling repr of empty GeoSeries. Fixes #1647

geopandas/geodataframe.py, geopandas/tests/test_dissolve.py
Resolves #1380
If no column is passed to `GeoDataFrame.dissolve()`, whole GeoDataFrame is considered a single group and all geometries are dissolved to a single one. It is done using a `__dummy` column. Since `aggfunc` needs to be passed to `groupby`, we can't create gdf directly using `unary_union` and `agg` (e.g. `DataFrame.agg('first)` and `DataFrame.groupby.agg('first)` are different methods).
=> ENH: allow GeoDataFrame.dissolve(by=None)

ci/envs/38-latest-conda-forge.yaml, doc/source/docs/reference/geodataframe.rst, doc/source/docs/reference/geoseries.rst, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geoseries.py
Closes #1528
Depends on release of pyproj 3+, but figured it wouldn't hurt to get the review process started.
=> ENH: Add estimate_utm_crs method to GeoSeries and GeoDataFrame

.github/workflows/tests.yaml, ci/envs/39-latest-conda-forge.yaml
Adding an environment with Python 3.9 to be tested on ubuntu.
=> CI: add Python3.9 to CI matrix

doc/source/docs/user_guide/set_operations.rst
Reading the docs, trying to learn the tool, I noticed the typo in the spelling of South America.
Forgive the extremely pedantic PR!
=> DOC: Fixing a typo in "South America"

doc/source/docs/reference/geoseries.rst, geopandas/base.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tests/test_geom_methods.py
As in the title, this PR is a work in progress. Black and flake8 have not yet been run. I'll run them when the changes are deemed satisfactory.
I have given no special attention to the onoing "MultiIndex vs. Duplicate Index" debate, just added a snippet to naively forward the inputs to pandas if the geom col is not None and not the geometry column name.
However this could raise another interesting question - I often have two geometry-type columns in a geodataframe for alternate representations, and sort of "activate and deactivate" them as I please. Maybe it's not the best practice but nothing stops me from doing it. If the data type of the column is a shapely geometry, but is not the "active" geometry column, should it be geometrically or non-geometrically exploded?
Related to …
=> ENH: fallback to DataFrame.explode() when the specified column is not the geometry column

geopandas/array.py, geopandas/io/tests/test_pickle.py
Closes #1745
Closes #1746
Moving conditions into `__setstate__` and `__getstate__` to make sure it reacts to `geopandas.options.use_pygeos = False`.
_edit:_ I have also included a patch for #1746 now. Since `pygeos.STRtree` cannot be pickled now, it is ignored during pickling and `_sindex` is set to `None` during un-pickling.
=> REGR: fix pickle issues

doc/source/docs/user_guide/projections.rst
There is a small typo in doc/source/docs/user_guide/projections.rst.
Should read `recommend` rather than `recommenend`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> DOC: fix simple typo, recommenend -> recommend

geopandas/array.py, geopandas/tests/test_array.py, geopandas/tests/test_extension_array.py
This should fix the CI failure with pandas master. 
I have fixed an expansion of scalar geometry which was mistakenly seen as a list and reimplemented `__contains__` following pandas example with a difference of switching the check (we have `(self == item).any()` whilst pandas `(item == self).any()`). To be honest, I am not sure how come that pandas implementation works with the switched order :).
pandas implementation for a reference:
https://github.com/pandas-dev/pandas/blob/6e1802312b019a061209f3bd75b12a039457f14e/pandas/core/arrays/base.py#L358-L373
=> BUG: implement custom __contains__ for GeometryArray

doc/source/docs/user_guide/geometric_manipulations.rst
There are apparently workarounds to handle this, but they aren't pretty: https://stackoverflow.com/questions/10669099/italicize-text-containing-a-link
@martinfleis I see you have some other documentation PRs, so you may want to take a quick look at this.
=> DOC: italics can't be nested in links

geopandas/tests/test_extension_array.py
Skipping new extension array test `test_argreduce_series` since we do not support sorting in `GeometryArray`. 
This should make CI green again.
=> TST: skip test_argreduce_series

geopandas/geodataframe.py, geopandas/io/sql.py, geopandas/io/tests/test_sql.py
The `gdf.to_postgis` method/helpers were calling `.begin()`, which is not compatible between `Engine`s and `Connection`s (unfortunately...). This adds a little extra logic to ensure we retrieve the right value. This supports wrapping `to_postgis` calls within a larger transaction/connection.
I also replaced the (to be [deprecated in 1.14](https://github.com/sqlalchemy/sqlalchemy/blob/cea03be/doc/build/changelog/unreleased_14/4755.rst)) `run_callable` use. Even though `Connectable.has_table` method will also be deprecated, the `dialect` one doesn't seem to be.
Hmm, test failures seem unrelated(?)
=> ENH: support both sqlalchemy Connection and Engine in to_postgis

geopandas/tests/test_extension_array.py
Skipping another pandas ExtensionArray test not supported on geometries.
xref  (pandas-dev/pandas#38733)
=> TST: skip pandas EA test

geopandas/io/file.py, geopandas/tests/test_api.py, geopandas/tests/test_geodataframe.py
A first possible step towards https://github.com/geopandas/geopandas/issues/1313
I did this a while ago, so thought to at least open it as a PR. 
While this already works fine as is, I think the main question is if we actually want to test this / allow to run our tests without fiona (to make it a proper optional dependency). Because given how *many* of our tests use fiona to read in a test dataset, it might be a bit invasive to change this.
=> DEP: lazily import fiona only when used (to make it possible to not have it installed)

.github/workflows/release_to_pypi.yml
Adding Github Actions workflow which pushes tagged release to PyPI automatically.
@jorisvandenbossche to make this work, I need you to add [PyPI API token](https://pypi.org/help/#apitoken) to `secrets` as `PYPI_PASSWORD`.
The release checklist would then be following (I'll update wiki once we merge):
<details>
Releasing:
* Make an empty release commit: ``git commit --allow-empty -m 'RLS: v0.2.1'``
* Tag the commit using an annotated tag. ``git tag -a v0.2.1 -m "Version 0.2.1"``
* Push the RLS commit ``git push upstream master``
* Also push the tag! ``git push upstream --tags ``
* Create sdist: ``python setup.py sdist``
* Make github release (ensure to add the sdist as asset)
Packaging:
* update on conda-forge should be done automatically once the github release is made
* update on PyPI …
=> GHA: Automatic release to GitHub and PyPI

doc/source/conf.py
The copyright states 2013-2019, but the project looks like it's still being updated as of 2021. This PR changes the end copyright date to 2021.
=> DOC: Update copyright year

doc/source/getting_started/install.rst, geopandas/_compat.py
This should avoid issues like https://github.com/geopandas/geopandas/issues/1778 where having an older version of pygeos installed causes geopandas to stop working (if you explicitly set the option to use pygeos, it will still give an error that the version if too old).
I didn't check what version we actually require, but 0.6 is certainly too old, since `query_bulk` was only added in 0.7. And 0.8 is already a few months old, so that seems fine.
=> Only use pygeos is a recent version is installed

geopandas/tests/test_geom_methods.py
Check for a specific warning instead of generic number in buffer CRS warning. It currently fails since pygeog 0.8 and numpy 1.20 raise the following warning (fixed in pygeos 0.9)
```
/opt/miniconda3/envs/test/lib/python3.7/site-packages/pygeos/constructive.py:165: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
np.bool(single_sided),
```
https://github.com/geopandas/geopandas/runs/1803069757?check_suite_focus=true#step:7:2826
=> TST: check exact warning

geopandas/tests/test_plotting.py
Closes #1791 
The actual plot is still looking good, it's only the testing code that is failing.
It seems that the order of the axes in `Figure.axes` changed. Previously, it was first the subplot axes and then the colorbar axes. Now it's switched. I am not fully sure what the robust way is of getting this ax ..
=> TST: fix tests with matplotlib master

geopandas/_compat.py, geopandas/_vectorized.py, geopandas/testing.py, geopandas/tests/test_overlay.py, geopandas/tests/test_plotting.py, geopandas/tests/test_sindex.py
Closes #1818
This adds `normalize` capabilities. For now I only added it to our assert_.. functions. Eventually we might also want to add it to the GeometryArray/GeoSeries, but for that I would like to wait on Shapely including it (https://github.com/Toblerity/Shapely/pull/1090/)
Normalizing the geometries fixes most of the overlay tests, only the NYBB tests are still failing (here the differences with GEOS 3.9 are bigger than just some coordinate order). Not sure what the best way to solve this is. We can skip the geometry equality check for now with GEOS 3.9 (we already check area and bounds, and that passes), and later re-produce the expected files with GEOS 3.9
=> TST: add normalize option to assert methods + fix tests for GEOS 3.9

geopandas/_compat.py
Follow-up on https://github.com/geopandas/geopandas/pull/1659 and https://github.com/geopandas/geopandas/pull/1662, also catching the deprecation warning for `len(..)`
=> Compatibility with Shapely 1.8 deprecation warnings (__len__)

README.md
I just noticed that Readme is using figures stored in examples, so I am just updating links.
=> DOC: fix links in readme

geopandas/_compat.py, geopandas/array.py, geopandas/tests/test_array.py, geopandas/tests/test_extension_array.py
Overrides `ExtensionArray.shift` in `GeometryArray` to preserve the `crs`.
I considered an alternative implementation of overriding `_from_sequence`. That's what `ExtensionArray.shift` calls to make a new array and where the CRS is lost. (see https://github.com/pandas-dev/pandas/blob/653f6944eba664d19e8d93e850340ac039ec452e/pandas/core/arrays/base.py#L677-L692). So I figured if I could preserve the CRS there, it would fix this issue in `shift` but also potentially other places where `_from_sequence` is used. The problem is `_from_sequence` is a class method, not an instance method. So even though it is called with `self._from_sequence` it doesn't actually have access to anything within `self` and thus doesn't have the `crs`. It is possible to make a custom descriptor that would give …
=> BUG: Override shift in GeometryArray to preserve CRS

benchmarks/sindex.py
This corrects for removal of `VALID_QUERY_PREDICATES` in #1698, which breaks the sindex benchmarks.
Query predicates are now a property on the instance of a sindex backend class.  To get these up front, we have to first create a non-empty instance of the sindex.
=> TST: Fix sindex query predicates used in benchmarks

geopandas/geoseries.py, geopandas/tests/test_geoseries.py
Fixes #1704 (probably not completely)
I went for the easy fix (which still addresses the initial message of the issue), so that I could ask some clarifying questions.
The message below seems to suggest that when not passing the data argument (or passing `None`) to the GeoSeries constructor:
1.  there should be no warning raised
2.  a GeoSeries should still be returned.
Is this correct ?
> Thanks for the notice! This is indeed something worth fixing. Not only because of this, but also to avoid that warning we raise during (and potential deprecation in the future).
```
FutureWarning:     You are passing non-geometry data to the GeoSeries constructor. Currently,
it falls back to returning a pandas Series. But in the future, we will start
to raise a TypeError instead.
```
> Our constructor …
=> BUG: Create unintialized GeoSeries

doc/source/docs/reference/sindex.rst, geopandas/sindex.py, geopandas/tests/test_sindex.py
@martinfleis as a test, I copied the docstrings out of the RTreeIndex into a base class, and added those back to the RTreeIndex class with a decorator. And then only included this base class in the sindex.rst API docs.
Of course, if we want this, we need to generalize the docstrings a bit to suite both implementations. The question is if we want to keep the actual docstrings of the 2 concrete implementations more specific, which is possible, but then it doesn't really lead to a deduplication of docstrings in the code (and only in the online documentation)
=> DOC: only include common spatial index interface in the docs

environment-dev.yml, environment.yml
The binder button in docs creates an incorrect environment at the moment since it uses `environment.yml`, which is meant to be for development and as such does not include geopandas.
I have renamed the existing `environment.yml` to `environment-dev.yml` and created a new `environment.yml` with all dependencies required to run all examples in docs.
=> DOC: set up binder environment

geopandas/geodataframe.py, geopandas/tests/test_pandas_methods.py, geopandas/tests/test_plotting.py
Still need to add tests, but this should fix the pandas plotting issue (https://github.com/geopandas/geopandas/issues/1776#issuecomment-787487017).
The underlying cause is in the first place that the subset of columns that gets selected by pandas when preparing to plot (without a geometry column) still is a GeoDataFrame (-> opened https://github.com/geopandas/geopandas/issues/1856). And then on my fix for apply fails for such a GeoDataFrame without geometry column.
=> BUG: fixup GeoDataFrame.apply in case there is no geometry column

doc/source/gallery/plotting_with_geoplot.ipynb
Removing an example using geoplot which fails (both locally and on RTD).
=> DOC: remove faulty geoplot Voronoi example

doc/source/_templates/accessor_callable.rst, doc/source/docs/reference/geodataframe.rst
xref https://github.com/geopandas/geopandas/issues/1776#issuecomment-787486170
This copies the template from pandas to ensure the API docstring page gets built properly. 
The reason for the custom template is (IIRC) because sphinx otherwise splits the `geopandas.GeoDataFrame` and `plot` parts incorrectly.
It doesn't yet fully show up like a function (eg in the overview page it is listed as `GeoDataFrame.plot` and not ``GeoDataFrame.plot(..)``), but the rest of the generated page looks good (uses the correct docstring. 
The full fix entails a bit more sphinx hackery, like pandas does here: https://github.com/pandas-dev/pandas/blob/f4b67b5eafca7310235cb4b037978739d0e3e52e/doc/source/conf.py#L551-L564
But this fix should be sufficient for now I think.
=> DOC: fix API reference page for GeoDataFrame.plot accessor

ci/envs/38-dev.yaml
Numpy renamed their `master` branch to `main`, which broke our dev CI environment.
=> CI: use numpy main instead of master branch

geopandas/testing.py, geopandas/tests/test_testing.py
* Use geom_equals or geom_almost_equals consistently
* Reuse repeated code to generate AssertionError by taking it outside if/else block
* Only check equality once instead of three times by generating a boolean series and reusing it
Closes #1863
=> BUG: Refactor geopandas.testing._check_equality (GH1863)

geopandas/io/tests/test_sql.py
The main fix here is to pass CI tests, which seem to have been broken for a few weeks. Reading the error message:
> sqlalchemy.exc.ArgumentError: The argument passed to Dialect.has_table() should be a <class 'sqlalchemy.engine.base.Connection'>, got <class 'sqlalchemy.engine.base.Engine'>. Additionally, the Dialect.has_table() method is for internal dialect use only; please use ``inspect(some_engine).has_table(<tablename>>)`` for public API use
A second fix is from a warning message:
> test_sql.py:67: SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
Closes #1910
=> TST: use public API to fix several issues with sqlalchemy

ci/envs/37-latest-defaults.yaml
This is basically a revert of https://github.com/geopandas/geopandas/pull/1092, and should no longer be needed.
=> CI: unpin python in 3.7 build

doc/source/community/contributing.rst
I'll confess I was slow to read the text and my eyes tend to drift and follow instructions in the code blocks. The small doc PR adds cd doc in the instructions to make it easier to copy-paste instructions in the future.
=> DOC: add cd doc in code block

doc/source/conf.py, doc/source/docs/user_guide/mergingdata.rst
This doc PR add hyperlinks from the user-guide to the API. It also adds hyperlinks to the pandas docs.
Before: https://geopandas.org/docs/user_guide/mergingdata.html
after with the Blue sections being clickable:
=> DOC: hyperlink to API in merging section

doc/source/gallery/plotting_basemap_background.ipynb
Complements [the example page about adding a background map to plots](https://geopandas.org/gallery/plotting_basemap_background.html) with the new layers functionality of `contextily`, shamefully copying from [its introduction guide](https://contextily.readthedocs.io/en/latest/intro_guide.html#Using-transparent-layers), with the changes introduced in geopandas/contextily#114. Not much but I thought that'd make a good first PR since I'd been following that PR in `contextily` and wanted to give visibility to this feature. 
In passing I changed the use of the deprecated `url` kwarg of `contextily.basemap` to `source`, adopted the same naming for `contextily` as in its docs(`cx`), and added a plot to show that projecting to Mercator wasn't always necessary.
=> DOC: document contextily layers functionality

doc/source/gallery/plotting_basemap_background.ipynb
#1922 changed Jupyter kernel which broke RTD. Reverting.
I'll merge this immediately as we do not test this at the moment anyway.
=> DOC: fix jupyter kernel

geopandas/io/file.py
I think this is right, based on how a Shapely input is handled, and the bounds doc: (https://shapely.readthedocs.io/en/stable/manual.html#object.bounds).
https://github.com/geopandas/geopandas/blob/a445f979e29ec5180d5fa08660af08305a1a6932/geopandas/io/file.py#L176-L177
=> DOC: Clarify bbox input to read_file

doc/source/conf.py, doc/source/docs/user_guide/aggregation_with_dissolve.rst, doc/source/docs/user_guide/data_structures.rst, doc/source/docs/user_guide/geocoding.rst, doc/source/docs/user_guide/geometric_manipulations.rst, doc/source/docs/user_guide/indexing.rst, doc/source/docs/user_guide/io.rst, doc/source/docs/user_guide/mapping.rst, doc/source/docs/user_guide/mergingdata.rst, doc/source/docs/user_guide/missing_empty.rst, doc/source/docs/user_guide/projections.rst, doc/source/docs/user_guide/set_operations.rst
Closes  #1929
This PR follows the changes done in #1926 and adds other relevant API links to the [intersphinx mapping](https://github.com/geopandas/geopandas/blob/0d38f10a9507bba80ed23b91c697a74fe95250cd/doc/source/conf.py#L337). In addition, updates the links in the docs under [User Guide](https://geopandas.org/docs/user_guide.html)  and [Advanced Guide](https://geopandas.org/docs/advanced_guide.html) sections.
- Adds links to the documentations of relevant API's (based on [dependencies](https://github.com/geopandas/geopandas/blob/master/environment.yml))
- Updates the links for the documentations of the [User Guide](https://geopandas.org/docs/user_guide.html)  and [Advanced Guide](https://geopandas.org/docs/advanced_guide.html) sections (rst files are located under …
=> DOC: Relevant API links for intersphinx mapping

geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tests/test_geom_methods.py
Closes #1937 
Additionally ran into other issues when pygeos is not available, see traceback below, which this PR also solves. 
<details>
<summary>Details</summary>
```shell
Traceback (most recent call last):
File "/home/daniel/PycharmProjects/geopandas/geopandas/tests/scripting.py", line 40, in <module>
explode_pandas_multi_index()
File "/home/daniel/PycharmProjects/geopandas/geopandas/tests/scripting.py", line 20, in explode_pandas_multi_index
test_df = df.explode()
File "/home/daniel/PycharmProjects/geopandas/geopandas/geodataframe.py", line 1582, in explode
exploded_geom = df_copy.geometry.explode().reset_index(level=-1)
File "/home/daniel/PycharmProjects/geopandas/geopandas/geoseries.py", line 852, in explode
index = MultiIndex.from_tuples(index, names=self.index.names + [None])
File …
```
=> BUG: fix GeoDataFrame.explode with MultiIndex (#1937)

doc/environment.yml, doc/source/conf.py
RTD fails to create the environment now. Removing pins to check how it resolves and whether we really need them, since it may be wiser to use the latest versions of dependencies.
EDIT: pinned to new versions, it shaves off 5 minutes from the build time.
=> DOC: update RTD env

doc/source/docs/user_guide/projections.rst, geopandas/io/tests/test_file.py
xref #1975
This should make CI green (with the exception of dev) again. I would keep the #1975 open because we need to resolve it properly I think.
=> TST: adapt GPKG tests with undefined CRS

geopandas/tests/test_plotting.py
fixes #1962 
I ran the tests in two environments, one with matplotlib versions 3.3.4 and the other with 3.5.0.dev1280+g92825fefb, which passed.
=> TST: adapt colorbar tests to matplotlib 3.5 changes

geopandas/tests/test_plotting.py
Partially reverts geopandas/geopandas#2000, because matplotlib redid some of the refactor (https://github.com/matplotlib/matplotlib/pull/20501)
=> TST: adapt again colorbar tests to matplotlib 3.5 changes

doc/source/docs/user_guide/geocoding.rst, geopandas/tests/test_geocode.py, geopandas/tools/geocoding.py
=> REF/TST: replace GeocodeFarm with Photon as a geocoding default

doc/source/conf.py, geopandas/geodataframe.py
This PR attempts to link `pyarrow.parquet.write_table` mentioned in the doc string of `to_parquet` to the relevant pyarrow docs page.
I couldn't get the doc build to show the update locally. It was building the old doc string and I can't work out why.
This PR also sorts the packages in intersphinx_mapping to make it easier to add new packages and remove the typo (to to) the the `to_parquet` doc string.
=> DOC: pyarrow intersphinx mapping

doc/source/conf.py, doc/source/gallery/create_geopandas_from_pandas.ipynb
This should ensure that no matter the kernel specified in kernelspec, RTD always uses default one and doesn't fail.
I have temporarily allowed RTD for PRs to test this.
=> DOC: override kernelspec when executing notebooks

geopandas/_vectorized.py
Since PyGEOS 0.9, the "normalize" parameter was renamed to "normalized" for line_interpolate_point and line_locate_point.
There are a few [pytest CI warnings](https://github.com/geopandas/geopandas/runs/3074661832#step:6:3101):
>   /usr/share/miniconda/envs/test/lib/python3.8/site-packages/pygeos/linear.py:90: DeprecationWarning: argument 'normalize' is deprecated; use 'normalized'
This PR should clear these warnings up, and work with older PyGEOS versions.
xref https://github.com/pygeos/pygeos/pull/209
=> REF: line_interpolate_point and line_locate_point now use normalized

geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_merge.py, geopandas/tests/test_pandas_methods.py
Fixes #1230. 
Adds tests for pd.concat().
Wording of exceptions could probably use a little work. 
Currently I've added a new test demonstrating undesirable behaviour of pd.concat(... axis=0), which should probably be addressed separately.
=> BUG: fix pd.concat(... axis=1) causing duplicate geometry column names

geopandas/plotting.py
This should fix the failure we got after matplotlib 3.4.3 appeared on conda-forge (https://github.com/geopandas/geopandas/runs/3345624943?check_suite_focus=true#step:5:3000)
=> BUG: fix colorbar issue under matplotlib 3.4.3

geopandas/io/file.py
The coordinate order of the `bbox` parameter to `read_file()` is (minx, miny, maxx, maxy), and is documented as such in the docstring.  One of the examples in `read_file()` passes a tuple where minx == maxx == 0, which isn't invalid as an intersecting geometry but seems a bit misleading (or at least it confused me :) ) since the resulting Polygon is shaped like a line rather than a box.
This just flips `miny` and `maxx` so that the resulting geometry is rectangular with positive area.
=> DOC: modify `read_file` `bbox` example so that `bbox` is shaped like a box

geopandas/tests/test_sindex.py
These sindex tests were disabled for windows due to appveyor, but we don't actually use appveyor [any more?]. In any case, they pass on windows locally and on CI: https://github.com/m-richards/geopandas/pull/5
=> TST: Enable tests for windows that work on windows

doc/source/docs/user_guide/io.rst, geopandas/geodataframe.py, geopandas/io/sql.py
Recent sqlalchemy errors loudly when using `postgres` as protocol instead of `postgresql`.
=> DOC: postgres/postgresql protocol change in docs

geopandas/base.py, geopandas/tests/test_geom_methods.py, geopandas/tests/test_pandas_methods.py
The `cascaded_union` method was already long time deprecated in the docs (both in Shapely as in GeoPandas), but starting with1.8, shapely also actually deprecates it with a warning (https://github.com/Toblerity/Shapely/pull/1025). 
So this PR removed the use of that attribute in our tests, plus also follows the same change and actually deprecates the property on GeoSeries/GeoDataFrame (so the user gets a more correct warning message).
=> DEPR: actually deprecate cascaded_union in favor of unary_union

geopandas/geoseries.py, geopandas/tests/test_geoseries.py
While looking into some more of the warnings from our tests, I noticed that `GeoSeries([]).isna()` didn't properly return a boolean Series:
```
>>> geopandas.GeoSeries([]).isna()
GeoSeries([], dtype: geometry)
```
while the result of `isna` should always be boolean.
=> BUG: GeoSeries constructor should return Series for empty array with dtype when possible (fix GeoSeries.isna for empty Series)

geopandas/_vectorized.py
Another follow-up on #1819 / #1659 / #1662, catching some more deprecation warnings from the upcoming Shapely 1.8.
(with this, we don't have any place left where we do `arr[:] = ...` that is not wrapped in a `with ignore_shapely2_warnings():` context, so hopefully we are getting there ;))
=> Compatibility with 1.8 deprecation warnings (.coords)

ci/envs/38-latest-conda-forge.yaml, geopandas/tests/test_overlay.py, geopandas/tools/overlay.py, geopandas/tools/tests/test_clip.py
overlay based on symmetric_difference started [failing](https://github.com/geopandas/geopandas/runs/3515474201?check_suite_focus=true) on pandas master because we used an outer join based on columns full of NaNs. Refactoring the implementation to avoid it.
=> TST: skip tests of in overlay symmetric_difference under pandas 1.3.3

geopandas/geodataframe.py, geopandas/tests/test_pandas_methods.py
Fixes #1870 
Decided to have another look at this - was actually trying to construct a simple case to report an issue to Pandas itself as discussed in the above thread. I'm actually not convinced it really is a bug in pandas (more on that below) and so this is a fix in geopandas.
It was pretty straightforward to overload convert_dtypes, and I've added tests for some obvious edge cases.
-----------------------------------------------------------------------
This is the example that makes me question whether this is really a bug in pandas / or perhaps whether this use case is supported by pandas:
```python
import pandas as pd
class SubclassedSeries(pd.Series):
@property
def _constructor(self):
return SubclassedSeries
@property
def _constructor_expanddim(self):
return SubclassedDataFrame …
```
=> BUG: convert_dtypes() converts GeoDataFrame to DataFrame

.github/workflows/tests.yaml
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
This avoids workflows from queuing up if a lot of commits are made, e.g. if accepting suggestions in a PR it's common to make 20 commits in <2 minutes -> it can take hours for the last one to finish running since there's a limited number of runners per repo
=> GHA: cancel existing jobs when new commits are added

.github/workflows/tests.yaml
Attempt to fix #2121; I'm only 85% sure this will work 😛
=> GHA: Use github.ref instead of github.ref_head in concurrency group

geopandas/io/arrow.py, geopandas/io/tests/test_arrow.py
Closes https://github.com/geopandas/geopandas/issues/2071
=> ENH: Add storage_options to read_parquet

benchmarks/overlay.py
Motivated by the pretty serious performance regression on overlays
I accidentally introduced in #1582, and reported in #2089, here's a new
benchmark for overlays that makes the regression more apparent than the
existing overlay benchmarks.
On master:
```
[  0.07%] ··· overlay.Countries.time_overlay                                                                        3/5 failed
[  0.07%] ··· ====================== ===========
how                      
---------------------- -----------
intersection        337±6ms  
union             failed  
identity           failed  
symmetric_difference     failed  
difference        143±0.8ms 
====================== ===========
[  0.09%] ··· overlay.ManyPoints.time_overlay …
```
=> PERF: Add new overlay benchmarks

geopandas/geoseries.py
fixes #2109 
With the following setup:
```python
import numpy as np
import pandas as pd
outer_index = (1, 2)
nr_pts = 10000
index = pd.MultiIndex.from_arrays(
[[outer_index] * nr_pts, np.arange(nr_pts)],
names=("first", "second"),
)
df = gpd.GeoDataFrame(
{"vals": np.arange(nr_pts)},
geometry=[MultiPoint([(x, x), (x, 0)]) for x in range(nr_pts)],
index=index,
)
```
, timing `test_df = df.explode()` I get:
`master`: `62.3 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)`
`explode-perf`: `51.4 ms ± 1.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)`
=> PERF: MultiIndex creation in explode

geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/io/file.py, geopandas/io/tests/test_file.py
xref #1607
It doesn't support everything, but it does support the main 3 and raises an error when the extension is undetermined. I think the error will be very helpful to prevent https://github.com/geopandas/geopandas/issues/1607#issuecomment-688488076.
=> ENH: Add basic driver detection for to_file

CHANGELOG.md, doc/source/docs/user_guide/data_structures.rst, doc/source/docs/user_guide/mapping.rst, doc/source/docs/user_guide/missing_empty.rst, geopandas/geodataframe.py, geopandas/geoseries.py
Fixing some formatting issues and minimising the number of warnings emitted by sphinx, so it is easier to actually catch potential issues.
@jorisvandenbossche One note for the Changelog - when doing nested lists we need to keep a blank line in between, to ensure the RST renders correctly online.
=> DOC: minimise warnings from sphinx

geopandas/sindex.py
Xref https://github.com/geopandas/geopandas/issues/2076#issuecomment-927163830
This gives a 3x speed-up in the `sindex.BenchQuery.time_query('intersects', 'points', 'points')` speed-up case (the one with the biggest slowdown). 
It's in the scalar `query` (not `query_bulk`), so typically you won't call this method many times in a loop like the benchmark does (because you can then use `query_bulk`), but it's an easy fix, so can do that anyway.
cc @adriangb
=> PERF: pre-define PyGEOSSTRTreeIndex.valid_query_predicates

geopandas/io/file.py
See https://github.com/geopandas/geopandas/issues/2123#issuecomment-927178129
We have had several reports with `AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)` or `AttributeError: module 'fiona' has no attribute '_loading'` errors. 
This PR certainly doesn't solve all of those issues (eg I don't expect it fixes the case where import fiona before geopandas helps), but I could verify that it fixes one specific case: if your fiona install is broken, it currently also breaks import geopandas (with the second attribute error). 
This seems to be due to how fiona importing works: `import fiona` can fail with a clear ImportError, but a subsequent `from fiona import Env` then gives the confusing AttributeError. 
And because …
=> BUG: fix importing of Fiona to avoid AttributeError on broken fiona install

geopandas/tools/sjoin.py
Closes https://github.com/geopandas/geopandas/issues/2116
This removes it altogether. Alternative is put it behind a `if left_df.has_sindex:` check.
=> PERF: avoid calculating total_bounds in sjoin

benchmarks/plotting.py
While running the benchmarks, I've noticed that `mixed` plotting fails. The fixture creation raises `ValueError: cannot set using a list-like indexer with a different length than the value`.
The change is only on lines 61, 61, the rest is just `black` formatting.
<details>
```py
ValueError: cannot set using a list-like indexer with a different length than the value
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/kp/fxnnw89x5qbb9gryn507p03c0000gn/T/ipykernel_11467/436023914.py in <module>
8 
9 geoms = g1
---> 10 geoms.iloc[np.random.randint(0, 100, 50)] = g2
11 geoms.iloc[np.random.randint(0, 100, 33)] = g3
12 
/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/pandas/c …
```
=> BENCH: fix plotting fixture

geopandas/tools/tests/test_sjoin.py
This removes the suffix `_how_left` from the names of a few test cases that now test both `how='left'` and `how='inner'` as updated in #2143 
With the exception of `test_sjoin_nearest_left`, which was left as is on purpose, this lets us use `_how_right` suffix specifically when testing `how='right'` but otherwise leaves left / inner test cases without a suffix.
(tiny fix, so if you don't agree just close and don't merge; no need to debate)
=> Rename sjoin_nearest test cases to match test implementation

doc/source/docs/reference/sindex.rst, geopandas/sindex.py, geopandas/tests/test_sindex.py, geopandas/tools/sjoin.py
Closes https://github.com/geopandas/geopandas/issues/1977
This adds a new keyword `return_all=True/False` (with a default of True, so matching the `nearest_all` behaviour). But other ideas for the name of the keyword are certainly welcome as well.
This already combines both methods and updates the code/tests using it. Since this adds new functionality (currently unique to geopandas), i.e. using a `max_distance` when only wanting a single return value, I will also need to add new tests for that (still to do).
=> Combine sindex.nearest/nearest_all in single method

geopandas/tests/test_overlay.py, geopandas/tools/overlay.py
Fixes #2176 
I still need to fabricate some tests, this is a very edge case.
=> REGR: overlay keep_geom_type issue with collections of different types

geopandas/tools/clip.py
xref https://github.com/geopandas/geopandas/issues/1667#issuecomment-940303204
=> BUG: avoid warning from deprecated explode in clip()

ci/envs/38-dev.yaml, geopandas/tests/test_explore.py
As mentioned in https://github.com/geopandas/xyzservices/blob/main/CHANGELOG.md#xyzservices-2021100-october-19-2021
@martinfleis I am not sure if we want to care about being able to run the tests with older xyzservices versions? (or we could change the test a bit to not rely on the exact number)
=> TST: fix explore() tests for change in CartoDB max zoom level in latest xyzservices

ci/envs/38-dev.yaml
I am aware that this may change again soon with the plans to move from `Toblerity` org to `shapely` org but it is good to keep our CI green in the meantime anyway.
=> CI: use shapely main instead of master

.github/workflows/tests.yaml
A bit of CI maintenance:
- Run on pushes and pull-requests to maintenance branches (starting with `0.`)
- Lint job: Update to latest patch version [pre-commit/action](https://github.com/pre-commit/action) v2 of (currently [2.0.3](https://github.com/pre-commit/action/releases/tag/v2.0.3))
- Update [codecov/codecov-action](https://github.com/codecov/codecov-action) to v2
=> CI: Run on maintenance branches, update actions

geopandas/plotting.py
Closes #2209
From what I could see the intersphinx mapping in `conf.py` already includes matplotlib so hpoing this works with no extra change needed.
I wasn't sure how to test to see if this would pass through to the documentation so any advice there would be appreciated.
=> DOC: Include links to matplotlib as per #2209

doc/source/gallery/spatial_joins.ipynb
Closes #2211.
Added new example demonstrating sjoin_nearest including using the optional parameter distance_col.
My addition is:
_Markdown_
> We can also conduct a nearest neighbour join with `sjoin_nearest`.
_Code_
> pointdf.sjoin_nearest(polydf, how="left", distance_col="Distances")
> \# Note the optional Distances column with computed distances between each point
> \# and the nearest polydf geometry.
Output in gallery is (pretty printed in gdf):
>	geometry	value1	value2	index_right	BoroCode	BoroName	Shape_Leng	Shape_Area	Distances
> 0	POINT (913175 120121)	1033296	793054	0	5	Staten Island	330470.010332	1623819823.81	1479.2910924795774
> 1	POINT (932450 139211)	1071661	793239	0	5	Staten Island	330470.010332	1623819823.81	0.0
> 2	POINT (951725 158301)	1110026	793424	0	5	Staten Island …
=> DOC: Added sjoin_nearest method to examples gallery.

ci/envs/38-dev.yaml
Until https://github.com/geopandas/geopandas/pull/2275 is done, this will otherwise always fail the dev build, which makes we don't really easily notice any other failure.
=> CI: temporarily use released Shapely in the dev build

doc/source/docs/user_guide/interactive_mapping.ipynb
Adding a note to `explore` user guide regarding the CRS and tiles.
The real diff is on lines 61-66, the rest is some Jupyter mess.
xref #2254
=> DOC: mention CRS requirement in explore docs

geopandas/_compat.py, geopandas/tests/test_pandas_methods.py
Fixes #2287.
Wasn't sure on the naming convention for the LooseVersion guard, so I've just copied the logic from https://github.com/geopandas/geopandas/pull/1658/files and hoped that's okay.
There is a separate issue that the geometryarray that is now stored in the index loses CRS info, but have kept this focused to fixing CI.
=> TST: fix test_value_counts test for pandas 1.4

geopandas/plotting.py, geopandas/tests/test_plotting.py
This closes #2210, a case where adding a legend for a categorical and using
missing_kwds when no data was missing resulted in an UnboundLocalError.
=> BUG: Handle case where legend=True and missing_kwds for categorical

ci/envs/38-latest-conda-forge.yaml, ci/envs/39-latest-conda-forge.yaml
In all the "latest-conda-forge" ci envs, we are not pinning pandas and thus getting the latest (except for an outdated pin in the 38 env), so all were using pandas 1.3.x. 
I added pins for pandas 1.2 and 1.3 for the py-38 and 39 envs (and then the py-310 env will get the latest pandas 1.4 once that is out). And we already have a specific env that pins to 1.0 and 0.25 (that last one we could probably remove if we bump the minimum required version)
=> CI: diversify pandas versions in the test environments

geopandas/geodataframe.py
Tiny follow-up on https://github.com/geopandas/geopandas/pull/2303, restructuredtext is picky about having a whitespace line before a list
=> DOC: fixup rst formatting in dissolve docstring

geopandas/geodataframe.py, geopandas/tests/test_pandas_methods.py
Closes #2283 
> it's good that we didn't end up merging that just before the 0.10 release :)
Sorry about this and the other bug, hopefully there's not more.
This one at least is easy to fix, basically exactly what @jorisvandenbossche suggested. The one change is doing an isinstance check on `DataFrame` rather than `GeoDataFrame` -  to get `test_crs.py::test_apply_geodataframe` to work. I suppose this was probably why that check got taken out when I did #2060, it's still a pretty big oversight by me. 
I'm now looking into why that GeoDataFrame -> DataFrame change is neccessary - it means the raw results of apply in pandas aren't preserving the GeoDataFrame although it used to, which probably isn't great because it means the geometry column is becoming an object type column as an …
=> REGR: fix bug in apply when returning a series

geopandas/geoseries.py, geopandas/testing.py
Should fix the failing 310-dev environment, we're just now getting warnings from https://github.com/pandas-dev/pandas/pull/45321
(the change in geoseries is not required to fix CI, but seemed sensible to get all at once)
I also noticed setting up a local environment that this environment doesn't actually seem to use numpy main, despite in being in the yaml:
https://github.com/geopandas/geopandas/blob/cebb5873d04a81bf37376dfb5d4b2adcfe9d87af/ci/envs/310-dev.yaml#L29
I'll make that a separate issue though.
=> CI: update use of deprecated iteritems to avoid warnings

geopandas/tests/test_dissolve.py
The test function name needs to start with `test_` to be recognized by `pytest`.
This test was originally named correctly, but was apparently renamed by accident in PR#654.
=> TST: Fix first_dissolve not picked up by pytest

geopandas/geodataframe.py, geopandas/tests/test_dissolve.py
Explicitly flatten the index to avoid a Pandas FutureWarning.
This is a no-op if the index is already flat.
Fixes #2304
=> BUG: Fix FutureWarning with multiple aggregations in dissolve

geopandas/tests/test_pandas_methods.py
This should fix the CI (this test didn't run on pandas 1.3, and now pandas 1.4 is released the test started running on the minimal build, which doesn't have rtree or pygeos)
=> TST: skip pandas groupby test if no sindex available

geopandas/geodataframe.py, geopandas/tests/test_geom_methods.py
Closes #2271, closes #2229
In some cases, the output of `join` on line 1697 returns sorted index even though the original one is unsorted. If that happens, we need to sort rows back before assigning the MultiIndex.
=> BUG: explode incorrectly expects unsorted index

geopandas/tests/test_array.py
With Shapely 2.0, `Polygon()` will start to return an actual empty Polygon, while now it actually returns an emtpy GeometryCollection. This has some effect on the tests, so already correcting this now.
=> TST: fix array tests to use proper empty Polygon

geopandas/io/file.py
The `Int64Index` class itself is deprecated (it will just become `Index` in the future), so we need a different way to check the index. I _think_ just checking for integer dtype should be equivalent (RangeIndex also gives a dtype of int64)
=> COMPAT: avoid direct usage of pd.Int64Index

geopandas/io/arrow.py, geopandas/io/tests/test_arrow.py
This came up in https://github.com/geopandas/dask-geopandas/issues/138
While I wouldn't consider the spec stable (there are some discussions in https://github.com/opengeospatial/cdw-geo/ as well), I think at this point it is already used enough to say that we will keep some back-compat layer in geopandas to be able to read files written with the current pandas, even if the metadata spec would still change? (after all, the spec is versioned, and should allow this). 
If we want to make this guarantee, I think it should be OK to remove the warning? 
cc @brendan-ward
=> Remove warning about no stability promise in Parquet/Feather export

geopandas/array.py, geopandas/tests/test_geom_methods.py
Close #2223
Done by explicit checking of emptiness and returning nan for empty points. Some performance degradation of `.[xyz]` methods may be expected due to the extra array being prepared and the nonempty check.
=> BUG: Fix error on .[xyz] on GeoSeries with empty points: return nan

geopandas/tests/test_pandas_methods.py
I have to admit I am not fully sure what has changed in https://github.com/pandas-dev/pandas/pull/45911 but as a result, `GeoDataFrame.fillna` completely circumvents our custom `GeometryArray.fillna`. But it still seem to work as before, just raising a different error (from `GeometryArray.__setitem__`), so I guess this is fine?
=> TST: allow TypeError in fillna() with pandas main

geopandas/sindex.py
The current `sindex` that is used when pygeos is installed, `PyGEOSSTRTreeIndex`, subclasses the pygeos.STRtree. But we also have a `BaseSpatialIndex` class ourselves that defines the interface. 
Considering that the STRtree migrated from pygeos to shapely will change its API a bit, I was thinking that in general it seems better and more robust that we don't subclass here, but rather use composition (something we will need to do for `shapely.STRtree` anyway, if we want to keep the `.sindex` interface stable). 
In general this seems the better way to do this if we would allow for multiple SpatialIndex classes backed by different implementations (xref https://github.com/geopandas/geopandas/issues/1344)
cc @adriangb
=> REF: use composition instead of sublcassing pygeos.STRtree for SpatialIndex

.github/workflows/tests.yaml, ci/envs/37-latest-defaults.yaml, ci/envs/37-minimal.yaml, ci/envs/37-pd11.yaml, doc/source/getting_started/install.rst, environment-dev.yml, geopandas/_compat.py, geopandas/_vectorized.py, geopandas/array.py, geopandas/geodataframe.py, geopandas/io/sql.py, geopandas/plotting.py, geopandas/tests/test_api.py, geopandas/tests/test_array.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geoseries.py, geopandas/tests/test_pandas_methods.py, geopandas/tests/test_plotting.py, requirements-dev.txt, setup.py
Bumping required versions of dependencies following the rules defined in #1457 and removed now obsolete compatibility code.
=> DEP: bump required versions of dependecies

doc/source/docs/user_guide/io.rst
Closes #2336 
Following the gitter thread of @jorisvandenbossche & @RadMagnus from February, 2.
Added a section on the [io-page ](https://geopandas.org/en/stable/docs/user_guide/io.html) that explains in more detail how to check which formats are supported by geopandas.read_file by investigating the fiona library.
Explained how to change fiona/drvsupport.py on runtime to include supported drivers that are unexposed (commented out)
=> DOC: how to access unexposed drivers from fiona

geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
I have implemented the fix for the issue in https://github.com/geopandas/geopandas/issues/2394#issuecomment-1083426801
Unfortunately I had to change the test as well, because the `from_features()` method, used in the test calls `iter_features()` itself, so that the expected order of columns had to be changed. 
However, after the fix, the order of columns is predictable and corresponds to `geometry`  and the ordered `keys` of the dict to greate the GeoDataFrame.
If there are issues with this PR let me know and I'll try to improve
Closes https://github.com/geopandas/geopandas/issues/2394
=> BUG: preserve column order inside iterfeatures

geopandas/tests/test_crs.py
Closes #2388
For more context on those tests (and the disabling of network), see https://github.com/geopandas/geopandas/issues/1360
=> CI: disabling of network usage with PROJ 9

geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
Fixes https://github.com/geopandas/geopandas/issues/2242
It allows to have `'properties':null` in a geoJSON and still allow to use it with GeoDataFrame.from_features.
The geoJSON spec allows to use null for properties: https://geojson.org/geojson-spec.html https://datatracker.ietf.org/doc/html/rfc7946
=> BUG: support null properties in GeoJSON

geopandas/geodataframe.py, geopandas/io/tests/test_arrow.py, geopandas/tests/test_geodataframe.py
The `GeoDataFrame.to_parquet` function does not match the signature of [`pandas.DataFrame.to_parquet`](https://github.com/pandas-dev/pandas/blob/a07561e5a33b78cb54d163e81dd7a4444ca41554/pandas/core/frame.py#L2686-L2695), so when the function is called from [`google.cloud.bigquery.client.Client.load_table_from_dataframe`](https://github.com/googleapis/python-bigquery/blob/9a5a888bad569c8c1d8d72994d428ed92fe5ac47/google/cloud/bigquery/client.py#L2669-L2678) with the `engine` keyword, it ends up passing that keyword along to pyarrow, which eventually results in a `TypeError`:
```
File "pyarrow/_parquet.pyx", line 1377, in pyarrow._parquet.ParquetWriter.__cinit__
TypeError: __cinit__() got an unexpected keyword argument 'engine'
```
While `engine` isn't useful for `GeoDataFrame.to_parquet` …
=> BUG: avoid passing engine along to _to_parquet function

.github/workflows/tests.yaml, CONTRIBUTING.md, ci/envs/38-latest-conda-forge.yaml, ci/envs/38-latest-defaults.yaml, ci/envs/38-minimal.yaml, ci/envs/38-pd11-defaults.yaml, ci/envs/39-no-optional-deps.yaml, ci/envs/39-pd12-conda-forge.yaml, doc/source/community/contributing.rst, setup.py
Closes #2391 
I tried to keep the same logic of the CI matrix, just on higher Python versions. Since I had to bump yaml names at the same time, the diff is a bit broken. The only thing I did was to change the Python versions.
=> DEP: bump minimal Python version to 3.8+

geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tools/clip.py, geopandas/tools/tests/test_clip.py
Adds fast rectangle clipping to `tools.clip` by allowing `mask` to be a 4 element tuple (minx, miny, maxx, maxy). 
This leverages the `.clip_by_rect()` method, added to `GeoPandasBase` in https://github.com/geopandas/geopandas/pull/1928. Currently this PR bases off of #1928, so it might be nice to merge it first to get a nicer diff.
=> ENH: Add fast rectangle clipping option to `tools.clip`

geopandas/geodataframe.py
See comment at https://github.com/geopandas/geopandas/pull/2332#discussion_r889136091
I _think_ passing the `crs` is never needed here. In practice, this `_constructor_sliced` typically gets called from places within pandas, so where no `crs` keyword will get passed. And even if it is present, since we only get here if the actual underlying data is a GeometryArray, that should already have the crs in that case as well.
=> CLN: no need to specify crs in _constructor_sliced

geopandas/io/tests/test_arrow.py
We don't yet support writing partitioned datasets (xref https://github.com/geopandas/geopandas/issues/1382), but for parquet we actually do support reading them by using `pyarrow.parquet.read_table` (for feather this is not supported, see https://github.com/geopandas/geopandas/issues/2348). 
But, I don't think we actually explicitly test this capability (`read_table` will do it automatically for us, but some of the surrounding handling of eg metadata could in theory break it). So this PR is adding a basic test.
=> TST: read_parquet supports partitioned datasets

.gitignore, geopandas/plotting.py, geopandas/tests/test_plotting.py
Closes #1379 
Fixes this referenced example in issue
```
import pandas as pd
from shapely.geometry import Point, box
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
gdf = gpd.GeoDataFrame({
"geometry": [box(0,0,1,1), box(1,1,2,2), box(2,2,3,3), Point(0, 0), Point(1,1), Point(2,2), Point(3,3)],
"color_rgba": [(0.0, 0.0, 0.0, 0.5), (0.0, 0.0, 0.0, 0.2), (0.0, 0.0, 0.0, 0.1), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0)],
})
gdf.plot(markersize=1000, edgecolor="k", color=gdf["color_rgba"])
```
Also
```
from shapely.geometry import LineString, Point, Polygon
import numpy as np
gdf = gpd.GeoDataFrame(geometry=[Polygon([(1, 1), (1, 2), (2, 2), (2, 1)]),
LineString([(2, …
```
=> BUG: fix incorrect colors with mixed geometry types and list of colors

CHANGELOG.md, CONTRIBUTING.md, doc/source/community/contributing.rst
We recently agreed that we should change the way we collect changelog notes. Instead of doing one massive work skimming through all commits ahead of a release, the idea is that each PR will include a change log note, unless it covers only CI, tests or some other internal work.
(I also noticed that contributing guide in docs and the one in root are a bit out of sync, will have a look at it later).
=> DOC: add changelog for main

CHANGELOG.md, geopandas/geodataframe.py, geopandas/io/arrow.py, geopandas/io/tests/test_arrow.py
Fixes #2495 
This deprecates the `version` parameter used for `to_feather` / `to_parquet` because it collides with the underlying feather / parquet writer parameter of the same name.  It is replaced with `schema_version`.
Temporarily, this captures the `version` parameter only if it is 0.1.0 or 0.4.0 (since neither collide with versions of feather or parquet); otherwise it is passed directly to the underlying writer.
=> Fix: Deprecate version for to_feather / to_parquet

CHANGELOG.md, geopandas/geodataframe.py, geopandas/tests/test_pandas_methods.py
This resolves #2480, which was introduced by #2286.
Within there I added the check that `df.apply` producing geometry should return a geoseries
```python
result = df.apply(lambda row: row.geometry, axis=1)
assert_geoseries_equal(result, df.geometry, check_crs=False)
```
This conflicts in the case of columns which are all  NaN as null is a legal value in a geometry array and cast by preserve geometry.
To resolve, this casting to a GeoSeries is more strict - it only happens for object dtypes now, rather than being attempted for any dtype.
This leaves the additional (slightly pathological) case of how a list of how an object dtype of all None's is handled. I've opted that this should stays as all Nones rather than becoming a geometry array - it seems hoping for these to be geometrydtype and …
=> REGR: Fix df.apply NaN to None regression

CHANGELOG.md, geopandas/geodataframe.py, geopandas/tests/test_geom_methods.py
Fixes #2501
Changes in #2292 resulted in a geometry column name being lost and only partially recovered in `__finalize__`. This should ensure that it gets always fully retained.
=> REGR: regression in ``GeoDataFrame.explode()`` with non-default geometry column name

CHANGELOG.md
xref https://github.com/geopandas/geopandas/issues/2444#issuecomment-1190632831
One question is whether we still want to include https://github.com/geopandas/geopandas/pull/2505 as well
=> DOC: update changelog for 0.11.1

CHANGELOG.md, geopandas/io/file.py, geopandas/io/tests/test_file.py
Fixes #2502 dealing with out of bounds datetimes.
Note that this includes #2479 so that should be merged before this (I originally was going to solve both things in the one PR but the tests were a little more complicated than I first thought - with GPKG and GeoJSON behaving differently.
=> BUG: Fix out of bounds datetime

doc/source/gallery/plotting_with_folium.ipynb
The formatting of [Plotting with Folium](https://geopandas.org/en/latest/gallery/plotting_with_folium.html) is a bit inconsistent.
Thus, I reformatted the file with [jblack](https://github.com/jupyter-black/jblack).
I can also reformat other Jupyter Notebooks with `jblack` if it makes sense in your opinion.
=> DOC: Reformat plotting_with_folium.ipynb

geopandas/tests/test_pandas_methods.py
Closes #1852.
Note this issue was already resolved (pretty sure as part of 0.11 and defining _constructor_sliced but I haven't checked explicitly), this is just a test to document correct behaviour.
=> TST: add test to close GH1852

geopandas/tests/test_plotting.py
Just noticed this while running tests in an environment where I did have matplotlib, but not scipy. We are testing here that the plot call raises an ImportError, but then still continued the rest of the test (triggering that import error again, failing the test)
=> TST: fix accessor plotting tests skip for no scipy

LICENSE.txt
This updates the copyright year to current year.
This also corrects the 3rd clause to be the name of the copyright holder as per [BSD license](https://opensource.org/licenses/BSD-3-Clause)
=> DOC: Update copyright year, fix 3rd clause ref to GeoPandas

geopandas/sindex.py, geopandas/tools/tests/test_sjoin.py
Resolves #2528 by adding the missing binary predicates to the docstrings for query / query_bulk.
Note: `dwithin` is intentionally omitted because it requires a distance parameter, which isn't part of the API here yet.
Also note: only a few of the predicates are actually tested using real geometries in `test_sjoin.py`, but updating that was beyond the scope of this PR.
=> DOC: add all valid binary predicates to STRtree query / query_bulk

geopandas/base.py
I have added one line to the example of `bounds` which shows how to assign the values back to the `GeoDataFrame`.
I know this goes beyond a simple example of the function and more into a cookbook but I think users would benefit from this. Adding it here makes it easy to discover for users. I imagine it'll have quite a bit of usage for people wanting to filter rows of the `GeoDataFrame` from the output of `bounds`. The method should be stable that it continues to work in the future.
=> DOC: assign bounds to geodataframe example

doc/environment.yml
The readthedocs build is also failing since a few weeks (since pydata-sphinx-theme 0.10 was out): https://readthedocs.org/projects/geopandas/builds/17963754/)
Temporary pinning this to 0.9.0, but we should also look into fixing the errors -> https://github.com/geopandas/geopandas/issues/2561
=> DOC: pin pydata-sphinx-theme to 0.9 for now

doc/source/about.md, doc/source/about/roadmap.md
This is a proposal of a roadmap for the GeoPandas project (not covering sub-projects) resulting from the [discussions](https://hackmd.io/pq8MqmtxTFqqaiayFuuEYQ) during the GeoPandas community calls. 
Feel free to open a discussion on a removal of individual goals or moving them between the milestones. If you have another suggestion on what would you like to see on a roadmap, feel free to suggest it here or open a separate issue for a discussion (not everything needs to be included in the first version but we need one for NumFocus in about 2 weeks).
I would like to merge the first version in relatively soon, ideally during the first week of October or sooner.
cc @geopandas/collaborators
=> DOC/MAINT: GeoPandas roadmap draft

doc/source/docs/user_guide/geometric_manipulations.rst, geopandas/base.py
I worked on the following issue and fixed typos (geometries’s to geometry's) in docs.
https://github.com/geopandas/geopandas/issues/2563
=> DOC: change geometries’s to geometry's

ci/envs/38-latest-conda-forge.yaml
I don't think there is a reason to still install it with pip (originally this was done to install the latest main version)
=> CI: install pyogrio from conda-forge instead of pip

geopandas/_vectorized.py
xref #2579 
This should ensure we have the same behaviour or unary_union not matter the geometry backend and turn our CI green again.
There is still an open discussion on whether we want to keep `None` or transition towards GeometryCollection Empty to have a consistency with shapely.
=> COMPAT: return None instead of empty collection in unary_union using shapely 2.0

doc/source/gallery/spatial_joins.ipynb
Corrects the old reference to the `op` kwarg.
=> DOC: update spatial_joins predicate param ref

geopandas/_compat.py
This gives:
```
>>> import geopandas
<stdin>:1: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still
use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment
variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before
importing geopandas:
import os
os.environ['USE_PYGEOS'] = '0'
import geopandas
=> Add warning when having both PyGEOS and Shapely 2.0 installed

CHANGELOG.md, geopandas/geodataframe.py, geopandas/tests/test_crs.py, geopandas/tests/test_merge.py
This is almost entirely based on the TODOs in https://github.com/geopandas/geopandas/pull/2373.
The only deviation I've made is in the getter for `crs`, I re-raise an AttributeError for trying to access `gdf.crs` when the active geometry column is not set. I think this is clearer for a user - rather than getting an error about `gdf.geometry` not being defined propagating from inside `gdf.crs` - and there is also the current case of where `gdf.geometry` isn't defined but `"geometry"` is in `gdf.columns` which gives pd.Series has no attribute crs right now - but that would change after #2575.
=> DEPR: remove `_crs` attribute

geopandas/tools/_show_versions.py
Update `geopandas.show_versions()` to work with Shapely 2, and also to use pyogrio (if fiona is not installed) to detect the GDAL version.
=> Update geopandas.show_versions() for GEOS and GDAL

CHANGELOG.md, geopandas/explore.py
This PR resolves the [`PendingDeprecationWarning`](https://github.com/geopandas/geopandas/actions/runs/3243624358/jobs/5318620857#step:6:4291) that is being thrown by `matplotlib` due to the upcoming deprecation of [`matplotlib.cm`](https://matplotlib.org/stable/api/cm_api.html#module-matplotlib.cm).
```
PendingDeprecationWarning: The get_cmap function will be deprecated in a future version. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
```
=> COMPAT: resolve matplotlib.cm warning in explore()

geopandas/explore.py
Pinning the correct min version required for new handling of cmaps in explore as pointed out by @rraymondgh in https://github.com/geopandas/geopandas/pull/2596#issuecomment-1287905024.
@jorisvandenbossche this should make it to the 0.12.
=> COMPAT: fix matplotlib version required for new cmaps

geopandas/tools/tests/test_clip.py
This should fix the failures on CI in an env with shapely 2.0b2. https://github.com/shapely/shapely/pull/1590 uncovered that we were passing a list of tuples to a Point constructor. While old shapely uses only the first tuple and ignores the rest, shapely 2.0b2 correctly raises an error.
=> TST: fix point creation in clip test suite

.github/workflows/tests.yaml
Pytest's short summary at the end of the run now shows only skipped tests. This ensures that every result other than pass is listed.
=> CI: include errors, failures, xfails and xpasses in the pytest short summary

.github/workflows/tests.yaml, ci/envs/310-latest-conda-forge.yaml, ci/envs/311-latest-conda-forge.yaml, ci/envs/38-latest-conda-forge.yaml, ci/envs/39-latest-conda-forge.yaml, ci/envs/39-no-optional-deps.yaml, ci/envs/39-pd12-conda-forge.yaml
With pyogrio being rebuilt for 3.11 (~Fiona not yet~), we should have all we need to test geopandas with Python 3.11.
~This env also excludes pygeos and uses shapely 2.~ (does not resolve)
Closes #2592
=> CI: add Python 3.11 to the test matrix

.github/workflows/versioneer.yml
Add a GitHub Action workflow that checks once a month if all the Versioneer files are still up to date, and opens a PR if updates are available.
Also runs on manual dispatch, if `setup.cfg` or the workflow itself (`versioneer.yml`) is changed.
=> CI: Create workflow to automatically update Versioneer

pyproject.toml, setup.py
This PR is a follow-up from #2419, and moves the project metatdata from `setup.py` to `pyproject.toml` as described by [PEP 621](https://peps.python.org/pep-0621/) and supported by [setuptools >= 61](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html). This supersedes #2424 as there are more community commitments behind maintaining project metadata in `pyproject.toml` than `setup.cfg`.
Details:
- Add new metadata: keywords and classifiers.
- Change author to "Kelsey Jordahl" (with existing email match), move "GeoPandas contributors" as maintainers.
- Change licence from slightly ambiguous "BSD" to SPDX compliant "BSD 3-Clause".
- Change how packages are found, using patterns `geopandas` and `geopandas.*`. This now finds `geopandas.io.tests`, which seems to be …
=> MAINT: move static metadata to pyproject.toml

.github/workflows/versioneer.yml
Run Black after updating Versioneer, and add a message to the PR body with some specific instructions (see https://github.com/geopandas/geopandas/pull/2633#pullrequestreview-1166413777)
=> Versioneer CI: Run black, add PR message

.github/workflows/versioneer.yml
The default black options _for GitHub Actions_ are `--check --diff`, which is different from the regular CLI. This PR overwrites that which allows Black to fix things instead giving an error.
```yml
- uses: psf/black@stable
with:
options: "--verbose"
```
Succeeds #2634.
=> Versioneer CI: Allow Black to fix formatting

geopandas/tests/test_sindex.py
**pandas** 2.0 is removing `Series.append()`.  There is a test that incorrectly suppresses deprecation warning.  Changed to use `pandas.concat()`
=> CI: 310-dev tests failing

geopandas/tests/test_explore.py
new branca release https://github.com/python-visualization/branca/releases/tag/v0.6.0
used in `explore()`.   There's a subtle change where embedded html/javascript that is generated by **branca** has changed from single quoted to double quoted strings.  Change test cases to pass on either case,  making it forward and backward compatible test case.
Where CI virtual machines have been rebuilt and using **branca** 0.6.0 CI is failing.
=> COMPAT: branca 0.6.0

geopandas/array.py, geopandas/geodataframe.py, geopandas/geoseries.py
Fix typo `no notion or projecting` -> `no notion of projecting`
=> Fix docstring typo in to_crs

.pre-commit-config.yaml
Currently the pre-commit.ci configuration, [`.pre-commit-config.yaml`](https://github.com/shapely/shapely/edit/main/.pre-commit-config.yaml), is a bit outdated. We could update it manually or write a custom workflow for it, but the easiest way to fix is is enable [pre-commit.ci](https://pre-commit.ci/). By default, it checks weekly if pre-commit versions can be updated and if so opens a PR to do so.
It also has an option to autofix PRs, which can be a great quality of life feature. It's `false` for now because it's a bit of a larger change.
=> pre-commit config: Add auto update schedule

ci/envs/39-latest-conda-forge.yaml
Testing the latest main in an additional build, and then will later today update this to use the actually released 2.0.0
=> CI: update shapely versions in test build matrix

ci/envs/39-latest-conda-forge.yaml, ci/envs/39-pd12-conda-forge.yaml
This is trying to address the crashes in the pandas 1.2 and pandas 3.9 latest environments seen here: https://github.com/geopandas/geopandas/actions/runs/3771037533/jobs/6411224335
----------------------
Subsequently repurposed to pin numpy versions after this was fixed upstream.
=> CI: numpy version for pandas 1.2

geopandas/_compat.py, geopandas/io/tests/test_file.py
This fixes one of the CI failures at the moment, the default representation of timezones has changed on the pandas main branch.
=> COMPAT: Fix pandas tz defaults

pyproject.toml, setup.py
This fixes two things:
1. There is a GitHub bug where the project name is assumed to be in `setup.py` to show dependents in the dependency graph; currently [it is empty](https://github.com/geopandas/geopandas/network/dependents)
2. Re-format the "text" TOML entry to it's own section, as the current form has problems with some packages, e.g. try "tox", and see "toml.decoder.TomlDecodeError: Stuff after closed string. WTF? (line 32 column 1 char 977)". The content of the readme is unchanged.
=> BUG: Add name to setup.py for GitHub, re-format text TOML entry

geopandas/tests/test_explore.py
Closes #2697
Folium made a small change in ordering of values in the output JS, so we need to adapt to that. The result is exactly the same.
=> TST: adapt test for folium main

doc/source/docs/user_guide/interactive_mapping.ipynb
Small change to the notebook showing interactive mapping.
- The `control` parameter is already True by default, no need to specify it.
- [We've recently merged a PR in folium](https://github.com/python-visualization/folium/pull/1690) that changes the default behavior when adding multiple base layers. Keep the current behavior by specifying we don't want to see the extra tilelayer when opening the map.
=> DOC: update usage of `folium.TileLayer`

.github/workflows/versioneer.yml
Fixes #2690.
Manually remove `__init__.py` changes from the commit to avoid the duplication of those two lines like we have now in #2694.
I tested it on my fork but it will probably needs to be merged to test it properly.
=> CI: fix versioneer update action

geopandas/array.py, geopandas/base.py, geopandas/geoseries.py, geopandas/io/sql.py, geopandas/sindex.py, geopandas/testing.py, geopandas/tests/test_array.py
As a first step, this makes the `.data` attribute of GeometryArray into a read-only property, and switches to use `_data` internally. In a next step we can then add a deprecation warning to the public property.
=> REF: rename GeometryArray.data to _data

geopandas/tests/test_plotting.py
The matplotlib failures in the dev build are known and the change might be reverted on the matplotlib side: https://github.com/matplotlib/matplotlib/issues/25162 (and if not, it's also easy to solve with adding some `squeeze()` calls to remove the extra dimension of length 1 in the color array). 
For now, assuming this will be changed back in matplotlib, skipping the tests just for mpl 3.8.0.dev, to get a green CI build.
=> TST: temporary skip test_legend for matplotlib 3.8.0.dev

geopandas/tests/test_sindex.py
Normally, selecting multiple columns in pandas returns a copy, but that was not done for extension dtype columns. This is fixed in 2.0 (https://github.com/pandas-dev/pandas/pull/51197), so we have to update one of our tests accordingly (this should fix one of the failing tests in the dev build).
This is somewhat a regression from the point of view of geopandas (adding an extra copy), but with the experimental Copy-on-Write feature of pandas, this will go back to not copying (unless you would afterwards mutate the column).
=> TST: selecting multiple columns copies GeometryArray with pandas >= 2.0, losing sindex

CHANGELOG.md, geopandas/io/file.py
Addresses issues related to pyogrio engine noted in [#2795 comment](https://github.com/geopandas/geopandas/issues/2795#issuecomment-1435264056)
This skips preprocessing of the file path or bytes passed to `read_file` and instead delegates that to `pyogrio` to parse.
Since this was the simpler case, I moved it to the first condition.
Tested manually with the remote file referenced in #2795 and it yields the same performance as using `pyogrio` directly.
=> FIX: remove download from URL in read_file before calling Fiona / pyogrio

doc/source/conf.py
Building the docs give an error on an "icon_links" key that doesn't exist.
This PR uses the "icon_links" syntax to create the links to github and twitter and this seems to work.
Noticed the problem when building docs failed in #2814
=> DOC: Fix icon_links error in docs

doc/environment.yml, doc/nyc_boros.py, doc/source/conf.py, doc/source/docs/user_guide/aggregation_with_dissolve.rst, doc/source/docs/user_guide/data_structures.rst, doc/source/docs/user_guide/geocoding.rst, doc/source/docs/user_guide/geometric_manipulations.rst, doc/source/docs/user_guide/indexing.rst, doc/source/docs/user_guide/interactive_mapping.ipynb, doc/source/docs/user_guide/io.rst, doc/source/docs/user_guide/mapping.rst, doc/source/docs/user_guide/mergingdata.rst, doc/source/docs/user_guide/projections.rst, doc/source/docs/user_guide/reproject_fiona.rst, doc/source/docs/user_guide/set_operations.rst, doc/source/getting_started/introduction.ipynb
This PR will eventually replace all occurrences of `geopandas.datasets` with alternative data using `geodatasets`. At the moment WIP, want to see RTD builds.
It will allow us to deprecate `geopandas.datasets`.
=> DOC: replace geopandas.datasets with geodatasets in user-facing documentation

geopandas/geodataframe.py, geopandas/io/sql.py
Some extra clarification in doc based on the comment here: #2799 :
- an example of GeoDataFrame.to_file using some engine-specific keyword arguments. Based on the issue above the example is related to the creation of a spatialite file.
- **QST**: if the example is OK, should it also be added to GeoSeries.to_file ? In geoseries.to_file is now already an example less, not sure if this is on purpose.
- clarify in to_postgis that file databases are easier to write using to_file.
=> DOC: Clarify that file databases can also be written using to_file

geopandas/io/tests/test_file_geom_types_drivers.py
Because writing to spatialite is now added as an example in to_file, it was mentioned in #2821 that it would be better to add a test on it as well...
=> TST: Add tests for to_file/read_file for spatialite format

benchmarks/sindex.py, geopandas/array.py, geopandas/sindex.py, geopandas/tests/test_array.py, geopandas/tests/test_sindex.py
Next step for the PyGEOS->Shapely migration of https://github.com/geopandas/geopandas/issues/2691
Next step after adding `_data` in https://github.com/geopandas/geopandas/pull/2785 to actually raise a warning when accessing `data` (I now am doing this always, not only when there are pygeos geometries)
=> DEPR: deprecate the usage of GeometryArray.data to access PyGEOS geometries

CHANGELOG.md, geopandas/io/file.py, geopandas/io/tests/test_file.py
cc @brendan-ward this translates the current `mode` keyword and enables the tests
I think it would still be good to document (and test) you can also pass `append=True` (that should already work since we pass through the keywords). And we could actually also do that for the fiona engine (translate append=True to mode="a")
=> ENH: enable and test append mode for pyogrio engine

geopandas/io/tests/test_file.py
Starting with pandas 2.0, it preserves the non-ns resolution of datetime64 input. And pyogrio creates datetime64[ms] data (that's the accuracy that GDAL supports)
=> TST: read_file with pyogrio and pandas>=2 gives datetime64 with ms unit

geopandas/tests/test_geom_methods.py
This should resolve those failing tests on Windows with Python 3.8. Pandas now support dtypes in Index but int defaults to int32 in that environment causing the failure. Given the issue is only in this one env and Py3.8 will be phased out soon, skipping felt like an appropriate response.
=> TST: skip tests with multiindex on win and Py38

doc/source/docs/advanced_guide.rst, doc/source/docs/user_guide/pygeos_to_shapely.rst
Adding a documentation page outlying the migration period from pygeos being the default to only shapely 2.0 being supported and the recommended way of adapting the code.
Xref #2691
=> DOC: add a pygeos -> shapely migration guide

doc/source/community/ecosystem.md
I personnaly use GADM dataset a lot when it comes to administrative boundaries and I was always copy/pasting the same script to load data from their server as Geodataframe. 
I ended-up created a lightweight package that loads these data with just the name of the admin area and deals with some simple issues such as:
-loading to GEE 
- manage duplicate names
- download specific administrative subdivisions within a requested country
I thought (maybe naively) that this package could be included in the "data retreival" section of your documentation.
=> DOC: add the pygadm package to geopandas ecosystem

README.md, doc/source/docs/user_guide/geometric_manipulations.rst
This PR contains a few improvements of the comments in the code examples for [Geometric Manipulations](https://geopandas.org/en/latest/docs/user_guide/geometric_manipulations.html#examples-of-geometric-manipulations). Partly, this is also relevant for the main README:
- Fix typo "object" to "objects"
- Add highlighting of `geopandas.GeoSeries` 
- Add change "our" to "a" corresponding to PR #2650
=> DOC: Fix typos in comments of code examples for "Geometric Manipulations"

geopandas/io/sql.py, geopandas/io/tests/test_sql.py
Closes #2407
I was looking back and realized I said I would make a PR for #2407 but never did. I thought I ought to just tie up that loose end once and for all, because it annoyed me again the other day.
=> Made read_postgis raise ValueError if the geom_col is specified twice (current error is cryptic)

geopandas/plotting.py, geopandas/tests/test_plotting.py
It seems we are getting tripped up by ax.legend's rather complex calling convention, resulting in an error: "You have mixed positional and keyword arguments, some input may be discarded."
Simplify the call by integrating all arguments into kwargs.
=> BUG: Fix broken call to ax.legend

geopandas/geodataframe.py
The `explore` method already has a `docstring`.  Decorating the `explore` methods with `@doc` docerator is causing the documentation to show the docstring twice (here: https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html)
=> DOC: Remove redundant sentence in documentation of the `explore` method

.github/workflows/tests.yaml
`mamba-org/provision-with-micromamba` is [deprecated](https://github.com/mamba-org/provision-with-micromamba) and it is recommended to use `setup-micromamba` instead. 
I will self-merge this once the CI gets green.
=> CI: use mamba-org/setup-micromamba action

CHANGELOG.md, geopandas/io/file.py, geopandas/io/tests/test_file.py
Fixes https://github.com/geopandas/geopandas/issues/2908
Alternative for https://github.com/geopandas/geopandas/pull/2912, since that didn't fix all cases of urls that no longer work. 
The approach in this PR is to only _not_ download the data ourselves ~if the url has an extension~ if the url indicates to support reading ranges (and in that case we assume the /vsicurl/ filesystem will work), and in all other cases still download the data as we did before, passing the raw bytes to pyogrio/fiona. 
If later pyogrio/fiona have better support for urls, we could again consider passing through all urls.
=> REGR: fix read_file from urls

CHANGELOG.md, ci/envs/310-dev.yaml, ci/envs/310-latest-conda-forge.yaml, ci/envs/311-latest-conda-forge.yaml, ci/envs/38-latest-conda-forge.yaml, ci/envs/38-latest-defaults.yaml, ci/envs/38-minimal.yaml, ci/envs/38-pd12-defaults.yaml, ci/envs/39-latest-conda-forge.yaml, ci/envs/39-pd13-conda-forge.yaml, geopandas/explore.py, geopandas/tests/test_explore.py
Closes #2922
We need to pass `k` from `binning`, not the one passed as an argument as `mapclassify.classify` may result in different number of bins (esp. with `UserDefined` scheme).
=> BUG: fix a color assignment in ``explore`` when using ``UserDefined`` bins

CHANGELOG.md, geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
=> BUG: Fix crash on constructing gdf with colname `crs`

doc/source/getting_started/install.rst
The GeoPandas docs installation page references the pointpats package and links to https://pointpats.readthedocs.io/en/latest/, which doesn't exist. This trivial PR fixes the link by pointing to the homepage https://pysal.org/pointpats/ instead.
=> DOC: broken pointpats link in docs

CHANGELOG.md, geopandas/io/file.py, geopandas/io/tests/test_file.py, geopandas/io/tests/test_infer_schema.py
Let columns of dtype `np.int32` (non-nullable) and `pandas.Int32Dtype()` (nullable) be inferred as int32 columns instead of int(64). Needed for the `OGR_GMT` driver.
Related:
- https://github.com/GenericMappingTools/pygmt/pull/2592
- https://github.com/geopandas/geopandas/issues/967#issuecomment-842999302
Similar PRs in the past:
- https://github.com/geopandas/geopandas/pull/2265
- https://github.com/geopandas/geopandas/pull/2464
=> BUG: Infer schema for np.int32 and pd.Int32Dtype columns properly

geopandas/_compat.py, geopandas/array.py, geopandas/tests/test_pandas_methods.py
Fixing some of the warnings we have on the dev build:
```
geopandas/tests/test_extension_array.py::TestMissing::test_fillna_series
/home/runner/work/geopandas/geopandas/geopandas/tests/test_extension_array.py:372: FutureWarning: ExtensionArray.fillna added a 'copy' keyword in pandas 2.1.0. In a future version, ExtensionArray subclasses will need to implement this keyword or an exception will be raised. In the interim, the keyword is ignored by GeometryArray.
result = ser.fillna(fill_value)
```
I have to check if this is properly tested in the upstream tests we inherit (maybe not since they were not failing before, only warning)
=> COMPAT: add fillna copy keyword for pandas 2.1

geopandas/tests/test_pandas_methods.py
Failure with latest pandas release, as described in https://github.com/geopandas/geopandas/issues/2948. I am skipping that part of the test just for pandas 2.1.0, assuming we will fix it by pandas 2.1.1.
=> TST: skip astype(object) check in test for pandas 2.1.0

geopandas/_vectorized.py
Just adding in the fact that when we use shapely over pygeos when pygeos is the selected engine, we need to convert the result back to pygeos (as originally noted here). This will all go away in 1.0 anyway, but still a bug for now.
https://github.com/geopandas/geopandas/pull/2940#discussion_r1273415232
=> BUG: fix pygeos compat for concave hull

ci/envs/310-dev.yaml
Nightlies of core scientific python projects are now on https://pypi.anaconda.org/scientific-python-nightly-wheels not on https://pypi.anaconda.org/scipy-wheels-nightly/. Changing the repository and switching pandas and matplotlib to install from that nightly wheel rather than building from source.
=> CI: use the new nightly repo

doc/source/docs/user_guide/interactive_mapping.ipynb, doc/source/gallery/plotting_basemap_background.ipynb, doc/source/gallery/plotting_with_folium.ipynb
Stamen is [deprecating](https://stamen.com/here-comes-the-future-of-stamen-maps/) they're tiles. Removing their usage from our docs. 
They are further mention in `explore` as a reference to folium. There I would wait for https://github.com/python-visualization/folium/issues/1803 to be resolved.
The same issue is in the notebook describing contextily, where we should first resolve https://github.com/geopandas/contextily/issues/220.
=> DOC: remove Stamen tiles from docs

geopandas/base.py
Our custom equals implementation uses `_data` which is deprecated and triggers a warning on pandas >=2.1, but it looks like we only have this to work around a pandas issue. Just running on CI to see what removing this does.
Seems not to cause any issues.
=> COMPAT: Remove base.equals override

CHANGELOG.md
I just sorted the list of changes, added missing PR number and fixed formatting. I also went through the list of commits since 0.13.2 and it seems that we have it all included (when relevant).
=> RLS: prepare changelog for 0.14

geopandas/io/tests/test_file.py
The tests show a bunch of warnings from `test_file.py` coming from pyogrio.
=> TST: fix/suppress some warnings for the pyogrio tests

.github/workflows/tests.yaml, ci/envs/312-latest-conda-forge.yaml
I think that matplotlib is breaking it but let's give it a go and get it temporarily from pip if needed.
=> CI: include Python 3.12 in the matrix

geopandas/io/file.py, geopandas/io/tests/test_file.py
The latest dev version of pyogrio now supports `skip_features` that are not between 0 and the feature count (truncating larger values to the feature count, i.e. skipping all rows). This PR updates the test to follow that change.
Negative values for `skip_features` are right now also interpreted as "skip everything", while here we allow a negative slice start to mean counting from the end. That's something we should decide what to do with this on the pyogrio side (if allowing negative skip_features, just letting it skip everything is also a bit confusing?) 
For this PR, for now raising an error on our side about negative slice start in case of pyogrio.
=> TST: fix bbox test for latest pyogrio

geopandas/array.py, geopandas/tests/test_geom_methods.py
When doing #3013, when @m-richards pointed out that we may need to keep the allocation of an empty array and then its population, we thought we don't since we thought it is shapely 1.8 related. Well, it was not :D. When there is no actual interior, this is now failing on main.
Fixed. No need for changelog as it fixed unreleased #3013.
=> BUG: fix interiors when no interior is present

geopandas/explore.py
Stamen will no longer work in a few days and folium will directly depend on xyzservices. Removing the mention of Stamen for now and will update again once the implementation in folium is merged.
=> DOC: remove Stamen from explore docstring

ci/envs/312-latest-conda-forge.yaml
No need for pip install of pointpats and matplotlib anymore (at least on a macOS).
=> CI: install whole 3.12 env from conda-forge

CHANGELOG.md, geopandas/io/_pyarrow_hotfix.py, geopandas/io/arrow.py
Similar to https://github.com/apache/arrow/pull/38608, but doing it on our side as well for people that use latest geopandas with older pyarrow. 
(using a similar approach as https://github.com/pitrou/pyarrow-hotfix, without adding a required dependency on that package)
I did a similar fix in pandas, but since geopandas uses pyarrow directly, instead of through pd.read_parquet, I thought I could add the same here.
=> Parquet/Feather IO: disable PyExtensionType autoload

CHANGELOG.md, geopandas/io/file.py, geopandas/io/tests/test_file.py
Resolves #3055 
This makes reading a data source that lacks geometry the same between the Fiona and Pyogrio engines by returning a Pandas DataFrame instead of a GeoDataFrame; this is also the same as the result when using the `ignore_geometry` keyword.
I have this listed as an API change; should this be a potentially-breaking change instead?
=> API: Fiona engine: return a Pandas DataFrame when no geometry available

geopandas/geoseries.py
Addresses https://github.com/geopandas/geopandas/issues/2948
In recent pandas, internal construction from a Manager object no longer goes through `_constructor`, but there is now a `_constructor_from_mgr`. Overriding this so we can implement our "_geoseries_constructor_with_fallback" logic that we have for `_constructor` there as well.
Our `GeoSeries._constructor` is `_geoseries_constructor_with_fallback`, which does:
https://github.com/geopandas/geopandas/blob/49c208ab95fa7cebd8553cba264ea3dc65e272fd/geopandas/geoseries.py#L40-L51
and currently the `GeoSeries(..)` init will raise that TypeError if being passed a manager that is not of geometry dtype.
=> COMPAT: ensure GeoSeries fallback to Series for construction from mgr

.github/workflows/tests.yaml, geopandas/geodataframe.py
With CoW enabled, the index is not necessarily an identical object (in python `is` sence), but it's still identical from pandas' point of view, and pandas has a `Index.is_()` method to check for this. 
This fixes a few of the failures on the dev build (where we test with CoW enabled)
=> BUG: fix getting row as Series for CoW

geopandas/io/tests/test_file.py
Pandas main has a regression with using `check_dtype=False`, which will probably be fixed on the pandas side. But, looking at the test where the failure was showing up, we can also easily make the test more explicit.
Closes #3093
=> TST: update read_file test to be more specific about expected dtype

CHANGELOG.md, geopandas/geodataframe.py, geopandas/tests/test_overlay.py, geopandas/tools/overlay.py
Resolves #3073 
Remark: Not described in the issue, but the function `test_overlap_make_valid()` was also still testing on `buffer(0)` for the fixed bowtie. From what I read online, `buffer(0)` was an old workaround from when `make_valid()` function from Shapely didn't exist yet that slightly changes the geometry and thus makes this test fail on:
```python
if should_make_valid:
df_overlay_bowtie = overlay(df1, df_bowtie, make_valid=should_make_valid)
assert df_overlay_bowtie.at[0, "geometry"].equals(fixed_bowtie)
assert df_overlay_bowtie.at[1, "geometry"].equals(fixed_bowtie)
```
I thus also changed it to also use the more recent `make_valid()` function from Shapely here.
=> REF: Replace the usage of buffer(0) with make_valid

.github/workflows/tests.yaml, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tests/test_merge.py
xref #3060
With [6b4857e](https://github.com/geopandas/geopandas/pull/3080/commits/6b4857ec8d1bcccb52984d2af1b9685349d37ed7) we are down to a mere 34992 warnings (commits after are fixes for old pandas).
With [5d7d146](https://github.com/geopandas/geopandas/pull/3080/commits/5d7d14672255a6fdededc1b92416f8011adfd450) we are down to 346
[482c989](https://github.com/geopandas/geopandas/pull/3080/commits/482c98926c37d6d2dab7c4c4fd950815a81a50d0) is a bit more convoluted than the others. Originally I didn't think we needed this, but there are warnings about this in e.g. test_clip.py (and with it we are down to 311). Since we have quite some logic for `GeoSeries._constructor_expanddim`, I opted to directly construct the dataframe (and fortunately we can actually do this in the DataFrame case as …
=> COMPAT: add pandas blockmanager alternative apis for _constructor like things

CHANGELOG.md, geopandas/explore.py, geopandas/tests/test_explore.py
As pointed out by @anitagraser on Mastodon, `explore()` raises an error when there is a missing or an empty geometry in the active column. This drops affected rows prior generating a JSON for Folium, as there's nothing to show.
=> BUG: allow None and empty geoms in explore

CHANGELOG.md, geopandas/array.py, geopandas/io/tests/test_file.py
Closes #3099.
Like `_from_sequence` right above, I minimally edited the abstract base function to give the desired behavior.
@martinfleis think this warrants its own test since it's more or less an alias of `from_wkt`...?
=> ENH: Add GeometryArray._from_sequence_of_strings

CHANGELOG.md, doc/source/docs/reference/geoseries.rst, geopandas/array.py, geopandas/base.py, geopandas/tests/test_geom_methods.py
We have contains_properly already in sindex as an allowed predicate but did not have one explicitly exposed.
Part of #2010
=> ENH: add contains_properly predicate method

CHANGELOG.md, geopandas/array.py, geopandas/geoseries.py, geopandas/tests/test_array.py, geopandas/tests/test_geoseries.py
Resolves #2962
Reference #2791
Remark: I noticed a method called `_from_wkb_or_wkb` in `GeoSeries`, I suppose this should be `_from_wkb_or_wkt`? If this is the case, shall I change this in this PR or in a seperate one?
=> ENH: add on_invalid parameter to from_wkt and from_wkb

CHANGELOG.md, geopandas/tools/overlay.py
Closes #3069
I suppose ideally this would have a regression test as part of the commit, but I'm not exactly sure how to produce some minimal test where the `buffer(0)` vs `make_valid` difference is present
(and I suppose the changelog for 0.14.2 needs to be added to main as well, I'm not sure how I should have done this best, since the regression is already solved on main)
=> BUG: Overlay regression from incorrect refactor

CHANGELOG.md
This is the changelog entry as it exists on the 0.14.x branch (from merging https://github.com/geopandas/geopandas/pull/3074, cherry-picking https://github.com/geopandas/geopandas/pull/3094 (https://github.com/geopandas/geopandas/commit/7c8fa85963273a17dee76a7d19b7a3c8a6b8aeee), and the release commit). 
Adding it to the main branch as well (for this specific case where we merged directly to the release branch)so we correctly keep track of it in the main branch / stable docs.
=> DOC/RLS: add 0.14.2 changelog to main branch as well

geopandas/plotting.py
Current plotting methods simply call `plt.draw()`  at the end. 
This assumes that the figure to which the plot-axes belongs to is managed by `pyplot` and that it is also the currently active figure. 
If a custom axes is provided (e.g. using `gdf.plot(ax=ax)`) and the associated figure is not properly recognized by `pyplot`, then the final call to `plt.draw()` will trigger the creation **of a new figure** rather than drawing the figure to which the axes belong to.
Since `plt.draw()` defaults to `plt.gcf().canvas.draw_idle()`, I suggest replacing it with `ax.figure.canvas.draw_idle()` to ensure that the correct figure is triggered.
To give a quick example where the current implementation can cause problems: If you initialize a figure in a jupyter-notebook cell and call `gdf.plot()` in a …
=> Make sure gdf.plot() triggers drawing the figure of the used plot-axes

geopandas/conftest.py, geopandas/io/tests/test_file.py
After merging https://github.com/geopandas/geopandas/pull/3084, the nybb zip file changed directory, but we were using that url for testing reading from url.
=> TST: update new url for nybb dataset

geopandas/tests/test_pandas_methods.py, pyproject.toml
Follow-up on https://github.com/geopandas/geopandas/pull/2966#issuecomment-1878816712:
- Fixes the warning in our tests (by passing the `include_groups=False` keyword if needed instead of selecting the columns)
- Adds an additional test case explicitly selecting columns, and parametrized that with different geometry name (see the mentioned issue, this should fail with latest pandas)
=> TST: update groupby test to handle included group columns with pandas >= 2.2 + test with non-default geometry name

.github/workflows/tests.yaml, geopandas/io/tests/test_file.py, pyproject.toml
A next batch of warning fixes. This ignores a few external warnings we can't do anything about.
=> MAINT: reduce warnings in the tests

geopandas/io/arrow.py, geopandas/io/tests/test_arrow.py
Related to https://github.com/geopandas/geopandas/issues/3143. 
Do we want to warn if not using ISO?
=> COMPAT: only use ISO WKB flavor in to_parquet for GEOS that supports it

CHANGELOG.md
Starting a whatsnew entry for 0.14.3 (so this can be backported in https://github.com/geopandas/geopandas/pull/3161)
=> DOC/RLS: start changelog for 0.14.3

geopandas/base.py
We currently have a whole bunch of failures in the dev build with pandas main because of a change in the `.names` attribute of an Index no longer returning a list-like (FrozenList) but a tuple. This small fix will ensure it works in either case.
(https://github.com/pandas-dev/pandas/pull/57042#issuecomment-1935700777)
=> COMPAT: fix _get_index_for_parts (explode, etc) for future pandas

geopandas/_compat.py, geopandas/tests/test_dissolve.py, geopandas/tests/test_pandas_methods.py
Two fixes
* the deprecated convert_dtypes has been removed
* In dissolve, the value for geometry in non observed categorical groups has changed (due to https://github.com/pandas-dev/pandas/pull/55738). We also should deprecated the default of observed from false to true to match pandas (created #3192 for this).
=> COMPAT: pandas 3 related test updates

doc/source/getting_started/install.rst, pyproject.toml, requirements-dev.txt
The specification for `optional-dependencies` is part of PEP 621
<https://peps.python.org/pep-0621/>. See
<https://packaging.python.org/en/latest/specifications/pyproject-toml/#pyproject-toml-spec>
for latest specification.
I added the dependencies to `optional-dependencies` based on
`./requirements-dev.txt`, `./environment.yml` and #2990.
This would be useful for defining the optional dependencies when packaging
`geopandas` for e.g. `nixpkgs`
(<https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/geopandas/default.nix>)
as it is better for them to be defined here in the main repository than
downstream. As there is already code in `./geopandas/` that use these optional
dependencies, I believe they should be documented somewhere.
I did not update …
=> MAINT: Add optional-dependencies to pyproject.toml

.github/workflows/tests.yaml, ci/envs/312-latest-conda-forge_no_pyproj.yaml, geopandas/_compat.py, geopandas/array.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/io/file.py, geopandas/io/tests/test_arrow.py, geopandas/io/tests/test_file.py, geopandas/tests/test_array.py, geopandas/tests/test_crs.py, geopandas/tests/test_dissolve.py, geopandas/tests/test_explore.py, geopandas/tests/test_geocode.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geom_methods.py, geopandas/tests/test_geoseries.py, geopandas/tests/test_merge.py, geopandas/tests/test_op_output_types.py, geopandas/tests/test_overlay.py, geopandas/tests/test_pandas_methods.py, geopandas/tests/test_plotting.py, geopandas/tests/test_testing.py, geopandas/tools/tests/test_clip.py, geopandas/tools/tests/test_sjoin.py, pyproject.toml
Closes #2077
When pyproj is not available and a user tries to set a CRS, it currently falls back to `None` and warns about the situation. It may be cleaner to raise an error to avoid potential issues with that though but you wouldn't be able to read a file in such a case. Now you can read it but you won't get CRS support.
Also, raising would require a ton of skips in our tests. Warnings can just be silenced.
=> ENH: make pyproj a soft-dependency

geopandas/geoseries.py
ffill/ bfill methods are to be used instead, neither of which are implemented on a GeoSeries
=> COMPAT: pandas 3 removes `method` kwarg to fillna

geopandas/io/arrow.py
This should use intersphinx mapping and render as a link to https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_table.html
see also https://github.com/geopandas/geopandas/pull/2016
=> DOC: link to pyarrow.parquet.read_table

ci/envs/311-dev.yaml, geopandas/io/file.py, geopandas/io/tests/test_file.py
Replaces broken usage with deprecated usage. Disentangling GeoPandas from fiona's path module is left as a TODO.
Resolves #3207
@m-richards @jorisvandenbossche I think this should get the project back in green.
=> COMPAT: Update import of parse_path from fiona

ci/envs/310-pd20-conda-forge.yaml, ci/envs/311-dev.yaml, geopandas/io/file.py, geopandas/io/tests/test_file.py, geopandas/io/util.py
Closes #3207. It's worth looking at the diff before 12393dc773bc5213538ee3751fa53a72ec353180. I was originally intending to just fix the zipfile case and still depend on the internal details to push down the road until fiona 1.11/  fiona 2 for a future break. But I was looking into how we could replace this, and it actually seemed simpler to pinch the pyogrio logic for this, than to work out how to come up with a minimal equivalent of the fiona path classes - which we only want specifically for this purpose.
Not sure how we feel about introducing the new code / duplication.
=> MAINT: Fiona 1.10 compat for zip files

geopandas/tests/test_extension_array.py, geopandas/tests/test_overlay.py
From pandas' changelog for 3.0:
> Enforce deprecation in [testing.assert_series_equal()](https://pandas.pydata.org/docs/dev/reference/api/pandas.testing.assert_series_equal.html#pandas.testing.assert_series_equal) and [testing.assert_frame_equal()](https://pandas.pydata.org/docs/dev/reference/api/pandas.testing.assert_frame_equal.html#pandas.testing.assert_frame_equal) with object dtype and mismatched null-like values, which are now considered not-equal ([GH 18463](https://github.com/pandas-dev/pandas/issues/18463))
I commented earlier about that it would be nice to have a keyword for this (https://github.com/pandas-dev/pandas/pull/52081#issuecomment-1620648937), although I think that would not actually have helped in this case for us to avoid the `test_unstack` changes.
This are …
=> TST: compat with pandas 3.0 for strict null check in assert_frame_equal

CHANGELOG.md, geopandas/geoseries.py, geopandas/tests/test_geoseries.py
Closes #3199 using existing functions in GeoDataFrame.
Have not included `na` as an attribute as Properties aren't used in GeoSeries as far as I understand.
I noted default of `GeoDataFrame.to_json` show_bbox is False, but the existing code defaults to True, hence have explicitly left default as True.
=> ENH: show_bbox and drop_id added to geoseries.to_json

CHANGELOG.md, geopandas/array.py, geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
Closes #2770
Closes #1038, #3160 (superceded PRs) 
This originally started with trying to rebase #1038, but that solution was breaking some tests due to column sort order, and also doesn't seem to implement what is discussed in the thread. I think this is a faithful implementation of what is discussed in #1038 minus the `geometry_name` discussion except for 
>But if the values have a name, it can also be an option to keep the original geometry column intact (not necessarily the default, but people could do drop=False to keep the original one)
as the default is drop=False as it would be quite odd to have drop=False the default for string like arguments and drop=True the default for Series like arguments.
(maybe I've misinterpreted that though. If this does become not straightforward to …
=> BUG/API: Set geometry api where `col` is named / with `drop=True`

geopandas/tools/sjoin.py, geopandas/tools/tests/test_sjoin.py
Closes #3239 
Moving the sorting to the query so we don't have to deal with it later. I _think_ it does not brake anything else.
=> REGR: fix order of left sjoin with within predicate

geopandas/tests/test_geodataframe.py
Fixing the issue caused by #3237. The set_geometry test was split to two, but the pyproj-related skip was added to the wrong part.
=> TST: properly skip set_geometry tests when pyproj is not available

CHANGELOG.md
Including the version information in the changelog + minor linting of markdown. 
Once the 1.0 is fully out, I would rename the header to 1.0. But until then, it may help to be explicit when people are going to be testing against pre-releases.
=> RLS: mark 1.0.0-alpha1 in the changelog

.github/workflows/versioneer.yml
This should hopefully resolve void PRs like #3238. Instead of running the stable black, we run pre-commit with whatever version is set there. It should also resolve unnecessary PRs on forks.
=> GHA: update versioneer GHA so it uses pre-commit and does not run on forks

geopandas/tests/test_geodataframe.py
Follow up on #3237 to make these tests which don't rely on the nybb data structure use a toy dataset instead. Didn't managed to get to this in time for the original merge (https://github.com/geopandas/geopandas/pull/3237/files#r1546244011)
=> TST: remove nybb usage in set geometry api tests

geopandas/geodataframe.py
A small follow-up on https://github.com/geopandas/geopandas/pull/3237 to be consistent with our own new default and don't warn when user does `DataFrame.set_geometry(geoms)`.
This also gets emitted in `explode` with no way of silencing.
```py
from geodatasets import get_path
df = gpd.read_file(get_path('nybb'))
df.explode()
/Users/martin/Git/geopandas/geopandas/geodataframe.py:2469: FutureWarning: The `drop` keyword argument is deprecated and in future the only supported behaviour will match drop=False. To silence this warning and adopt the future behaviour, stop providing `drop` as a keyword to `set_geometry`. To replicate the `drop=True` behaviour you should update your code to
`geo_col_name = gdf.active_geometry_name; …
```
=> CLN: pass drop=None to DataFrame.set_geometry

CHANGELOG.md, doc/source/docs/reference/geoseries.rst, geopandas/array.py, geopandas/base.py, geopandas/tests/test_geom_methods.py
This is the last PR exposing shapely functionality as GeoSeries methods outlined in #2010. One last that is there is `symmetric_difference_all`, but that seems to be wrong in shapely - https://github.com/shapely/shapely/issues/2027.
=> ENH: add intersection_all

CHANGELOG.md, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geoseries.py, geopandas/tools/clip.py, geopandas/tools/tests/test_clip.py
Resolves #2937 
Exposes the existing sorting keywork in sindex.query to clip geodataframes and geoseries
=> ENH: allow sorting of geodataframe or geoseries when clipping

geopandas/geodataframe.py, geopandas/tools/overlay.py, geopandas/tools/sjoin.py
This fixes some warnings in the dev build:
```
geopandas/tests/test_geodataframe.py: 54 warnings
geopandas/tests/test_pandas_methods.py: 8 warnings
geopandas/tools/tests/test_sjoin.py: 250 warnings
/home/runner/work/geopandas/geopandas/geopandas/tools/sjoin.py:425: DeprecationWarning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
joined = pd.concat([left, right], axis=1, copy=False)
geopandas/tests/test_overlay.py: 12 warnings
/home/runner/work/geopandas/geopandas/geopandas/tools/overlay.py:19: DeprecationWarning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is …
```
=> COMPAT: avoid passing copy keyword to concat and astype for pandas 3.0

geopandas/io/file.py, geopandas/io/tests/test_file.py
While testing https://github.com/geopandas/geopandas/issues/3260#issuecomment-2078302687 I noticed I got a confusing error because I actually had no fiona installed, not because fiona was failing to write to bytes:
```
In [3]: data.to_file(outpath, layer="geometry", driver="GPKG", engine="fiona")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 3
1 if outpath.exists():
2     outpath.unlink()
----> 3 data.to_file(outpath, layer="geometry", driver="GPKG", engine="fiona")
File ~/scipy/repos/geopandas/geopandas/geodataframe.py:1349, in GeoDataFrame.to_file(self, filename, driver, schema, index, **kwargs)
1257 """Write the ``GeoDataFrame`` to a file.
1258 
1259 By default, an …
```
=> Fix error message when specifying IO engine that is not available

geopandas/base.py
Follow up on #3212. We missed two methods there.
=> API: fix the default align value in hausdorff_distance and frechet_distance

geopandas/io/tests/test_file.py
GDAL 3.9 added support of boolean fields to Shapefile driver. This should fix two of our dev env CI failures.
=> TST: GDAL 3.9 compat for boolean array in shp

geopandas/geodataframe.py
pandas has removed `CachedAccessor` and has only `Accessor` now (https://github.com/pandas-dev/pandas/pull/58733). That breaks our CI (https://github.com/geopandas/geopandas/actions/runs/9121040464/job/25088681559).
This will hopefully resolve it.
It is a bit surprising to me but I suppose that `CachedAccessor` was considered private anyway?
=> COMPAT: switch from pandas CachedAccessor to Accessor

CHANGELOG.md, geopandas/array.py, geopandas/geoseries.py, geopandas/tests/test_extension_array.py
Following the implementation of https://github.com/pandas-dev/pandas/pull/58249
This should fix the dev CI build, because pandas enabled this feature for EAs recently and added tests for it, and those tests were now failing.
=> ENH: support limit keyword in GeoSeries.fillna

CHANGELOG.md, doc/source/docs/reference/geoseries.rst, geopandas/array.py, geopandas/base.py, geopandas/tests/test_geom_methods.py
Last forgotten method as part of #2010. Will link to it from the docstring of `shared_paths` in #3215 once merged.
=> ENH: add get_geometry from shapely

.pre-commit-config.yaml, geopandas/base.py, geopandas/plotting.py, geopandas/tests/test_array.py, geopandas/tests/test_decorator.py, geopandas/tests/test_geodataframe.py, pyproject.toml
Some clean-up of our Ruff setup: 
- updating the version (with some minor required changes to the keys in the settings)
- removed a bunch of selected rules we are not really using, and some ignored rules which were actually passing (or passing with only minor positive change)
- I added the UP, SIM and I rule sets commented out in the select section, because I think those might be good to enable in a follow-up later (they are also included in the example recommendation of selection of rules at https://docs.astral.sh/ruff/linter/#rule-selection)
In general, we currently have a huge list of both selects/ignores, and personally I think it will be easier to maintain if we reduce that list (it's OK to not enable every possible rule set, as long as we enable the most important ones, and …
=> MAINT: Update ruff version and clean up settings

CHANGELOG.md, geopandas/array.py, geopandas/base.py, geopandas/tests/test_geom_methods.py
Ensuring the consistent API with #3177. 
This is currently a hard-breaking change as the method has been released as part of 0.14. It is a bit unfortunate but seems to be better than introducing a deprecation period after which we would do a hard break anyway.
=> API: change the behaviour of delaunay_triangles to consider all geometries together

CHANGELOG.md, geopandas/io/arrow.py, geopandas/io/tests/test_arrow.py
Attempts to fix `.to_parquet` not respecting "Z" geometries.
Closes #2824
=> BUG: ensure proper metadata for 3D geometry types in to_parquet

geopandas/io/arrow.py, geopandas/io/tests/test_arrow.py
Now that we require shapely >= 2, we can directly use `shapely.get_type_id` instead of going through our own `geom_type` attribute which converts the integer ids to type strings for all values, before we get the unique values of them.
That gives around a 2x speedup. However, we now also have to call `has_z` after https://github.com/geopandas/geopandas/pull/2835, and that is actually more expensive than `get_type_id`, so this PR combined with the fix to include "Z" for 3D geometries gives more or less the same result as before (so no slowdown).
=> PERF: improve performance of getting unique geometry types for GeoParquet metadata

doc/source/docs/reference/geoseries.rst, geopandas/base.py
Moving methods that behave like aggregations (considering all geoms together) under the aggregations heading.
xref https://github.com/geopandas/geopandas/issues/3201#issuecomment-2118797818
=> DOC: move aggregations to the relevant API section

geopandas/tests/test_explore.py
Compat with https://github.com/python-visualization/folium/pull/1952. There's no need to test `maxNativeZoom` on our side, keeping only the values that are relevant for our tests. That should make dev CI green again.
=> TST: test only relevant values in xyzservices explore tests

geopandas/io/arrow.py
Broken off a small piece of https://github.com/geopandas/geopandas/pull/3282, because this is a bit a tricky part and wanted to have it clearly in a separate diff.
This is needed for https://github.com/geopandas/geopandas/pull/3282 (which needs to access the schema metadata to see if there is a bbox covering column). But we should improve this in the future to avoid discovering the dataset twice (which can be expensive for eg cloud datasets)
=> Change read_parquet to read metadata upfront before reading the data

CHANGELOG.md
Grouping all items that are actually breaking, separating from new deprecations and enforced deprecations. And moved bug fixes section to the end.
=> DOC/RLS: clean-up sections in 1.0 changelog

CHANGELOG.md, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/io/tests/test_arrow.py, geopandas/io/tests/test_file.py, geopandas/io/tests/test_geoarrow.py, geopandas/io/tests/test_sql.py, geopandas/tests/test_crs.py, geopandas/tests/test_dissolve.py, geopandas/tests/test_explore.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geom_methods.py, geopandas/tests/test_geoseries.py, geopandas/tests/test_overlay.py, geopandas/tests/test_testing.py
Allows passing `None` to `set_crs` to remove CRS information from GeometryArray.
xref https://github.com/geopandas/geopandas/pull/3088#issuecomment-2142278823
Will push one more commit using this across our tests to eliminate warnings from #3088.
=> ENH: allow None in set_crs to remove CRS

geopandas/io/tests/test_file.py
pandas will now properly convert it to datetime64 (just with non-nanosecond resolution, so it is no longer out of bounds)
=> TST: update read_file out-of-bounds datetime test for pandas 3+

CHANGELOG.md, geopandas/io/sql.py, geopandas/io/tests/test_sql.py
small one to close out #2158, #2763, and stale MR #2159
Changing the default no CRS value to 0 to be consistent with postgis. There are a few different proposed approaches to this floating about the above issues/PRs, but this one is based on the comments in #2159 . It is not clear to me why -1 was selected as the no CRS value in the first place, so I may be missing some important context.
**EDIT**
Looking at shapely.get_srid(), it returns a -1 if it is run on None, but 0 when on a geometry with no CRS. The docstring does only specify -1 for 'not-a-geometry value' but does not specify 0 is the no CRS value. Perhaps this misinterpretation was the origin of using -1 as the no CRS value here?
=> BUG: allow appending df with no CRS to postgis with no CRS

geopandas/geodataframe.py, geopandas/tests/test_pandas_methods.py
Closes #3165 (in the specific case of `_geometry_column_name=="geometry"` - which is also the case which previously worked prior to the regression
=> REGR: constructor from mgr geometry col preservation

CHANGELOG.md
In he end the PR also did it for GeoDataFrame, not only GeoSeries.
=> DOC: update changelog for crs setter deprecation

doc/source/docs/user_guide.rst, doc/source/docs/user_guide/how_to.rst
This was recommended by @martinfleis in #3098.
It currently contains a tip on dropping duplicate geometries using normalize() before drop_duplicates(). It can be used as an appropriate place in the future for other How To/Hints and Tips content later.
=> DOC: Add new 'How to...' section in User Guide

doc/source/docs/user_guide/projections.rst, doc/source/gallery/plotting_basemap_background.ipynb, doc/source/gallery/polygon_plotting_with_folium.ipynb
https://github.com/OSGeo/PROJ/issues/4170 reminded me that we should stop using epsg.io as the best reference for EPSG codes.
=> DOC: replace references to epsg.io with spatialreference.org

.github/workflows/tests.yaml, geopandas/io/tests/test_sql.py
I was looking into #3338 and noticed that https://github.com/geopandas/geopandas/actions/runs/9483017108/job/26129164190 is passing, even though the postgis tests are failing. There was a typo added in #3328 that needs fixing is all.
Aiming to make sure the tests fail before I get them passing.
Here's the now failing tests: https://github.com/geopandas/geopandas/actions/runs/9499054652/job/26179125647?pr=3339 - we were swallowing the exit code with some extra bash stuff to check if all the tests were skipped (I guess this is to prevent the tests silently passing if postgis isn't installed)
=> CI: Postgis CI ignores exit codes

doc/source/docs/reference/tools.rst
Given the whole module is now deprecated and there are not datasets, I suppose there's no point in keeping it in the API reference anymore.
=> DOC: remove datasets module from API reference

doc/source/about/roadmap.md
So far, I have only removed goals that are either included in 1.0 or not planned any longer (pure Python I/O). I suppose we should have a proper discussion on what should come next, though I am not sure we need it before 1.0 release.
I think that on top of what currently remains, we should include a note on GeoArrow geometry engine we already talked about with @jorisvandenbossche and which was mentioned in the CZI proposal (but that is likely a long-term one).
I am no longer sure about the prepared stuff as @jorisvandenbossche mentioned GEOS might do that?
=> DOC: update roadmap for post-1.0 era

geopandas/io/arrow.py
I noticed this in the dask-geopandas tests, and strictly speaking it is also a small improvement in the code logic for geopandas here, because right now in read_feather the metadata was decoded twice.
=> Avoid read_feather to decode metadata twice + fix _arrow_to_geopandas for dask-geopandas

doc/source/docs/reference/geodataframe.rst, doc/source/docs/user_guide/data_structures.rst, doc/source/docs/user_guide/geometric_manipulations.rst, doc/source/docs/user_guide/io.rst, doc/source/docs/user_guide/mergingdata.rst, doc/source/getting_started.md, doc/source/getting_started/install.rst, doc/source/getting_started/introduction.ipynb, geopandas/geodataframe.py
I was really meaning to do this a few months ago and just ran out of time. Hoping this is non controvertial changes. Not particularly attached to any so happy to revert segments if there isn't consensus. The main things I've changed are:
* Tightening up the dicussion of active geometry columns vs "geometry" columns. I think now that we've discussed this a bit more and have `active_geometry_name` as a property we've got a proper way to refer to this, while the user guide still refers to a "geometry" column (which I think perhaps should have been `geometry` column in the old language anyway)
* IO introduction for to_file now says you don't need to specify a driver if you give a file extension
* Trying to avoid language which gets out of date where possible (referring to geoparquet 1.0.0, …
=> DOC: Documentation tidy up

geopandas/io/file.py, geopandas/io/tests/test_file.py
Tiny typo fix. 
I saw this as an error message and spotted the typo. 
I didn't update the changelog as I assume this is too small to track.
=> DOC: Fix small typos in `io.file`

CHANGELOG.md, geopandas/explore.py, geopandas/tests/test_explore.py
As per @anitagraser's report in #2378, this snippet caused JSON serialisation error even though we say we support datetime.
```py
import pandas as pd
import shapely
df = gpd.GeoDataFrame(
index=[pd.Timestamp("2018-01-01 12:02:00"), pd.Timestamp("2018-01-02 12:02:00")],
geometry=[shapely.Point(0, 0), shapely.Point(2, 0)],
)
df.index.name = "t"
df.explore()
```
Interestingly enough, non-named datetime index was fine. Only named caused issues.
Fixed by explicitly checking for index dtype and converting as we do with columns.
=> BUG: support datetime in named index in explore()

CHANGELOG.md, geopandas/explore.py, geopandas/tests/test_explore.py
small follow up to #3360.
I also swapped the astype call for the index from str to string for consistency with the columns - this will mean that NA values are preserved in the JSON (I also looked at going from string to str to keep nan /None / pd.NA but we already explicitly test NA behaviour and this would break that)
=> BUG: Explore json non serialisable index fix

geopandas/tests/test_merge.py
Removes the warning:
```
/home/runner/work/geopandas/geopandas/geopandas/tests/test_merge.py:137: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
partial_none_case.iloc[0] = None
```
=> TST: Use explicit copy to eliminate the warning.

CHANGELOG.md, geopandas/geoseries.py
=> COMPAT: Delete the `GeoSeries.select` method (removed in pandas)

.github/workflows/tests.yaml
This reverts #3186, as pytest [8.3](https://github.com/pytest-dev/pytest/releases/tag/8.3.0) now moves the xfail tracebacks to a new flag and restores the pre 8.0 behaviour for the `-ra` option ([12231](https://github.com/pytest-dev/pytest/pull/12280))
=> TST/CI: show xfails in test summary again

geopandas/geodataframe.py, geopandas/io/tests/test_arrow.py
The `LZ4` and `ZSTD` compression codecs are supported by [`pyarrow.parquet.write_table`](https://arrow.apache.org/docs/16.1/python/generated/pyarrow.parquet.write_table.html), and should work when saving a `geopandas.GeoDataFrame` to a GeoParquet file.
**Preview** at https://geopandas--3399.org.readthedocs.build/en/3399/docs/reference/api/geopandas.GeoDataFrame.to_parquet.html
=> DOC: Document LZ4 and ZSTD compression codecs in `to_parquet`

CHANGELOG.md, geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
Alternate to #3380, have opted for a test using regular enums and not str enums as they're only in the standard library from 3.11 onwards.
=> BUG: Fix geodataframe constructor not supporting classes with name attributes besides (Geo)Series

CHANGELOG.md, geopandas/io/file.py, geopandas/io/tests/test_file.py
Bug is described in issue #3377
Solution is to pass down the layer argument from gpd.read_file to pyogrio.read_info to prevent the unwaranted warning.
=> BUG:  incorrect warning in read_file for pyogrio when layer keyword is provided

geopandas/io/_geoarrow.py, geopandas/io/tests/test_geoarrow.py
See https://github.com/geopandas/geopandas/issues/3407
This at least raises an informative error message. But we should also consider defaulting to some geometry type.
=> BUG: raise proper error message when exporting empty GeoDataFrame to geoarrow

geopandas/io/arrow.py
I guess that was an oversight or am I missing something here?
=> DOC: Add GeoParquet 1.1.0 to arrow.py docs

geopandas/io/arrow.py, geopandas/io/tests/test_arrow.py
The geometry_column defaults to None, but in the following code this may lead to issues.
Add documentation for the parameter.
=> BUG: Properly handle geometry_encoding if None and add docs

geopandas/explore.py
The documentation for `missing_kwds` in `explore` was missing.
=> DOC: Document missing_kwds in `explore`

.gitattributes, .gitignore, geopandas/array.py, geopandas/tests/test_geodataframe.py
`geopandas.array.GeometryArray._reduce` issues a FutureWarning if the parameter `keepdims` is not set. `GeometryArray` inherits from `pandas.api.extensions.ExtensionArray` and its `_reduce` is overridden in `GeometryArray`.  Setting `keepdims=False` in `GeometryArray._reduce` turns off this warning. 
See issue #3403 for details.
=> COMPAT: include keepdims GeometryArray._reduce

.pre-commit-config.yaml, CONTRIBUTING.md, doc/source/community/contributing.rst, environment-dev.yml, geopandas/_compat.py, geopandas/explore.py, geopandas/geoseries.py, geopandas/io/_geoarrow.py, geopandas/io/arrow.py, geopandas/io/file.py, geopandas/io/tests/test_arrow.py, geopandas/io/tests/test_file.py, geopandas/io/tests/test_sql.py, geopandas/tests/test_api.py, geopandas/tests/test_dissolve.py, geopandas/tests/test_extension_array.py, geopandas/tests/test_geodataframe.py, geopandas/tests/test_geoseries.py, geopandas/tests/test_op_output_types.py, geopandas/tests/test_pandas_methods.py, geopandas/tests/util.py, geopandas/tools/sjoin.py, pyproject.toml, requirements-dev.txt
- update ruff to 0.5.5
- apply needed changes in code to comply to new rules
- replace black formatting by ruff-format
- apply relevant changes in code
- update contributing docs
Didn't activate `pyupgrade` nor `pydocstyle` yet to keep PR managable.
=> ENH: Use ruff for formatting instead of black + update to 0.5.5

geopandas/_compat.py, geopandas/explore.py, geopandas/geoseries.py, geopandas/io/_geoarrow.py, geopandas/io/arrow.py, geopandas/io/tests/test_arrow.py, geopandas/tests/test_dissolve.py, geopandas/tests/test_extension_array.py
Follow up to #3371 after I noticed in #3413 that we still had a compat version defined for pandas 1.5. Using the pyproject.toml as the source of truth here
=> CLN: cleanup old version guards

.github/workflows/tests.yaml, .pre-commit-config.yaml
The linting part of our CI has started failing on the action setup. Given the action is in maintenance mode only and its readme suggests using pre-commit.ci, this PR does exactly that. I have enabled pre-commit.ci for this repo.
=> CI: use pre-commit.ci for linting checks

geopandas/tests/test_api.py
Based on the explanation in https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html#subprocess-support, this might prevent pytest-cov getting imported in the subprocess (and importing that might trigger import pytest)
=> TST: fix imports tests with latest pytest-cov

geopandas/_compat.py
Potentially forgotten import and usage of `shapely.geos`. As far as I can see `shapely.geos_version` already exists in shapely v2.0.0.
=> CLN: avoid `shapely.geos` in _compat.py

geopandas/geodataframe.py
Similar as https://github.com/geopandas/geopandas/pull/3235, but now for the remaining cases where we are doing this with pandas objects (now that pandas `main` branch implements the correct numpy semantics).
This should fix the failures on the dev CI build.
=> COMPAT: avoid np.array(.., copy=False) for pandas objects

CHANGELOG.md, geopandas/geoseries.py, geopandas/tests/test_sindex.py
Similar to #3394
Calling `append` on a geoseries raises `AttributeError: 'super' object has no attribute 'append'`.
The upstream method has been removed in [pandas 2.0](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#removal-of-prior-version-deprecations-changes), the minimum supported version in pyproject.toml
=> COMPAT: Delete the `GeoSeries.append` method (removed in pandas)

ci/envs/310-minimal.yaml, geopandas/_compat.py, geopandas/geodataframe.py, geopandas/io/file.py, geopandas/io/tests/test_file.py, geopandas/io/tests/test_sql.py, geopandas/tests/test_dissolve.py, geopandas/tests/test_overlay.py, geopandas/tests/test_pandas_methods.py, geopandas/tests/test_sindex.py
Another follow up on #3443, there I took out the pandas 1.5 version guards, but can actually take out 2.0 guards since 2.0 is the minimum version.
Note, this should be merged after #3460 -which is what originally prompted me to come back and look at this.
=> MAINT: More pandas 2 cleanups

CHANGELOG.md, geopandas/tools/_random.py, geopandas/tools/tests/test_random.py
Closes #3470 
It turns out that when we retain the order of points provided by the `STRTree.query`, we break the distribution as the internal structure of the tree propagates to the result.
=> BUG: fix uniform sampling of polygons

pyproject.toml, requirements-dev.txt
When this was added for version 2, it may have made sense to use `psycopg2-binary`. However, with version 3, the upstream docs [1] say _not_ to use `psycopg-binary`, but the `psycopg[binary]` extra instead.
[1] https://pypi.org/project/psycopg-binary/
=> Use correct binary dependency of psycopg

.github/FUNDING.yml
See https://github.com/geopandas/geopandas/pull/3450#issuecomment-2506502988, removing this in favor of https://github.com/geopandas/.github
=> Use org-wide FUNDING.yml file

geopandas/io/_geoarrow.py, geopandas/io/tests/test_geoarrow.py
Before this PR, GeoArrow `"crs"` metadata was a stringified-and-escaped JSON object, whereas a regular JSON object is what other implementations expect (and produce). (Implementations also accept a string that can be passed to PROJ generally, which is probably why this worked before!)
After this PR:
```python
import geopandas
import pyarrow as pa
df = geopandas.GeoDataFrame({"geometry": geopandas.GeoSeries.from_wkt(["POINT (0 1)"], crs="OGC:CRS84")})
pa.table(df.to_arrow()).schema.field(0).metadata
#> {b'ARROW:extension:name': b'geoarrow.wkb',
#>  b'ARROW:extension:metadata': b'{"crs": {"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type"...
```
Closes #3512.
=> BUG: Fix crs representation of GeoArrow metadata

CHANGELOG.md, geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
Closes #3501.
This issue comes up because the fix in #2577 uses `_geometry_column_name` to discern if we already should a GeoDataFrame.crs attribute. But in `set_geometry` we set the name before we do the setitem so this doesn't work.
=> BUG: Fix constructor crash with column named crs

CHANGELOG.md, geopandas/geodataframe.py, geopandas/tests/test_crs.py, geopandas/tests/test_geodataframe.py
At the moment, subclassing ``GeoDataFrame`` requires to patch a few more functions than just ``_constructor`` so that the new object does not switch back to ``GeoDataFrame`` after several operations like ``__getitem__``, ``.loc`` or ``copy``.
In the spirit of the previous discussion and PR on the same topic (#2750), I'd propose to use the object class/method rather than directly ``GeoDataFrame`` in the affected functions.
=> Do not hardcode GeoDataFrame for easier subclassing

CHANGELOG.md, benchmarks/geom_methods.py, doc/source/docs/reference/geoseries.rst, geopandas/array.py, geopandas/base.py, geopandas/tests/test_array.py, geopandas/tests/test_geoseries.py
shapely removed deprecated almost_equals on main, causing failures on our CI. Given our `geom_almost_equals` has also been deprecated for some time, removing it here as well.
=> DEPR: remove deprecated geom_almost_equals

CHANGELOG.md, environment-dev.yml, geopandas/array.py, geopandas/base.py, geopandas/tests/test_geom_methods.py
shapely 2.1 introduced the `method` and `keep_collapsed` argumetns for `make_valid`... Add them in geopandas as well.
=> ENH: add method and keep_collapsed arguments to make_valid

doc/source/about/citing.md
The name "François" should be "Fran\c{c}ois" in LaTeX.
=> DOC: Correct a name accent in citing.md

doc/source/conf.py
Replace Twitter icon with X on the geopandas website.
I followed the pandas documentation to propose this change.
https://github.com/pandas-dev/pandas/blob/main/doc/source/conf.py
https://pandas.pydata.org/docs/dev/index.html
=> DOC: Remove Twitter icon on geopandas website

CHANGELOG.md, doc/source/docs/reference/geoseries.rst, doc/source/gallery/plot_clip.ipynb, geopandas/array.py, geopandas/base.py, geopandas/geodataframe.py, geopandas/tests/test_explore.py, geopandas/tests/test_geom_methods.py
xref #2010
following the discussion we had in the dev call and #3541 , this uses natural language order rather than shapely's `coverage_` prefix.
=> ENH: add is_valid_coverage and invalid_coverage_edges

CHANGELOG.md, doc/source/docs/reference/geoseries.rst, doc/source/docs/user_guide/geometric_manipulations.rst, geopandas/array.py, geopandas/base.py, geopandas/tests/test_crs.py, geopandas/tests/test_geom_methods.py
Add a `constrained_delaunay_triangles` method on GeoSeries/GeoDataFrame as this function became available in shapely 2.1.
xref #2010
=> ENH: add constrained_delaunay_triangles

CHANGELOG.md, geopandas/io/file.py
Closes #3571 
In `read_file(url)`, opportunistically tries a range request and only downloads the whole file if range requests are explicitly not supported (`"Accept-Ranges": "none"` in the header) or if the status is not `206` (PARTIAL_CONTENT).
This makes it possible to avoid downloading large files if they can be read partially with range requests but the server doesn't explicitly advertise it with the header `"Accept-Ranges": "bytes"`.
See the issue for a further description.
=> add opportunistic range request

geopandas/base.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/tests/test_geom_methods.py
This adds notes to docstrings of all methods that require shapely 2.1 and disables positional arguments in new methods when it makes sense.
=> shapely 2.1 follow-up (docstrings, positional arguments)

geopandas/io/tests/test_file.py
Given we're trying to do a release I think it makes sense to skip the test failing here https://github.com/geopandas/geopandas/issues/3583 for the moment so the CI is not permanently red. Not familar with the original content at this link so it's a bit hard to say if this will be fixed or if it's permanently broken/ changed.
=> CI: xfail remote url test for now

CHANGELOG.md, geopandas/tests/test_overlay.py, geopandas/tools/overlay.py
When `overlay` with `how="identity"` is used on two input dataframes that have one or more equal column names, these columns with equal names aren't handled correctly. This results in having the properly suffixed "column_name_1" and "column_name_2" as well as a non-suffixed "column_name" in the output, which is not correct.
This did work correctly in previous versions of geopandas.
This PR fixes this + adds tests for this scenario.
Noticed in a test in geofileops: https://github.com/geofileops/geofileops/pull/704
=> REGR: overlay with identity doesn't handle equal input column names correctly

geopandas/_compat.py, geopandas/_decorator.py, geopandas/accessors.py, geopandas/array.py, geopandas/base.py, geopandas/explore.py, geopandas/geodataframe.py, geopandas/geoseries.py, geopandas/io/arrow.py, geopandas/io/file.py, geopandas/io/sql.py, geopandas/io/util.py, geopandas/plotting.py, geopandas/sindex.py, geopandas/testing.py, geopandas/tools/_random.py, geopandas/tools/_show_versions.py, geopandas/tools/clip.py, geopandas/tools/geocoding.py, geopandas/tools/hilbert_curve.py, geopandas/tools/overlay.py, geopandas/tools/sjoin.py, geopandas/tools/util.py, pyproject.toml
Enable the pydocstyle ruff rules, but only the rules that can be fixed automatically or by making trivial changes.
Excluded rules:
- rules that trigger a missing docstring, as the content of the new docstring should be reviewed
- rules regarding having a single line summary at the start of the docstring, as this sometimes needs a serious rewrite of the docstring
In a followup PR the more complex rules can be activated/fixed so reviewing is a bit more manageble.
=> MAINT: enable pydocstyle ruff rules - automatic and easy fixes

CHANGELOG.md
I was trying to figure out which version active_geometry_name was introduced. In the changelog, the change fell under 0.14.0, but it wasn't there when I used that version. Looking at the original [PR](https://github.com/geopandas/geopandas/pull/2943), it was originally meant to go in 0.14, but eventually ended up in 1.0.0, but the changelog wasn't updated. This PR updates the change log.
Closes #3618
=> DOC: Move `active_geometry_name` change to version 1.0.0

CHANGELOG.md, geopandas/geodataframe.py, geopandas/tests/test_geodataframe.py
Hi! This fixes #2506, an old bug that resulted in a `KeyError` when running `from_features` on data without the `properties` field. I have also updated an old test to be clear that empty or `null` `properties` do not produce any column.
Let me know if anything needs to be adjusted.
=> ENH: support missing `properties` key in `from_features`

.github/workflows/tests.yaml, geopandas/base.py, geopandas/io/tests/test_file.py
This is an enabler for https://github.com/geopandas/geopandas/pull/3623, as geoarrow doesn't support older pythons. 
I think in the past we might have preferred not having doctests tied to one of the "latest" envs because it can lead to flux in the doctest results, but I think we can review that again when it comes up.
I've moved a test into xfailing to get the CI less red. The sole failing tests are those in #3643 and maybe a pandas main groupby agg issue.
=> MAINT: Change doctest env
